import IMG from "./__photoIMPORTS";
import { nanoid } from "nanoid";

const Photos = [
  //  ----------- Black History -----------
  {
    id: nanoid(),
    category: "BlackHistory",
    src: IMG.BHM365Days,
    alt: "Black history poster with fist in color",
    name: "BHM 365 Days",
    fee: 3,
  },
  {
    id: nanoid(),
    category: "BlackHistory",
    src: IMG.BHMMalcolmX,
    alt: "Malcolm X caricature poster in color",
    name: "BHM Malcolm X",
    fee: 3,
  },
  {
    id: nanoid(),
    category: "BlackHistory",
    src: IMG.BHMMap,
    alt: "USA and Africa map poster in color",
    name: "BHM pan-Africa Map",
    fee: 3,
  },
  {
    id: nanoid(),
    category: "BlackHistory",
    src: IMG.BHMMLK,
    alt: "MLK badge poster in color",
    name: "BHM MLK",
    fee: 3,
  },
  {
    id: nanoid(),
    category: "BlackHistory",
    src: IMG.BHMPowerHand,
    alt: "black power fist in front of map poster in color",
    name: "BHM Power Hand",
    fee: 3,
  },
  {
    id: nanoid(),
    category: "BlackHistory",
    src: IMG.BHM,
    alt: "text with fist in foreground poster in color",
    name: "BHM",
    fee: 3,
  },
  {
    id: nanoid(),
    category: "BlackHistory",
    src: IMG.BH,
    alt: "malcolm x head poster in color",
    name: "Black Hx",
    fee: 3,
  },
  {
    id: nanoid(),
    category: "BlackHistory",
    src: IMG.BLMHand,
    alt: "power fist with text poster in color",
    name: "BLM Hand",
    fee: 3,
  },
  {
    id: nanoid(),
    category: "BlackHistory",
    src: IMG.MartinLutherJunior,
    alt: "MLK jr. poster in color",
    name: "Martin Luther Junior",
    fee: 3,
  },
  {
    id: nanoid(),
    category: "BlackHistory",
    src: IMG.BLMMLK,
    alt: "MLK jr. poster in color",
    name: "BLM",
    fee: 3,
  },
  {
    id: nanoid(),
    category: "BlackHistory",
    src: IMG.BlackLivesMatter,
    alt: "afro charicature in front of flag in color",
    name: "Black Lives Matter",
    fee: 3,
  },
  {
    id: nanoid(),
    category: "BlackHistory",
    src: IMG.DreamBH,
    alt: "MLK dream poster in color",
    name: "Dream BHx",
    fee: 3,
  },
  {
    id: nanoid(),
    category: "BlackHistory",
    src: IMG.EnoughIsEnough,
    alt: "George Floyd in front of text poster in color",
    name: "Enough Is Enough",
    fee: 3,
  },
  {
    id: nanoid(),
    category: "BlackHistory",
    src: IMG.FrederickDouglass,
    alt: "Frederick Douglass badge poster in color",
    name: "Frederick Douglass",
    fee: 3,
  },
  {
    id: nanoid(),
    category: "BlackHistory",
    src: IMG.FreedomBH,
    alt: "afro female poster in color",
    name: "Freedom BHx",
    fee: 3,
  },
  {
    id: nanoid(),
    category: "BlackHistory",
    src: IMG.JohnLewis,
    alt: "john lweis poster in color",
    name: "John Lewis",
    fee: 3,
  },
  {
    id: nanoid(),
    category: "BlackHistory",
    src: IMG.EveryMonthBH,
    alt: "hands in shackles poster in color",
    name: "Every Month BHx",
    fee: 3,
  },
  {
    id: nanoid(),
    category: "BlackHistory",
    src: IMG.MalcolmXBH,
    alt: "Malcolm x poster in color",
    name: "Malcolm X BHx",
    fee: 3,
  },
  {
    id: nanoid(),
    category: "BlackHistory",
    src: IMG.MLKBH,
    alt: "MLK poster in color",
    name: "MLK BHx",
    fee: 3,
  },
  {
    id: nanoid(),
    category: "BlackHistory",
    src: IMG.Riot,
    alt: "call to action poster in color",
    name: "Riot",
    fee: 3,
  },
  {
    id: nanoid(),
    category: "BlackHistory",
    src: IMG.WeCanDoIt,
    alt: "strong afro female poster in color",
    name: "We Can Do It",
    fee: 3,
  },
  //    -------------- Cat Cartoon -------------
  {
    id: nanoid(),
    category: "CatCartoon",
    src: IMG.Cat1,
    alt: "Full color cartoon cat",
    name: "Cat 1",
    fee: 3,
  },
  {
    id: nanoid(),
    category: "CatCartoon",
    src: IMG.Cat2,
    alt: "Full color cartoon cat",
    name: "Cat 2",
    fee: 3,
  },
  {
    id: nanoid(),
    category: "CatCartoon",
    src: IMG.Cat3,
    alt: "Full color cartoon cat",
    name: "Cat 3",
    fee: 3,
  },
  {
    id: nanoid(),
    category: "CatCartoon",
    src: IMG.Cat4,
    alt: "Full color cartoon cat",
    name: "Cat 4",
    fee: 3,
  },
  {
    id: nanoid(),
    category: "CatCartoon",
    src: IMG.Cat5,
    alt: "Full color cartoon cat",
    name: "Cat 5",
    fee: 3,
  },
  {
    id: nanoid(),
    category: "CatCartoon",
    src: IMG.Cat6,
    alt: "Full color cartoon cat",
    name: "Cat 6",
    fee: 3,
  },
  {
    id: nanoid(),
    category: "CatCartoon",
    src: IMG.Cat7,
    alt: "Full color cartoon cat",
    name: "Cat 7",
    fee: 3,
  },
  {
    id: nanoid(),
    category: "CatCartoon",
    src: IMG.Cat8,
    alt: "Full color cartoon cat",
    name: "Cat 8",
    fee: 3,
  },
  {
    id: nanoid(),
    category: "CatCartoon",
    src: IMG.Cat9,
    alt: "Full color cartoon cat",
    name: "Cat 9",
    fee: 3,
  },
  {
    id: nanoid(),
    category: "CatCartoon",
    src: IMG.Cat10,
    alt: "Full color cartoon cat",
    name: "Cat 10",
    fee: 3,
  },
  {
    id: nanoid(),
    category: "CatCartoon",
    src: IMG.Cat11,
    alt: "Full color cartoon cat",
    name: "Cat 11",
    fee: 3,
  },
  {
    id: nanoid(),
    category: "CatCartoon",
    src: IMG.Cat12,
    alt: "Full color cartoon cat",
    name: "Cat 12",
    fee: 3,
  },
  {
    id: nanoid(),
    category: "CatCartoon",
    src: IMG.Cat13,
    alt: "Full color cartoon cat",
    name: "Cat 13",
    fee: 3,
  },
  {
    id: nanoid(),
    category: "CatCartoon",
    src: IMG.Cat14,
    alt: "Full color cartoon cat",
    name: "Cat 14",
    fee: 3,
  },
  {
    id: nanoid(),
    category: "CatCartoon",
    src: IMG.Cat15,
    alt: "Full color cartoon cat",
    name: "Cat 15",
    fee: 3,
  },
  {
    id: nanoid(),
    category: "CatCartoon",
    src: IMG.Cat16,
    alt: "Full color cartoon cat",
    name: "Cat 16",
    fee: 3,
  },
  {
    id: nanoid(),
    category: "CatCartoon",
    src: IMG.Cat17,
    alt: "Full color cartoon cat",
    name: "Cat 17",
    fee: 3,
  },
  {
    id: nanoid(),
    category: "CatCartoon",
    src: IMG.Cat18,
    alt: "Full color cartoon cat",
    name: "Cat 18",
    fee: 3,
  },
  {
    id: nanoid(),
    category: "CatCartoon",
    src: IMG.Cat19,
    alt: "Full color cartoon cat",
    name: "Cat 19",
    fee: 3,
  },
  {
    id: nanoid(),
    category: "CatCartoon",
    src: IMG.Cat20,
    alt: "Full color cartoon cat",
    name: "Cat 20",
    fee: 3,
  },
  {
    id: nanoid(),
    category: "CatCartoon",
    src: IMG.Cat21,
    alt: "Full color cartoon cat",
    name: "Cat 21",
    fee: 3,
  },
  {
    id: nanoid(),
    category: "CatCartoon",
    src: IMG.Cat22,
    alt: "Full color cartoon cat",
    name: "Cat 22",
    fee: 3,
  },
  {
    id: nanoid(),
    category: "CatCartoon",
    src: IMG.Cat23,
    alt: "Full color cartoon cat",
    name: "Cat 23",
    fee: 3,
  },
  {
    id: nanoid(),
    category: "CatCartoon",
    src: IMG.Cat24,
    alt: "Full color cartoon cat",
    name: "Cat 24",
    fee: 3,
  },
  {
    id: nanoid(),
    category: "CatCartoon",
    src: IMG.Cat25,
    alt: "Full color cartoon cat",
    name: "Cat 25",
    fee: 3,
  },
  //    --------------- Charicatures ------------
  {
    id: nanoid(),
    category: "Charicatures",
    src: IMG.AstronautIceCream,
    alt: "astronaut in space eating ice cream in color",
    name: "Astronaut Ice Cream",
    fee: 3,
  },
  {
    id: nanoid(),
    category: "Charicatures",
    src: IMG.BarberSkater,
    alt: "barbershop pole with scrissors and skateboard in color",
    name: "Barber Skater",
    fee: 3,
  },
  {
    id: nanoid(),
    category: "Charicatures",
    src: IMG.BasketBallBombers,
    alt:
      "a bomb wearing shoes and hat and spinning a basketball in black and white",
    name: "BasketBall Bombers",
    fee: 3,
  },
  {
    id: nanoid(),
    category: "Charicatures",
    src: IMG.Bomber,
    alt: "man with spray paint can and gas mask in black and white",
    name: "Bomber",
    fee: 3,
  },
  {
    id: nanoid(),
    category: "Charicatures",
    src: IMG.BoomboxRobot,
    alt: "a transformers-like robot in front of yellow moon in color",
    name: "Boombox Robot",
    fee: 3,
  },
  {
    id: nanoid(),
    category: "Charicatures",
    src: IMG.BoxingChampion,
    alt: "a character wearing oversized headgear and boxing gloves in color",
    name: "Boxing Champion",
    fee: 3,
  },
  {
    id: nanoid(),
    category: "Charicatures",
    src: IMG.BrickGamers,
    alt: "a handheld gaming console with backwards hat in color",
    name: "Brick Gamers",
    fee: 3,
  },
  {
    id: nanoid(),
    category: "Charicatures",
    src: IMG.BrooklynBaseball,
    alt:
      "a baseball character with bat ready to swing at a pitch in black and white",
    name: "Brooklyn Baseball",
    fee: 3,
  },
  {
    id: nanoid(),
    category: "Charicatures",
    src: IMG.BurgerBastard,
    alt: "a hamburger character holding a spiked bat amd soda in color",
    name: "Burger Bastard",
    fee: 3,
  },
  {
    id: nanoid(),
    category: "Charicatures",
    src: IMG.BurgerScooter,
    alt: "a hamburger character riding a motorized scooter in color",
    name: "Burger Scooter",
    fee: 3,
  },
  {
    id: nanoid(),
    category: "Charicatures",
    src: IMG.CaferacerHelmet,
    alt: "character in large helmet riding a motorbike in color",
    name: "Cafe Racer Helmet",
    fee: 3,
  },
  {
    id: nanoid(),
    category: "Charicatures",
    src: IMG.CashRules,
    alt: "a character made of money holding two guns in color",
    name: "Cash Rules",
    fee: 3,
  },
  {
    id: nanoid(),
    category: "Charicatures",
    src: IMG.ChainsawKiller,
    alt: "man in hockey mask holding a chainsaw in monotone",
    name: "Chainsaw Killer",
    fee: 3,
  },
  {
    id: nanoid(),
    category: "Charicatures",
    src: IMG.ChocolateSquad,
    alt: "candy characters holding a boombox in color",
    name: "Chocolate Squad",
    fee: 3,
  },
  {
    id: nanoid(),
    category: "Charicatures",
    src: IMG.CigaretteKiller,
    alt: "a pack of cigarettes holding a revolver in color",
    name: "Cigarette Killer",
    fee: 3,
  },
  {
    id: nanoid(),
    category: "Charicatures",
    src: IMG.ClassicCameraman,
    alt: "an old-style film camera giving the peace sign in black and white",
    name: "Classic Cameraman",
    fee: 3,
  },
  {
    id: nanoid(),
    category: "Charicatures",
    src: IMG.Diver,
    alt:
      "a character in an oversized old-style diving helmet holding a sword in color",
    name: "Diver",
    fee: 3,
  },
  {
    id: nanoid(),
    category: "Charicatures",
    src: IMG.DonutSkater,
    alt: "a donut with sunglasses riding a skateboard in color",
    name: "Donut Skater",
    fee: 3,
  },
  {
    id: nanoid(),
    category: "Charicatures",
    src: IMG.DoubleStickMan,
    alt: "a pair of nunchucks with hands and feet in color",
    name: "Double StickMan",
    fee: 3,
  },
  {
    id: nanoid(),
    category: "Charicatures",
    src: IMG.Fighter,
    alt: "man in NY Yankees hat ready to fight in black and white",
    name: "Fighter",
    fee: 3,
  },
  {
    id: nanoid(),
    category: "Charicatures",
    src: IMG.FootballKing,
    alt: "football character wearing crown and holding trophy in color",
    name: "Football King",
    fee: 3,
  },
  {
    id: nanoid(),
    category: "Charicatures",
    src: IMG.FootballPlayer,
    alt: "footballl helmet running with ball in color",
    name: "Football Player",
    fee: 3,
  },
  {
    id: nanoid(),
    category: "Charicatures",
    src: IMG.FrankRace,
    alt: "frankenstein monster driving hotrod in color",
    name: "Frank Race",
    fee: 3,
  },
  {
    id: nanoid(),
    category: "Charicatures",
    src: IMG.GameKid,
    alt: "gameboy console holding boombox in color",
    name: "Game Kid",
    fee: 3,
  },
  {
    id: nanoid(),
    category: "Charicatures",
    src: IMG.GameMachine,
    alt:
      "old gaming machine wearing hat and glasses and holding ice cream in color",
    name: "Game Machine",
    fee: 3,
  },
  {
    id: nanoid(),
    category: "Charicatures",
    src: IMG.GameOn1,
    alt: "handheld gaming connsole holding bat in color",
    name: "Game On 1",
    fee: 3,
  },
  {
    id: nanoid(),
    category: "Charicatures",
    src: IMG.GameOn2,
    alt: "handheld gaming connsole holding bat in color",
    name: "Game On 2",
    fee: 3,
  },
  {
    id: nanoid(),
    category: "Charicatures",
    src: IMG.GamersKiller,
    alt: "handheld gaming console holding bloody knife in color",
    name: "Gamers Killer",
    fee: 3,
  },
  {
    id: nanoid(),
    category: "Charicatures",
    src: IMG.GiftFromOuterSpace,
    alt: "astronaut in space holding balloons in color",
    name: "Gift From Outer Space",
    fee: 3,
  },
  {
    id: nanoid(),
    category: "Charicatures",
    src: IMG.Golfer,
    alt: "golfball character swinging club in black and white",
    name: "Golfer",
    fee: 3,
  },
  {
    id: nanoid(),
    category: "Charicatures",
    src: IMG.GramophoneHead,
    alt:
      "oldstyle vintage record player wearing monocle and tophat in black and white",
    name: "Gramophone Head",
    fee: 3,
  },
  {
    id: nanoid(),
    category: "Charicatures",
    src: IMG.GrenadeBrain,
    alt: "a brain with components to look like a grenade in black and white",
    name: "Grenade Brain",
    fee: 3,
  },
  {
    id: nanoid(),
    category: "Charicatures",
    src: IMG.GrenadeHeart,
    alt: "a heart with components to look like a grenade in monochrome",
    name: "Grenade Heart",
    fee: 3,
  },
  {
    id: nanoid(),
    category: "Charicatures",
    src: IMG.GrenadeRibcage,
    alt: "a ribcage with components to look like a grenade in monochrome",
    name: "Grenade Ribcage",
    fee: 3,
  },
  {
    id: nanoid(),
    category: "Charicatures",
    src: IMG.Grenade,
    alt: "a grenade character wearing glasses in monochrome",
    name: "Grenade",
    fee: 3,
  },
  {
    id: nanoid(),
    category: "Charicatures",
    src: IMG.HeartToKill,
    alt: "a heart character holding two guns in color",
    name: "Heart To Kill",
    fee: 3,
  },
  {
    id: nanoid(),
    category: "Charicatures",
    src: IMG.Hello,
    alt: "a telephone booth making a phone call in color",
    name: "Hello",
    fee: 3,
  },
  {
    id: nanoid(),
    category: "Charicatures",
    src: IMG.ILikeDonut,
    alt: "a character with a donut head eating a donut in color",
    name: "I Like Donut",
    fee: 3,
  },
  {
    id: nanoid(),
    category: "Charicatures",
    src: IMG.ILoveBurger,
    alt: "a character with a hamburger head eating a burger in color",
    name: "I Love Burger",
    fee: 3,
  },
  {
    id: nanoid(),
    category: "Charicatures",
    src: IMG.IceCreamNinja,
    alt: "a sundae ice cream cone with swords in color",
    name: "Ice Cream Ninja",
    fee: 3,
  },
  {
    id: nanoid(),
    category: "Charicatures",
    src: IMG.IceCreamTruck,
    alt:
      "an ice cream truck driven by a man with a mask holding a cone in color",
    name: "Ice Cream Truck",
    fee: 3,
  },
  {
    id: nanoid(),
    category: "Charicatures",
    src: IMG.KillerMinibike,
    alt:
      "a character in a hockey mask riding a bike and holding a knife in color",
    name: "Killer Minibike",
    fee: 3,
  },
  {
    id: nanoid(),
    category: "Charicatures",
    src: IMG.KillerSkater,
    alt:
      "a masked character riding a skateboard and holding a bloody knife in color",
    name: "Killer Skater",
    fee: 3,
  },
  {
    id: nanoid(),
    category: "Charicatures",
    src: IMG.LetsPaint,
    alt: "a can of paint holding a painbrush in monochrome",
    name: "Let's Paint",
    fee: 3,
  },
  {
    id: nanoid(),
    category: "Charicatures",
    src: IMG.LetsPlay,
    alt: "a nintendo controller holding a gun and a soda in color",
    name: "Let's Play",
    fee: 3,
  },
  {
    id: nanoid(),
    category: "Charicatures",
    src: IMG.LetsPlay2,
    alt: "an Xbox controller holding a gun and a soda in color",
    name: "Let's Play 2",
    fee: 3,
  },
  {
    id: nanoid(),
    category: "Charicatures",
    src: IMG.LightBoy,
    alt: "a cracked lightbuld wearing a hat in black and white",
    name: "Light Boy",
    fee: 3,
  },
  {
    id: nanoid(),
    category: "Charicatures",
    src: IMG.MicrophoneKing,
    alt: "an elvis character holding a micrphone in black and white",
    name: "Microphone King",
    fee: 3,
  },
  {
    id: nanoid(),
    category: "Charicatures",
    src: IMG.MoneyTakers,
    alt: "a bag of money holding a gun in black and white",
    name: "Money Takers",
    fee: 3,
  },
  {
    id: nanoid(),
    category: "Charicatures",
    src: IMG.Money,
    alt: "a stack of money holding an umbrella and a drink in color",
    name: "Money",
    fee: 3,
  },
  {
    id: nanoid(),
    category: "Charicatures",
    src: IMG.MrCoffee,
    alt:
      "a coffee character wearing glasses and riding a skateboard in black and white",
    name: "Mr Coffee",
    fee: 3,
  },
  {
    id: nanoid(),
    category: "Charicatures",
    src: IMG.MummyRace,
    alt: "a wrapped mummy riding a hot rod in color",
    name: "Mummy Race",
    fee: 3,
  },
  {
    id: nanoid(),
    category: "Charicatures",
    src: IMG.PeaceChar,
    alt: "a peace sign riding a skatebord and wearing a hat in color",
    name: "Peace",
    fee: 3,
  },
  {
    id: nanoid(),
    category: "Charicatures",
    src: IMG.Pilot,
    alt: "a pilot flying a fighter jet and giving thumbs up in black and white",
    name: "Pilot",
    fee: 3,
  },
  {
    id: nanoid(),
    category: "Charicatures",
    src: IMG.PizzaBeard,
    alt: "a hipster character holding and axe and a drink in color",
    name: "Pizza Beard",
    fee: 3,
  },
  {
    id: nanoid(),
    category: "Charicatures",
    src: IMG.PizzaGangster,
    alt: "a slice of pizza holding two guns and wearing a bandana in color",
    name: "Pizza Gangster",
    fee: 3,
  },
  {
    id: nanoid(),
    category: "Charicatures",
    src: IMG.PizzaSkater,
    alt: "a slice of pizza wearing a hat and riding a skateboard in color",
    name: "Pizza Skater",
    fee: 3,
  },
  {
    id: nanoid(),
    category: "Charicatures",
    src: IMG.PlayerHead1,
    alt: "a man with a controller for a head holding a pipe wrench in color",
    name: "Player Head 1",
    fee: 3,
  },
  {
    id: nanoid(),
    category: "Charicatures",
    src: IMG.PlayerHead2,
    alt: "an animal with a controller for a head giving thumbs up in color",
    name: "Player Head 2",
    fee: 3,
  },
  {
    id: nanoid(),
    category: "Charicatures",
    src: IMG.PlayerSkater,
    alt:
      "a man  with a controller for a head holding a wrench and soda riding a skateboard in color",
    name: "Player Skater",
    fee: 3,
  },
  {
    id: nanoid(),
    category: "Charicatures",
    src: IMG.Polaroid,
    alt: "a polaroid camera holding a slurpee and riding a skateboard in color",
    name: "Polaroid",
    fee: 3,
  },
  {
    id: nanoid(),
    category: "Charicatures",
    src: IMG.Racer,
    alt: "a race car character in color",
    name: "Racer",
    fee: 3,
  },
  {
    id: nanoid(),
    category: "Charicatures",
    src: IMG.RamenStyle,
    alt: "a bowl of ramen holding a skateboard in color",
    name: "Ramen Style",
    fee: 3,
  },
  {
    id: nanoid(),
    category: "Charicatures",
    src: IMG.RobotBoombox,
    alt: "a robot dressed like a b-boy and holding a boombox in color",
    name: "Robot Boombox",
    fee: 3,
  },
  {
    id: nanoid(),
    category: "Charicatures",
    src: IMG.RubixKiller,
    alt: "a rubix cube holding two guns in color",
    name: "Rubix Killer",
    fee: 3,
  },
  {
    id: nanoid(),
    category: "Charicatures",
    src: IMG.Sailor,
    alt: "a pirate ship holding a sword in black and white",
    name: "Sailor",
    fee: 3,
  },
  {
    id: nanoid(),
    category: "Charicatures",
    src: IMG.SamuraiRider,
    alt: "a man in knight armor riding a BMX bike in black and white",
    name: "Samurai Rider",
    fee: 3,
  },
  {
    id: nanoid(),
    category: "Charicatures",
    src: IMG.Samurai,
    alt: "a man in samurai gear holding a sword in black and white",
    name: "Samurai",
    fee: 3,
  },
  {
    id: nanoid(),
    category: "Charicatures",
    src: IMG.Savage,
    alt: "a man wearing a gas mask and hat and holding a gun in color",
    name: "Savage",
    fee: 3,
  },
  {
    id: nanoid(),
    category: "Charicatures",
    src: IMG.ScooterSkater,
    alt: "a scooter that is riding a skateboard in color",
    name: "Scooter Skater",
    fee: 3,
  },
  {
    id: nanoid(),
    category: "Charicatures",
    src: IMG.Shooter,
    alt: "a camera holding a revolver in black and white",
    name: "Shooter",
    fee: 3,
  },
  {
    id: nanoid(),
    category: "Charicatures",
    src: IMG.SkateBastard,
    alt: "a skateboard holding a boombox and a drink in color",
    name: "Skate Bastard",
    fee: 3,
  },
  {
    id: nanoid(),
    category: "Charicatures",
    src: IMG.SkaterBomb,
    alt:
      "a bomb character riding a skateboard holding a soda in black and white",
    name: "Skater Bomb",
    fee: 3,
  },
  {
    id: nanoid(),
    category: "Charicatures",
    src: IMG.Skatespace,
    alt: "an astronaut in space riding a skateboard in black and white",
    name: "Skatespace",
    fee: 3,
  },
  {
    id: nanoid(),
    category: "Charicatures",
    src: IMG.Soldier,
    alt: "an army helmet holding an M16 rifle in color",
    name: "Soldier",
    fee: 3,
  },
  {
    id: nanoid(),
    category: "Charicatures",
    src: IMG.SpaceBike,
    alt: "an astronaut in space riding a bike in color",
    name: "Space Bike",
    fee: 3,
  },
  {
    id: nanoid(),
    category: "Charicatures",
    src: IMG.SpaceJump,
    alt: "an astronaut in space reaching for saturn in monocrome",
    name: "Space Jump",
    fee: 3,
  },
  {
    id: nanoid(),
    category: "Charicatures",
    src: IMG.SpaceRacer,
    alt: "an astronaut driving a hot rod in monochrome",
    name: "Space Racer",
    fee: 3,
  },
  {
    id: nanoid(),
    category: "Charicatures",
    src: IMG.SpaceSlider,
    alt: "an astronaut in space holding balloons in color",
    name: "Space Slider",
    fee: 3,
  },
  {
    id: nanoid(),
    category: "Charicatures",
    src: IMG.StayFresh,
    alt: "a watermelon slice holding a drink in color",
    name: "Stay Fresh",
    fee: 3,
  },
  {
    id: nanoid(),
    category: "Charicatures",
    src: IMG.SteampunkHeart,
    alt: "a heart made of gears in color",
    name: "Steampunk Heart",
    fee: 3,
  },
  {
    id: nanoid(),
    category: "Charicatures",
    src: IMG.SteampunkOwl,
    alt: "an owl in a tophat made of gears in color",
    name: "Steampunk Owl",
    fee: 3,
  },
  {
    id: nanoid(),
    category: "Charicatures",
    src: IMG.SteampunkRibcage,
    alt: "a ribcage made of metal and gears in monochrome",
    name: "Steampunk Ribcage",
    fee: 3,
  },
  {
    id: nanoid(),
    category: "Charicatures",
    src: IMG.SteampunkTRex,
    alt: "a T-rex wearing a tophat and made of gears and metal in monochrome",
    name: "Steampunk T-Rex",
    fee: 3,
  },
  {
    id: nanoid(),
    category: "Charicatures",
    src: IMG.StreetBasketball,
    alt: "a basketball character holding a boombox in color",
    name: "Street Basketball",
    fee: 3,
  },
  {
    id: nanoid(),
    category: "Charicatures",
    src: IMG.StreetBeetle,
    alt: "a VW beetle wearing a NY hat in color",
    name: "Street Beetle",
    fee: 3,
  },
  {
    id: nanoid(),
    category: "Charicatures",
    src: IMG.StreetBomber,
    alt:
      "a spraypaint can wearing hat and riding skateboard with boombox in color",
    name: "Street Bomber",
    fee: 3,
  },
  {
    id: nanoid(),
    category: "Charicatures",
    src: IMG.StreetGamers,
    alt: "a gameboy console riding a skateboard in color",
    name: "Street Gamers",
    fee: 3,
  },
  {
    id: nanoid(),
    category: "Charicatures",
    src: IMG.StreetKing,
    alt: "a royal crown holding a boom box in color",
    name: "Street King",
    fee: 3,
  },
  {
    id: nanoid(),
    category: "Charicatures",
    src: IMG.StreetSoccer,
    alt: "a soccer ball wearing a hat and kicking a soccer ball in color",
    name: "Street Soccer",
    fee: 3,
  },
  {
    id: nanoid(),
    category: "Charicatures",
    src: IMG.Surprise,
    alt:
      "a jack in the box character wearing mask and top hat holding knife in color",
    name: "Surprise",
    fee: 3,
  },
  {
    id: nanoid(),
    category: "Charicatures",
    src: IMG.Taco,
    alt: "a taco character holding baseball bat in color",
    name: "Taco",
    fee: 3,
  },
  {
    id: nanoid(),
    category: "Charicatures",
    src: IMG.ToasterMonster,
    alt: "a toaster holding a drink in color",
    name: "Toaster Monster",
    fee: 3,
  },
  {
    id: nanoid(),
    category: "Charicatures",
    src: IMG.TrainKiller,
    alt: "a train car holding a revolver in color",
    name: "Train Killer",
    fee: 3,
  },
  {
    id: nanoid(),
    category: "Charicatures",
    src: IMG.Vandalism,
    alt: "a can of spray paint with muliple arms in monochrome",
    name: "Vandalism",
    fee: 3,
  },
  {
    id: nanoid(),
    category: "Charicatures",
    src: IMG.Viking,
    alt: "a viking character holding axe in black and white",
    name: "Viking",
    fee: 3,
  },
  {
    id: nanoid(),
    category: "Charicatures",
    src: IMG.VintageRobot,
    alt: "an old style robot graphic in color",
    name: "Vintage Robot",
    fee: 3,
  },
  {
    id: nanoid(),
    category: "Charicatures",
    src: IMG.WarTank,
    alt: "a tank wearing a helmut and pointing ahead in color",
    name: "War Tank",
    fee: 3,
  },
  {
    id: nanoid(),
    category: "Charicatures",
    src: IMG.YourTimeWillCome,
    alt: "a clock wearing a grim reaper cloak and holding a sickle in color",
    name: "Your Time Will Come",
    fee: 3,
  },
  {
    id: nanoid(),
    category: "Charicatures",
    src: IMG.ZombieCassette,
    alt: "a cassette tape wearing a hat that says brain in color",
    name: "Zombie Cassette",
    fee: 3,
  },
  //    --------------- Dog Cartoon ------------
  {
    id: nanoid(),
    category: "DogCartoon",
    src: IMG.Dog1,
    alt: "full color cartoon dog",
    name: "Dog 1",
    fee: 3,
  },
  {
    id: nanoid(),
    category: "DogCartoon",
    src: IMG.Dog2,
    alt: "full color cartoon dog",
    name: "Dog 2",
    fee: 3,
  },
  {
    id: nanoid(),
    category: "DogCartoon",
    src: IMG.Dog3,
    alt: "full color cartoon dog",
    name: "Dog 3",
    fee: 3,
  },
  {
    id: nanoid(),
    category: "DogCartoon",
    src: IMG.Dog4,
    alt: "full color cartoon dog",
    name: "Dog 4",
    fee: 3,
  },
  {
    id: nanoid(),
    category: "DogCartoon",
    src: IMG.Dog5,
    alt: "full color cartoon dog",
    name: "Dog 5",
    fee: 3,
  },
  {
    id: nanoid(),
    category: "DogCartoon",
    src: IMG.Dog6,
    alt: "full color cartoon dog",
    name: "Dog 6",
    fee: 3,
  },
  {
    id: nanoid(),
    category: "DogCartoon",
    src: IMG.Dog7,
    alt: "full color cartoon dog",
    name: "Dog 7",
    fee: 3,
  },
  {
    id: nanoid(),
    category: "DogCartoon",
    src: IMG.Dog8,
    alt: "full color cartoon dog",
    name: "Dog 8",
    fee: 3,
  },
  {
    id: nanoid(),
    category: "DogCartoon",
    src: IMG.Dog9,
    alt: "full color cartoon dog",
    name: "Dog 9",
    fee: 3,
  },
  {
    id: nanoid(),
    category: "DogCartoon",
    src: IMG.Dog10,
    alt: "full color cartoon dog",
    name: "Dog 10",
    fee: 3,
  },
  {
    id: nanoid(),
    category: "DogCartoon",
    src: IMG.Dog11,
    alt: "full color cartoon dog",
    name: "Dog 11",
    fee: 3,
  },
  {
    id: nanoid(),
    category: "DogCartoon",
    src: IMG.Dog12,
    alt: "full color cartoon dog",
    name: "Dog 12",
    fee: 3,
  },
  {
    id: nanoid(),
    category: "DogCartoon",
    src: IMG.Dog13,
    alt: "full color cartoon dog",
    name: "Dog 13",
    fee: 3,
  },
  {
    id: nanoid(),
    category: "DogCartoon",
    src: IMG.Dog14,
    alt: "full color cartoon dog",
    name: "Dog 14",
    fee: 3,
  },
  {
    id: nanoid(),
    category: "DogCartoon",
    src: IMG.Dog15,
    alt: "full color cartoon dog",
    name: "Dog 15",
    fee: 3,
  },
  {
    id: nanoid(),
    category: "DogCartoon",
    src: IMG.Dog16,
    alt: "full color cartoon dog",
    name: "Dog 16",
    fee: 3,
  },
  {
    id: nanoid(),
    category: "DogCartoon",
    src: IMG.Dog17,
    alt: "full color cartoon dog",
    name: "Dog 17",
    fee: 3,
  },
  {
    id: nanoid(),
    category: "DogCartoon",
    src: IMG.Dog18,
    alt: "full color cartoon dog",
    name: "Dog 18",
    fee: 3,
  },
  {
    id: nanoid(),
    category: "DogCartoon",
    src: IMG.Dog19,
    alt: "full color cartoon dog",
    name: "Dog 19",
    fee: 3,
  },
  {
    id: nanoid(),
    category: "DogCartoon",
    src: IMG.Dog20,
    alt: "full color cartoon dog",
    name: "Dog 20",
    fee: 3,
  },
  {
    id: nanoid(),
    category: "DogCartoon",
    src: IMG.Dog21,
    alt: "full color cartoon dog",
    name: "Dog 21",
    fee: 3,
  },
  {
    id: nanoid(),
    category: "DogCartoon",
    src: IMG.Dog22,
    alt: "full color cartoon dog",
    name: "Dog 22",
    fee: 3,
  },
  {
    id: nanoid(),
    category: "DogCartoon",
    src: IMG.Dog23,
    alt: "full color cartoon dog",
    name: "Dog 23",
    fee: 3,
  },
  {
    id: nanoid(),
    category: "DogCartoon",
    src: IMG.Dog24,
    alt: "full color cartoon dog",
    name: "Dog 24",
    fee: 3,
  },
  {
    id: nanoid(),
    category: "DogCartoon",
    src: IMG.Dog25,
    alt: "full color cartoon dog",
    name: "Dog 25",
    fee: 3,
  },
  //    --------------- Dragon Cartoon -------------
  {
    id: nanoid(),
    category: "DragonCartoon",
    src: IMG.Dragon1,
    alt: "full color cartoon dragon",
    name: "Dragon 1",
    fee: 3,
  },
  {
    id: nanoid(),
    category: "DragonCartoon",
    src: IMG.Dragon2,
    alt: "full color cartoon dragon",
    name: "Dragon 2",
    fee: 3,
  },
  {
    id: nanoid(),
    category: "DragonCartoon",
    src: IMG.Dragon3,
    alt: "full color cartoon dragon",
    name: "Dragon 3",
    fee: 3,
  },
  {
    id: nanoid(),
    category: "DragonCartoon",
    src: IMG.Dragon4,
    alt: "full color cartoon dragon",
    name: "Dragon 4",
    fee: 3,
  },
  {
    id: nanoid(),
    category: "DragonCartoon",
    src: IMG.Dragon5,
    alt: "full color cartoon dragon",
    name: "Dragon 5",
    fee: 3,
  },
  {
    id: nanoid(),
    category: "DragonCartoon",
    src: IMG.Dragon6,
    alt: "full color cartoon dragon",
    name: "Dragon 6",
    fee: 3,
  },
  {
    id: nanoid(),
    category: "DragonCartoon",
    src: IMG.Dragon7,
    alt: "full color cartoon dragon",
    name: "Dragon 7",
    fee: 3,
  },
  {
    id: nanoid(),
    category: "DragonCartoon",
    src: IMG.Dragon8,
    alt: "full color cartoon dragon",
    name: "Dragon 8",
    fee: 3,
  },
  {
    id: nanoid(),
    category: "DragonCartoon",
    src: IMG.Dragon9,
    alt: "full color cartoon dragon",
    name: "Dragon 9",
    fee: 3,
  },
  {
    id: nanoid(),
    category: "DragonCartoon",
    src: IMG.Dragon10,
    alt: "full color cartoon dragon",
    name: "Dragon 10",
    fee: 3,
  },
  {
    id: nanoid(),
    category: "DragonCartoon",
    src: IMG.Dragon11,
    alt: "full color cartoon dragon",
    name: "Dragon 11",
    fee: 3,
  },
  {
    id: nanoid(),
    category: "DragonCartoon",
    src: IMG.Dragon12,
    alt: "full color cartoon dragon",
    name: "Dragon 12",
    fee: 3,
  },
  {
    id: nanoid(),
    category: "DragonCartoon",
    src: IMG.Dragon13,
    alt: "full color cartoon dragon",
    name: "Dragon 13",
    fee: 3,
  },
  {
    id: nanoid(),
    category: "DragonCartoon",
    src: IMG.Dragon14,
    alt: "full color cartoon dragon",
    name: "Dragon 14",
    fee: 3,
  },
  {
    id: nanoid(),
    category: "DragonCartoon",
    src: IMG.Dragon15,
    alt: "full color cartoon dragon",
    name: "Dragon 15",
    fee: 3,
  },
  {
    id: nanoid(),
    category: "DragonCartoon",
    src: IMG.Dragon16,
    alt: "full color cartoon dragon",
    name: "Dragon 16",
    fee: 3,
  },
  {
    id: nanoid(),
    category: "DragonCartoon",
    src: IMG.Dragon17,
    alt: "full color cartoon dragon",
    name: "Dragon 17",
    fee: 3,
  },
  {
    id: nanoid(),
    category: "DragonCartoon",
    src: IMG.Dragon18,
    alt: "full color cartoon dragon",
    name: "Dragon 18",
    fee: 3,
  },
  {
    id: nanoid(),
    category: "DragonCartoon",
    src: IMG.Dragon19,
    alt: "full color cartoon dragon",
    name: "Dragon 19",
    fee: 3,
  },
  {
    id: nanoid(),
    category: "DragonCartoon",
    src: IMG.Dragon20,
    alt: "full color cartoon dragon",
    name: "Dragon 20",
    fee: 3,
  },
  {
    id: nanoid(),
    category: "DragonCartoon",
    src: IMG.Dragon21,
    alt: "full color cartoon dragon",
    name: "Dragon 21",
    fee: 3,
  },
  {
    id: nanoid(),
    category: "DragonCartoon",
    src: IMG.Dragon22,
    alt: "full color cartoon dragon",
    name: "Dragon 22",
    fee: 3,
  },
  {
    id: nanoid(),
    category: "DragonCartoon",
    src: IMG.Dragon23,
    alt: "full color cartoon dragon",
    name: "Dragon 23",
    fee: 3,
  },
  {
    id: nanoid(),
    category: "DragonCartoon",
    src: IMG.Dragon24,
    alt: "full color cartoon dragon",
    name: "Dragon 24",
    fee: 3,
  },
  {
    id: nanoid(),
    category: "DragonCartoon",
    src: IMG.Dragon25,
    alt: "full color cartoon dragon",
    name: "Dragon 25",
    fee: 3,
  },
  {
    id: nanoid(),
    category: "DragonCartoon",
    src: IMG.Dragon1,
    alt: "full color cartoon dragon",
    name: "Dragon 1",
    fee: 3,
  },
  {
    id: nanoid(),
    category: "DragonCartoon",
    src: IMG.Dragon2,
    alt: "full color cartoon dragon",
    name: "Dragon 2",
    fee: 3,
  },
  {
    id: nanoid(),
    category: "DragonCartoon",
    src: IMG.Dragon3,
    alt: "full color cartoon dragon",
    name: "Dragon 3",
    fee: 3,
  },
  {
    id: nanoid(),
    category: "DragonCartoon",
    src: IMG.Dragon4,
    alt: "full color cartoon dragon",
    name: "Dragon 4",
    fee: 3,
  },
  {
    id: nanoid(),
    category: "DragonCartoon",
    src: IMG.Dragon5,
    alt: "full color cartoon dragon",
    name: "Dragon 5",
    fee: 3,
  },
  {
    id: nanoid(),
    category: "DragonCartoon",
    src: IMG.Dragon6,
    alt: "full color cartoon dragon",
    name: "Dragon 6",
    fee: 3,
  },
  {
    id: nanoid(),
    category: "DragonCartoon",
    src: IMG.Dragon7,
    alt: "full color cartoon dragon",
    name: "Dragon 7",
    fee: 3,
  },
  {
    id: nanoid(),
    category: "DragonCartoon",
    src: IMG.Dragon8,
    alt: "full color cartoon dragon",
    name: "Dragon 8",
    fee: 3,
  },
  {
    id: nanoid(),
    category: "DragonCartoon",
    src: IMG.Dragon9,
    alt: "full color cartoon dragon",
    name: "Dragon 9",
    fee: 3,
  },
  {
    id: nanoid(),
    category: "DragonCartoon",
    src: IMG.Dragon10,
    alt: "full color cartoon dragon",
    name: "Dragon 10",
    fee: 3,
  },
  {
    id: nanoid(),
    category: "DragonCartoon",
    src: IMG.Dragon11,
    alt: "full color cartoon dragon",
    name: "Dragon 11",
    fee: 3,
  },
  {
    id: nanoid(),
    category: "DragonCartoon",
    src: IMG.Dragon12,
    alt: "full color cartoon dragon",
    name: "Dragon 12",
    fee: 3,
  },
  {
    id: nanoid(),
    category: "DragonCartoon",
    src: IMG.Dragon13,
    alt: "full color cartoon dragon",
    name: "Dragon 13",
    fee: 3,
  },
  {
    id: nanoid(),
    category: "DragonCartoon",
    src: IMG.Dragon14,
    alt: "full color cartoon dragon",
    name: "Dragon 14",
    fee: 3,
  },
  {
    id: nanoid(),
    category: "DragonCartoon",
    src: IMG.Dragon15,
    alt: "full color cartoon dragon",
    name: "Dragon 15",
    fee: 3,
  },
  {
    id: nanoid(),
    category: "DragonCartoon",
    src: IMG.Dragon16,
    alt: "full color cartoon dragon",
    name: "Dragon 16",
    fee: 3,
  },
  {
    id: nanoid(),
    category: "DragonCartoon",
    src: IMG.Dragon17,
    alt: "full color cartoon dragon",
    name: "Dragon 17",
    fee: 3,
  },
  {
    id: nanoid(),
    category: "DragonCartoon",
    src: IMG.Dragon18,
    alt: "full color cartoon dragon",
    name: "Dragon 18",
    fee: 3,
  },
  {
    id: nanoid(),
    category: "DragonCartoon",
    src: IMG.Dragon19,
    alt: "full color cartoon dragon",
    name: "Dragon 19",
    fee: 3,
  },
  {
    id: nanoid(),
    category: "DragonCartoon",
    src: IMG.Dragon20,
    alt: "full color cartoon dragon",
    name: "Dragon 20",
    fee: 3,
  },
  {
    id: nanoid(),
    category: "DragonCartoon",
    src: IMG.Dragon21,
    alt: "full color cartoon dragon",
    name: "Dragon 21",
    fee: 3,
  },
  {
    id: nanoid(),
    category: "DragonCartoon",
    src: IMG.Dragon22,
    alt: "full color cartoon dragon",
    name: "Dragon 22",
    fee: 3,
  },
  {
    id: nanoid(),
    category: "DragonCartoon",
    src: IMG.Dragon23,
    alt: "full color cartoon dragon",
    name: "Dragon 23",
    fee: 3,
  },
  {
    id: nanoid(),
    category: "DragonCartoon",
    src: IMG.Dragon24,
    alt: "full color cartoon dragon",
    name: "Dragon 24",
    fee: 3,
  },
  {
    id: nanoid(),
    category: "DragonCartoon",
    src: IMG.Dragon25,
    alt: "full color cartoon dragon",
    name: "Dragon 25",
    fee: 3,
  },
  //    ----------------- Monster Cartoon --------------
  {
    id: nanoid(),
    category: "MonsterCartoon",
    src: IMG.Monster,
    alt: "Monster",
    name: "Monster",
    fee: 3,
  },
  {
    id: nanoid(),
    category: "MonsterCartoon",
    src: IMG.Monster1,
    alt: "Monster 1",
    name: "Monster 1",
    fee: 3,
  },
  {
    id: nanoid(),
    category: "MonsterCartoon",
    src: IMG.Monster2,
    alt: "Monster 2",
    name: "Monster 2",
    fee: 3,
  },
  {
    id: nanoid(),
    category: "MonsterCartoon",
    src: IMG.Monster3,
    alt: "Monster 3",
    name: "Monster 3",
    fee: 3,
  },
  {
    id: nanoid(),
    category: "MonsterCartoon",
    src: IMG.Monster4,
    alt: "Monster 4",
    name: "Monster 4",
    fee: 3,
  },
  {
    id: nanoid(),
    category: "MonsterCartoon",
    src: IMG.Monster5,
    alt: "Monster 5",
    name: "Monster 5",
    fee: 3,
  },
  {
    id: nanoid(),
    category: "MonsterCartoon",
    src: IMG.Monster6,
    alt: "Monster 6",
    name: "Monster 6",
    fee: 3,
  },
  {
    id: nanoid(),
    category: "MonsterCartoon",
    src: IMG.Monster7,
    alt: "Monster 7",
    name: "Monster 7",
    fee: 3,
  },
  {
    id: nanoid(),
    category: "MonsterCartoon",
    src: IMG.Monster8,
    alt: "Monster 8",
    name: "Monster 8",
    fee: 3,
  },
  {
    id: nanoid(),
    category: "MonsterCartoon",
    src: IMG.Monster9,
    alt: "Monster 9",
    name: "Monster 9",
    fee: 3,
  },
  {
    id: nanoid(),
    category: "MonsterCartoon",
    src: IMG.Monster10,
    alt: "Monster 10",
    name: "Monster 10",
    fee: 3,
  },
  {
    id: nanoid(),
    category: "MonsterCartoon",
    src: IMG.Monster11,
    alt: "Monster 11",
    name: "Monster 11",
    fee: 3,
  },
  {
    id: nanoid(),
    category: "MonsterCartoon",
    src: IMG.Monster12,
    alt: "Monster 12",
    name: "Monster 12",
    fee: 3,
  },
  {
    id: nanoid(),
    category: "MonsterCartoon",
    src: IMG.Monster13,
    alt: "Monster 13",
    name: "Monster 13",
    fee: 3,
  },
  {
    id: nanoid(),
    category: "MonsterCartoon",
    src: IMG.Monster14,
    alt: "Monster 14",
    name: "Monster 14",
    fee: 3,
  },
  {
    id: nanoid(),
    category: "MonsterCartoon",
    src: IMG.Monster15,
    alt: "Monster 15",
    name: "Monster 15",
    fee: 3,
  },
  {
    id: nanoid(),
    category: "MonsterCartoon",
    src: IMG.Monster16,
    alt: "Monster 16",
    name: "Monster 16",
    fee: 3,
  },
  {
    id: nanoid(),
    category: "MonsterCartoon",
    src: IMG.Monster17,
    alt: "Monster 17",
    name: "Monster 17",
    fee: 3,
  },
  {
    id: nanoid(),
    category: "MonsterCartoon",
    src: IMG.Monster18,
    alt: "Monster 18",
    name: "Monster 18",
    fee: 3,
  },
  {
    id: nanoid(),
    category: "MonsterCartoon",
    src: IMG.Monster19,
    alt: "Monster 19",
    name: "Monster 19",
    fee: 3,
  },
  {
    id: nanoid(),
    category: "MonsterCartoon",
    src: IMG.Monster20,
    alt: "Monster 20",
    name: "Monster 20",
    fee: 3,
  },
  {
    id: nanoid(),
    category: "MonsterCartoon",
    src: IMG.Monster21,
    alt: "Monster 21",
    name: "Monster 21",
    fee: 3,
  },
  {
    id: nanoid(),
    category: "MonsterCartoon",
    src: IMG.Monster22,
    alt: "Monster 22",
    name: "Monster 22",
    fee: 3,
  },
  {
    id: nanoid(),
    category: "MonsterCartoon",
    src: IMG.Monster23,
    alt: "Monster 23",
    name: "Monster 23",
    fee: 3,
  },
  {
    id: nanoid(),
    category: "MonsterCartoon",
    src: IMG.Monster24,
    alt: "Monster 24",
    name: "Monster 24",
    fee: 3,
  },
  {
    id: nanoid(),
    category: "MonsterCartoon",
    src: IMG.Monster25,
    alt: "Monster 25",
    name: "Monster 25",
    fee: 3,
  },
  {
    id: nanoid(),
    category: "MonsterCartoon",
    src: IMG.Monster26,
    alt: "Monster 26",
    name: "Monster 26",
    fee: 3,
  },
  {
    id: nanoid(),
    category: "MonsterCartoon",
    src: IMG.Monster27,
    alt: "Monster 27",
    name: "Monster 27",
    fee: 3,
  },
  {
    id: nanoid(),
    category: "MonsterCartoon",
    src: IMG.Monster28,
    alt: "Monster 28",
    name: "Monster 28",
    fee: 3,
  },
  {
    id: nanoid(),
    category: "MonsterCartoon",
    src: IMG.Monster29,
    alt: "Monster 29",
    name: "Monster 29",
    fee: 3,
  },
  {
    id: nanoid(),
    category: "MonsterCartoon",
    src: IMG.Monster30,
    alt: "Monster 30",
    name: "Monster 30",
    fee: 3,
  },
  {
    id: nanoid(),
    category: "MonsterCartoon",
    src: IMG.Monster31,
    alt: "Monster 31",
    name: "Monster 31",
    fee: 3,
  },
  {
    id: nanoid(),
    category: "MonsterCartoon",
    src: IMG.Monster32,
    alt: "Monster 32",
    name: "Monster 32",
    fee: 3,
  },
  {
    id: nanoid(),
    category: "MonsterCartoon",
    src: IMG.Monster33,
    alt: "Monster 33",
    name: "Monster 33",
    fee: 3,
  },
  {
    id: nanoid(),
    category: "MonsterCartoon",
    src: IMG.Monster34,
    alt: "Monster 34",
    name: "Monster 34",
    fee: 3,
  },
  {
    id: nanoid(),
    category: "MonsterCartoon",
    src: IMG.Monster35,
    alt: "Monster 35",
    name: "Monster 35",
    fee: 3,
  },
  {
    id: nanoid(),
    category: "MonsterCartoon",
    src: IMG.Monster36,
    alt: "Monster 36",
    name: "Monster 36",
    fee: 3,
  },
  {
    id: nanoid(),
    category: "MonsterCartoon",
    src: IMG.Monster37,
    alt: "Monster 37",
    name: "Monster 37",
    fee: 3,
  },
  {
    id: nanoid(),
    category: "MonsterCartoon",
    src: IMG.Monster38,
    alt: "Monster 38",
    name: "Monster 38",
    fee: 3,
  },
  {
    id: nanoid(),
    category: "MonsterCartoon",
    src: IMG.Monster39,
    alt: "Monster 39",
    name: "Monster 39",
    fee: 3,
  },
  {
    id: nanoid(),
    category: "MonsterCartoon",
    src: IMG.Monster40,
    alt: "Monster 40",
    name: "Monster 40",
    fee: 3,
  },
  {
    id: nanoid(),
    category: "MonsterCartoon",
    src: IMG.Monster41,
    alt: "Monster 41",
    name: "Monster 41",
    fee: 3,
  },
  {
    id: nanoid(),
    category: "MonsterCartoon",
    src: IMG.Monster42,
    alt: "Monster 42",
    name: "Monster 42",
    fee: 3,
  },
  {
    id: nanoid(),
    category: "MonsterCartoon",
    src: IMG.Monster43,
    alt: "Monster 43",
    name: "Monster 43",
    fee: 3,
  },
  {
    id: nanoid(),
    category: "MonsterCartoon",
    src: IMG.Monster44,
    alt: "Monster 44",
    name: "Monster 44",
    fee: 3,
  },
  {
    id: nanoid(),
    category: "MonsterCartoon",
    src: IMG.Monster45,
    alt: "Monster 45",
    name: "Monster 45",
    fee: 3,
  },
  {
    id: nanoid(),
    category: "MonsterCartoon",
    src: IMG.Monster46,
    alt: "Monster 46",
    name: "Monster 46",
    fee: 3,
  },
  {
    id: nanoid(),
    category: "MonsterCartoon",
    src: IMG.Monster47,
    alt: "Monster 47",
    name: "Monster 47",
    fee: 3,
  },
  {
    id: nanoid(),
    category: "MonsterCartoon",
    src: IMG.Monster48,
    alt: "Monster 48",
    name: "Monster 48",
    fee: 3,
  },
  {
    id: nanoid(),
    category: "MonsterCartoon",
    src: IMG.Monster49,
    alt: "Monster 49",
    name: "Monster 49",
    fee: 3,
  },
  {
    id: nanoid(),
    category: "MonsterCartoon",
    src: IMG.Monster50,
    alt: "Monster 50",
    name: "Monster 50",
    fee: 3,
  },
  //   ---------------- pockets ----------------
  {
    id: nanoid(),
    category: "Pocket",
    src: IMG.Abduction,
    alt: "a cat being abducted by aliens in color",
    name: "Abduction",
    fee: 3,
  },
  {
    id: nanoid(),
    category: "Pocket",
    src: IMG.AngryWaves,
    alt: "a tug boat in stormy waves in color",
    name: "Angry Waves",
    fee: 3,
  },
  {
    id: nanoid(),
    category: "Pocket",
    src: IMG.Aquarium,
    alt: "cats staring a fish in a pocket in color",
    name: "Aquarium",
    fee: 3,
  },
  {
    id: nanoid(),
    category: "Pocket",
    src: IMG.BeAwesome,
    alt: "school supplies in a pokcet in color",
    name: "Be Awesome",
    fee: 3,
  },
  {
    id: nanoid(),
    category: "Pocket",
    src: IMG.Cactus,
    alt: "a cactus in a pocket in color",
    name: "Cactus",
    fee: 3,
  },
  {
    id: nanoid(),
    category: "Pocket",
    src: IMG.CatSkeleton,
    alt: "an x-ray image of a cat in color",
    name: "Cat Skeleton",
    fee: 3,
  },
  {
    id: nanoid(),
    category: "Pocket",
    src: IMG.ChildMoon,
    alt: "a person on the moon fishing in color",
    name: "ChildMoon",
    fee: 3,
  },
  {
    id: nanoid(),
    category: "Pocket",
    src: IMG.CourageDog,
    alt: "a dog with a worried look on his face in color",
    name: "Courage Dog",
    fee: 3,
  },
  {
    id: nanoid(),
    category: "Pocket",
    src: IMG.CuteCat,
    alt: "a cat staring ahead in color",
    name: "Cute Cat",
    fee: 3,
  },
  {
    id: nanoid(),
    category: "Pocket",
    src: IMG.Dollar,
    alt: "hundred dollar bills coming out of a pocket in color",
    name: "Dollar",
    fee: 3,
  },
  {
    id: nanoid(),
    category: "Pocket",
    src: IMG.FallingCat,
    alt: "cat falling down out of inverted pocket in color",
    name: "Falling Cat",
    fee: 3,
  },
  {
    id: nanoid(),
    category: "Pocket",
    src: IMG.Fish,
    alt: "a fish swimming in a pocket in color",
    name: "Fish",
    fee: 3,
  },
  {
    id: nanoid(),
    category: "Pocket",
    src: IMG.Ghost,
    alt: "ghosts coming out of pocket with a net in color",
    name: "Ghost",
    fee: 3,
  },
  {
    id: nanoid(),
    category: "Pocket",
    src: IMG.GoldenCoins,
    alt: "gold coins overflowing out of pocket in color",
    name: "Golden Coins",
    fee: 3,
  },
  {
    id: nanoid(),
    category: "Pocket",
    src: IMG.Heart,
    alt: "a heart in a pocket with flowers growing out of it in color",
    name: "Heart",
    fee: 3,
  },
  {
    id: nanoid(),
    category: "Pocket",
    src: IMG.Hotdog,
    alt: "a weiner dog in a bun in color",
    name: "Hotdog",
    fee: 3,
  },
  {
    id: nanoid(),
    category: "Pocket",
    src: IMG.Husky,
    alt: "a husky poking his head out of a pocket in color",
    name: "Husky",
    fee: 3,
  },
  {
    id: nanoid(),
    category: "Pocket",
    src: IMG.Icecreampocket,
    alt: "two ice cream cones coming out of a pocket in color",
    name: "Ice cream",
    fee: 3,
  },
  {
    id: nanoid(),
    category: "Pocket",
    src: IMG.Knife,
    alt: "a knife in a pocket in color",
    name: "Knife",
    fee: 3,
  },
  {
    id: nanoid(),
    category: "Pocket",
    src: IMG.LoveAtFirstBite,
    alt: "pizza in a pocket in color",
    name: "Love At First Bite",
    fee: 3,
  },
  {
    id: nanoid(),
    category: "Pocket",
    src: IMG.Minion,
    alt: "a minion sticking his head out of a pocket in color",
    name: "Minion",
    fee: 3,
  },
  {
    id: nanoid(),
    category: "Pocket",
    src: IMG.MonkeyButt,
    alt: "a monkey bending over and showing his butt in color",
    name: "Monkey Butt",
    fee: 3,
  },
  {
    id: nanoid(),
    category: "Pocket",
    src: IMG.Octopus,
    alt: "an octopus in a pocket in color",
    name: "Octopus",
    fee: 3,
  },
  {
    id: nanoid(),
    category: "Pocket",
    src: IMG.Palm,
    alt: "palm trees growing out of a pocket in color",
    name: "Palm",
    fee: 3,
  },
  {
    id: nanoid(),
    category: "Pocket",
    src: IMG.Panda,
    alt: "a happy panda bear in a pocket in color",
    name: "Panda",
    fee: 3,
  },
  {
    id: nanoid(),
    category: "Pocket",
    src: IMG.PinupGirl,
    alt: "a sexy woman with head and legs coming out of pocket in color",
    name: "Pinup Girl",
    fee: 3,
  },
  {
    id: nanoid(),
    category: "Pocket",
    src: IMG.PinkPanther,
    alt: "Pink Panther in a pocket in color",
    name: "Pink Panther",
    fee: 3,
  },
  {
    id: nanoid(),
    category: "Pocket",
    src: IMG.Popcorn,
    alt: "a movie-style popcorn in color",
    name: "Popcorn",
    fee: 3,
  },
  {
    id: nanoid(),
    category: "Pocket",
    src: IMG.Pug,
    alt: "a pug dog in a pocket in color",
    name: "Pug",
    fee: 3,
  },
  {
    id: nanoid(),
    category: "Pocket",
    src: IMG.SeaStar,
    alt: "star fish in a pocket in color",
    name: "Sea Star",
    fee: 3,
  },
  {
    id: nanoid(),
    category: "Pocket",
    src: IMG.Sun,
    alt: "sun and beach umbrellas in a pocket in color",
    name: "Sun",
    fee: 3,
  },
  {
    id: nanoid(),
    category: "Pocket",
    src: IMG.Swimming,
    alt: "a man swimming in a pocket with a life in color",
    name: "Swimming",
    fee: 3,
  },
  {
    id: nanoid(),
    category: "Pocket",
    src: IMG.TropicalFruit,
    alt: "a tropical themed pocket in color",
    name: "Tropical Fruit",
    fee: 3,
  },
  {
    id: nanoid(),
    category: "Pocket",
    src: IMG.WateringFlowers,
    alt: "a girl watering flowers that a boy is holding below in color",
    name: "Watering Flowers",
    fee: 3,
  },
  {
    id: nanoid(),
    category: "Pocket",
    src: IMG.ZombieHands,
    alt: "zombie hands coming out of pocket in color",
    name: "Zombie Hands",
    fee: 3,
  },
  //   --------------- PopArt --------------
  {
    id: nanoid(),
    category: "PopArt",
    src: IMG.AlbertKisstein,
    alt: "Albert Kisstein",
    name: "Albert Kisstein",
    fee: 3,
  },
  {
    id: nanoid(),
    category: "PopArt",
    src: IMG.AmericanPsycho2,
    alt: "American Psycho 2",
    name: "American Psycho 2",
    fee: 3,
  },
  {
    id: nanoid(),
    category: "PopArt",
    src: IMG.AmericanPsycho,
    alt: "American Psycho",
    name: "American Psycho",
    fee: 3,
  },
  {
    id: nanoid(),
    category: "PopArt",
    src: IMG.BenjaminDranklin,
    alt: "Benjamin Dranklin",
    name: "Benjamin Dranklin",
    fee: 3,
  },
  {
    id: nanoid(),
    category: "PopArt",
    src: IMG.CharimanMeow,
    alt: "Chariman Meow",
    name: "Chariman Meow",
    fee: 3,
  },
  {
    id: nanoid(),
    category: "PopArt",
    src: IMG.Chef,
    alt: "Chef",
    name: "Chef",
    fee: 3,
  },
  {
    id: nanoid(),
    category: "PopArt",
    src: IMG.Covfefe,
    alt: "Covfefe",
    name: "Covfefe",
    fee: 3,
  },
  {
    id: nanoid(),
    category: "PopArt",
    src: IMG.Dope,
    alt: "Dope",
    name: "Dope",
    fee: 3,
  },
  {
    id: nanoid(),
    category: "PopArt",
    src: IMG.Dream,
    alt: "Dream",
    name: "Dream",
    fee: 3,
  },
  {
    id: nanoid(),
    category: "PopArt",
    src: IMG.GotMLK,
    alt: "Got MLK",
    name: "Got MLK",
    fee: 3,
  },
  {
    id: nanoid(),
    category: "PopArt",
    src: IMG.Heilstein,
    alt: "Heilstein",
    name: "Heilstein",
    fee: 3,
  },
  {
    id: nanoid(),
    category: "PopArt",
    src: IMG.HoHoHoChiMinh,
    alt: "HoHoHo Chi Minh",
    name: "HoHoHo Chi Minh",
    fee: 3,
  },
  {
    id: nanoid(),
    category: "PopArt",
    src: IMG.ICantBreathe,
    alt: "I Can't Breathe",
    name: "I Can't Breathe",
    fee: 3,
  },
  {
    id: nanoid(),
    category: "PopArt",
    src: IMG.JusticeForGeorgeFloyd,
    alt: "Justice For George Floyd",
    name: "Justice For George Floyd",
    fee: 3,
  },
  {
    id: nanoid(),
    category: "PopArt",
    src: IMG.LincolnUnknown,
    alt: "Lincoln Unknown",
    name: "Lincoln Unknown",
    fee: 3,
  },
  {
    id: nanoid(),
    category: "PopArt",
    src: IMG.MakeAmericaGreyAgain,
    alt: "Make America Grey Again",
    name: "Make America Grey Again",
    fee: 3,
  },
  {
    id: nanoid(),
    category: "PopArt",
    src: IMG.MeowTseTung,
    alt: "Meow Tse Tung",
    name: "Meow Tse Tung",
    fee: 3,
  },
  {
    id: nanoid(),
    category: "PopArt",
    src: IMG.Merica,
    alt: "Merica",
    name: "Merica",
    fee: 3,
  },
  {
    id: nanoid(),
    category: "PopArt",
    src: IMG.MericaTrump,
    alt: "Merica Trump",
    name: "Merica Trump",
    fee: 3,
  },
  {
    id: nanoid(),
    category: "PopArt",
    src: IMG.NoRacism,
    alt: "No Racism",
    name: "No Racism",
    fee: 3,
  },
  {
    id: nanoid(),
    category: "PopArt",
    src: IMG.Putintin,
    alt: "Putintin",
    name: "Putintin",
    fee: 3,
  },
  {
    id: nanoid(),
    category: "PopArt",
    src: IMG.RocketBoy,
    alt: "Rocket Boy",
    name: "Rocket Boy",
    fee: 3,
  },
  {
    id: nanoid(),
    category: "PopArt",
    src: IMG.RocketMan,
    alt: "Rocket Man",
    name: "Rocket Man",
    fee: 3,
  },
  {
    id: nanoid(),
    category: "PopArt",
    src: IMG.StraigtOuttaPyongYang,
    alt: "Straigt Outta Pyong Yang",
    name: "Straigt Outta Pyong Yang",
    fee: 3,
  },
  {
    id: nanoid(),
    category: "PopArt",
    src: IMG.SylvesterStalin,
    alt: "Sylvester Stalin",
    name: "Sylvester Stalin",
    fee: 3,
  },
  {
    id: nanoid(),
    category: "PopArt",
    src: IMG.TheFuhrer,
    alt: "The Fuhrer",
    name: "The Fuhrer",
    fee: 3,
  },
  {
    id: nanoid(),
    category: "PopArt",
    src: IMG.Trump,
    alt: "Trump",
    name: "Trump",
    fee: 3,
  },
  {
    id: nanoid(),
    category: "PopArt",
    src: IMG.UnderControl,
    alt: "Under Control",
    name: "Under Control",
    fee: 3,
  },
  {
    id: nanoid(),
    category: "PopArt",
    src: IMG.VivaLaEvolucion,
    alt: "Viva La Evolucion",
    name: "Viva La Evolucion",
    fee: 3,
  },
  {
    id: nanoid(),
    category: "PopArt",
    src: IMG.WeCanDoIt,
    alt: "We Can Do It",
    name: "We Can Do It",
    fee: 3,
  },
  // ----------- Presidents ------------
  {
    id: nanoid(),
    category: "President",
    src: IMG.Franklin,
    alt: "president Franklin",
    name: "Franklin",
    fee: 3,
  },
  {
    id: nanoid(),
    category: "President",
    src: IMG.Grant,
    alt: "president Grant",
    name: "Grant",
    fee: 3,
  },
  {
    id: nanoid(),
    category: "President",
    src: IMG.Hamilton,
    alt: "president Hamilton",
    name: "Hamilton",
    fee: 3,
  },
  {
    id: nanoid(),
    category: "President",
    src: IMG.Jackson,
    alt: "president Jackson",
    name: "Jackson",
    fee: 3,
  },
  {
    id: nanoid(),
    category: "President",
    src: IMG.Jefferson,
    alt: "president Jefferson",
    name: "Jefferson",
    fee: 3,
  },
  {
    id: nanoid(),
    category: "President",
    src: IMG.Lincoln,
    alt: "president Lincoln",
    name: "Lincoln",
    fee: 3,
  },
  {
    id: nanoid(),
    category: "President",
    src: IMG.Washington,
    alt: "president Washington",
    name: "Washington",
    fee: 3,
  },
  //   ---------------- Random -----------
  {
    id: nanoid(),
    category: "Random",
    src: IMG.AnchorBones,
    alt: "full color graphic",
    name: "Anchor Bones",
    fee: 3,
  },
  {
    id: nanoid(),
    category: "Random",
    src: IMG.Anchor,
    alt: "full color graphic",
    name: "Anchor",
    fee: 3,
  },
  {
    id: nanoid(),
    category: "Random",
    src: IMG.Astrocode,
    alt: "full color graphic",
    name: "Astrocode",
    fee: 3,
  },
  {
    id: nanoid(),
    category: "Random",
    src: IMG.Awesome,
    alt: "full color graphic",
    name: "Awesome",
    fee: 3,
  },
  {
    id: nanoid(),
    category: "Random",
    src: IMG.BananaSkateboard,
    alt: "full color graphic",
    name: "Banana Skateboard",
    fee: 3,
  },
  {
    id: nanoid(),
    category: "Random",
    src: IMG.BaseballPlayer,
    alt: "full color graphic",
    name: "Baseball Player",
    fee: 3,
  },
  {
    id: nanoid(),
    category: "Random",
    src: IMG.BasketballPlayer,
    alt: "full color graphic",
    name: "Basketball Player",
    fee: 3,
  },
  {
    id: nanoid(),
    category: "Random",
    src: IMG.Beetle,
    alt: "full color graphic",
    name: "Beetle",
    fee: 3,
  },
  {
    id: nanoid(),
    category: "Random",
    src: IMG.BicycleSkull,
    alt: "full color graphic",
    name: "Bicycle Skull",
    fee: 3,
  },
  {
    id: nanoid(),
    category: "Random",
    src: IMG.BirdsBeard,
    alt: "full color graphic",
    name: "Birds Beard",
    fee: 3,
  },
  {
    id: nanoid(),
    category: "Random",
    src: IMG.BrainGloves,
    alt: "full color graphic",
    name: "Brain Gloves",
    fee: 3,
  },
  {
    id: nanoid(),
    category: "Random",
    src: IMG.BreakingNoise,
    alt: "full color graphic",
    name: "Breaking Noise",
    fee: 3,
  },
  {
    id: nanoid(),
    category: "Random",
    src: IMG.Burger,
    alt: "full color graphic",
    name: "Burger",
    fee: 3,
  },
  {
    id: nanoid(),
    category: "Random",
    src: IMG.CheSmiley,
    alt: "full color graphic",
    name: "Che Smiley",
    fee: 3,
  },
  {
    id: nanoid(),
    category: "Random",
    src: IMG.CoffeeTree,
    alt: "full color graphic",
    name: "Coffee Tree",
    fee: 3,
  },
  {
    id: nanoid(),
    category: "Random",
    src: IMG.Coffee,
    alt: "full color graphic",
    name: "Coffee",
    fee: 3,
  },
  {
    id: nanoid(),
    category: "Random",
    src: IMG.Crab,
    alt: "full color graphic",
    name: "Crab",
    fee: 3,
  },
  {
    id: nanoid(),
    category: "Random",
    src: IMG.CrystalLake,
    alt: "full color graphic",
    name: "Crystal Lake",
    fee: 3,
  },
  {
    id: nanoid(),
    category: "Random",
    src: IMG.DeadSchool,
    alt: "full color graphic",
    name: "Dead School",
    fee: 3,
  },
  {
    id: nanoid(),
    category: "Random",
    src: IMG.DeadSea,
    alt: "full color graphic",
    name: "Dead Sea",
    fee: 3,
  },
  {
    id: nanoid(),
    category: "Random",
    src: IMG.DeathCity,
    alt: "full color graphic",
    name: "Death City",
    fee: 3,
  },
  {
    id: nanoid(),
    category: "Random",
    src: IMG.Deer2,
    alt: "full color graphic",
    name: "Deer 2",
    fee: 3,
  },
  {
    id: nanoid(),
    category: "Random",
    src: IMG.Deer3,
    alt: "full color graphic",
    name: "Deer 3",
    fee: 3,
  },
  {
    id: nanoid(),
    category: "Random",
    src: IMG.DeerButterfly,
    alt: "full color graphic",
    name: "Deer Butterfly",
    fee: 3,
  },
  {
    id: nanoid(),
    category: "Random",
    src: IMG.Deer,
    alt: "full color graphic",
    name: "Deer",
    fee: 3,
  },
  {
    id: nanoid(),
    category: "Random",
    src: IMG.DonutBarbell,
    alt: "full color graphic",
    name: "Donut Barbell",
    fee: 3,
  },
  {
    id: nanoid(),
    category: "Random",
    src: IMG.Eagle,
    alt: "full color graphic",
    name: "Eagle",
    fee: 3,
  },
  {
    id: nanoid(),
    category: "Random",
    src: IMG.ElectricAnchor,
    alt: "full color graphic",
    name: "Electric Anchor",
    fee: 3,
  },
  {
    id: nanoid(),
    category: "Random",
    src: IMG.ElectricBalance,
    alt: "full color graphic",
    name: "Electric Balance",
    fee: 3,
  },
  {
    id: nanoid(),
    category: "Random",
    src: IMG.ElectricBrain,
    alt: "full color graphic",
    name: "Electric Brain",
    fee: 3,
  },
  {
    id: nanoid(),
    category: "Random",
    src: IMG.ElectricDeer,
    alt: "full color graphic",
    name: "Electric Deer",
    fee: 3,
  },
  {
    id: nanoid(),
    category: "Random",
    src: IMG.ElectricSkull,
    alt: "full color graphic",
    name: "Electric Skull",
    fee: 3,
  },
  {
    id: nanoid(),
    category: "Random",
    src: IMG.ElectricSmiley,
    alt: "full color graphic",
    name: "Electric Smiley",
    fee: 3,
  },
  {
    id: nanoid(),
    category: "Random",
    src: IMG.ElectricalOwl,
    alt: "full color graphic",
    name: "Electrical Owl",
    fee: 3,
  },
  {
    id: nanoid(),
    category: "Random",
    src: IMG.EnjoyYourLie,
    alt: "full color graphic",
    name: "Enjoy Your Lie",
    fee: 3,
  },
  {
    id: nanoid(),
    category: "Random",
    src: IMG.FloatLikeButterflyStingLikeBee,
    alt: "full color graphic",
    name: "Float Like Butterfly",
    fee: 3,
  },
  {
    id: nanoid(),
    category: "Random",
    src: IMG.FlourishVandalism,
    alt: "full color graphic",
    name: "Flourish Vandalism",
    fee: 3,
  },
  {
    id: nanoid(),
    category: "Random",
    src: IMG.FlyingAstronaut,
    alt: "full color graphic",
    name: "Flying Astronaut",
    fee: 3,
  },
  {
    id: nanoid(),
    category: "Random",
    src: IMG.FroggyNight,
    alt: "full color graphic",
    name: "Froggy Night",
    fee: 3,
  },
  {
    id: nanoid(),
    category: "Random",
    src: IMG.GhostFaceBats,
    alt: "full color graphic",
    name: "Ghostface Bats",
    fee: 3,
  },
  {
    id: nanoid(),
    category: "Random",
    src: IMG.Godzilla,
    alt: "full color graphic",
    name: "Godzilla",
    fee: 3,
  },
  {
    id: nanoid(),
    category: "Random",
    src: IMG.GoodIdea,
    alt: "full color graphic",
    name: "Good Idea",
    fee: 3,
  },
  {
    id: nanoid(),
    category: "Random",
    src: IMG.GramophoneDonut,
    alt: "full color graphic",
    name: "Gramophone Donut",
    fee: 3,
  },
  {
    id: nanoid(),
    category: "Random",
    src: IMG.GreenMonster,
    alt: "full color graphic",
    name: "Green Monster",
    fee: 3,
  },
  {
    id: nanoid(),
    category: "Random",
    src: IMG.Grenade,
    alt: "full color graphic",
    name: "Grenade",
    fee: 3,
  },
  {
    id: nanoid(),
    category: "Random",
    src: IMG.HandOfRevolution,
    alt: "full color graphic",
    name: "Hand Of Revolution",
    fee: 3,
  },
  {
    id: nanoid(),
    category: "Random",
    src: IMG.HandOfZombies,
    alt: "full color graphic",
    name: "Hand Of Zombies",
    fee: 3,
  },
  {
    id: nanoid(),
    category: "Random",
    src: IMG.HeadphoneDonut,
    alt: "full color graphic",
    name: "Headphone Donut",
    fee: 3,
  },
  {
    id: nanoid(),
    category: "Random",
    src: IMG.Hipster,
    alt: "full color graphic",
    name: "Hipster",
    fee: 3,
  },
  {
    id: nanoid(),
    category: "Random",
    src: IMG.HomeHeart,
    alt: "full color graphic",
    name: "Home Heart",
    fee: 3,
  },
  {
    id: nanoid(),
    category: "Random",
    src: IMG.Icecream,
    alt: "full color graphic",
    name: "Icecream",
    fee: 3,
  },
  {
    id: nanoid(),
    category: "Random",
    src: IMG.JasonMoon,
    alt: "full color graphic",
    name: "Jason Moon",
    fee: 3,
  },
  {
    id: nanoid(),
    category: "Random",
    src: IMG.Kaiju2,
    alt: "full color graphic",
    name: "Kaiju2",
    fee: 3,
  },
  {
    id: nanoid(),
    category: "Random",
    src: IMG.Kaiju,
    alt: "full color graphic",
    name: "Kaiju",
    fee: 3,
  },
  {
    id: nanoid(),
    category: "Random",
    src: IMG.KnowYourRoots,
    alt: "full color graphic",
    name: "Know Your Roots",
    fee: 3,
  },
  {
    id: nanoid(),
    category: "Random",
    src: IMG.Liberty,
    alt: "full color graphic",
    name: "Liberty",
    fee: 3,
  },
  {
    id: nanoid(),
    category: "Random",
    src: IMG.LifeAndDeath,
    alt: "full color graphic",
    name: "Life and Death",
    fee: 3,
  },
  {
    id: nanoid(),
    category: "Random",
    src: IMG.LOL,
    alt: "full color graphic",
    name: "LOL",
    fee: 3,
  },
  {
    id: nanoid(),
    category: "Random",
    src: IMG.Milkyway,
    alt: "full color graphic",
    name: "Milkyway",
    fee: 3,
  },
  {
    id: nanoid(),
    category: "Random",
    src: IMG.NatureOfCrime,
    alt: "full color graphic",
    name: "Nature Of Crime",
    fee: 3,
  },
  {
    id: nanoid(),
    category: "Random",
    src: IMG.Nerd,
    alt: "full color graphic",
    name: "Nerd",
    fee: 3,
  },
  {
    id: nanoid(),
    category: "Random",
    src: IMG.Peace,
    alt: "full color graphic",
    name: "Peace",
    fee: 3,
  },
  {
    id: nanoid(),
    category: "Random",
    src: IMG.PizzaMoon,
    alt: "full color graphic",
    name: "Pizza Moon",
    fee: 3,
  },
  {
    id: nanoid(),
    category: "Random",
    src: IMG.PizzaScratch,
    alt: "full color graphic",
    name: "Pizza Scratch",
    fee: 3,
  },
  {
    id: nanoid(),
    category: "Random",
    src: IMG.PizzaUFO,
    alt: "full color graphic",
    name: "Pizza UFO",
    fee: 3,
  },
  {
    id: nanoid(),
    category: "Random",
    src: IMG.Pizza,
    alt: "full color graphic",
    name: "Pizza",
    fee: 3,
  },
  {
    id: nanoid(),
    category: "Random",
    src: IMG.Prismzza,
    alt: "full color graphic",
    name: "Prismzza",
    fee: 3,
  },
  {
    id: nanoid(),
    category: "Random",
    src: IMG.ReaperScream,
    alt: "full color graphic",
    name: "Reaper Scream",
    fee: 3,
  },
  {
    id: nanoid(),
    category: "Random",
    src: IMG.Recycling,
    alt: "full color graphic",
    name: "Recycling",
    fee: 3,
  },
  {
    id: nanoid(),
    category: "Random",
    src: IMG.RhymeInPeace,
    alt: "full color graphic",
    name: "Rhyme in Peace",
    fee: 3,
  },
  {
    id: nanoid(),
    category: "Random",
    src: IMG.RibcageBird,
    alt: "full color graphic",
    name: "Ribcage Bird",
    fee: 3,
  },
  {
    id: nanoid(),
    category: "Random",
    src: IMG.Scooter,
    alt: "full color graphic",
    name: "Scooter",
    fee: 3,
  },
  {
    id: nanoid(),
    category: "Random",
    src: IMG.SeaHorse,
    alt: "full color graphic",
    name: "Sea Horse",
    fee: 3,
  },
  {
    id: nanoid(),
    category: "Random",
    src: IMG.SherlockHolmes,
    alt: "full color graphic",
    name: "Sherlock Holmes",
    fee: 3,
  },
  {
    id: nanoid(),
    category: "Random",
    src: IMG.Skater,
    alt: "full color graphic",
    name: "Skater",
    fee: 3,
  },
  {
    id: nanoid(),
    category: "Random",
    src: IMG.SkaterHook,
    alt: "full color graphic",
    name: "Skater Hook",
    fee: 3,
  },
  {
    id: nanoid(),
    category: "Random",
    src: IMG.SkullNature,
    alt: "full color graphic",
    name: "Skull Nature",
    fee: 3,
  },
  {
    id: nanoid(),
    category: "Random",
    src: IMG.SmileyMoon,
    alt: "full color graphic",
    name: "Smiley Moon",
    fee: 3,
  },
  {
    id: nanoid(),
    category: "Random",
    src: IMG.Smiley,
    alt: "full color graphic",
    name: "Smiley",
    fee: 3,
  },
  {
    id: nanoid(),
    category: "Random",
    src: IMG.SmokingKills,
    alt: "full color graphic",
    name: "Smoking Kills",
    fee: 3,
  },
  {
    id: nanoid(),
    category: "Random",
    src: IMG.SoundCollector,
    alt: "full color graphic",
    name: "Sound Collector",
    fee: 3,
  },
  {
    id: nanoid(),
    category: "Random",
    src: IMG.SoundOfRain,
    alt: "full color graphic",
    name: "Sound Of Rain",
    fee: 3,
  },
  {
    id: nanoid(),
    category: "Random",
    src: IMG.StandAndBleed,
    alt: "full color graphic",
    name: "Stand and Bleed",
    fee: 3,
  },
  {
    id: nanoid(),
    category: "Random",
    src: IMG.TheBridge,
    alt: "full color graphic",
    name: "The Bridge",
    fee: 3,
  },
  {
    id: nanoid(),
    category: "Random",
    src: IMG.TheChronicle,
    alt: "full color graphic",
    name: "The Chronicle",
    fee: 3,
  },
  {
    id: nanoid(),
    category: "Random",
    src: IMG.TheCrow,
    alt: "full color graphic",
    name: "The Crow",
    fee: 3,
  },
  {
    id: nanoid(),
    category: "Random",
    src: IMG.TheMask,
    alt: "full color graphic",
    name: "The Mask",
    fee: 3,
  },
  {
    id: nanoid(),
    category: "Random",
    src: IMG.Thunderbolt,
    alt: "full color graphic",
    name: "Thunderbolt",
    fee: 3,
  },
  {
    id: nanoid(),
    category: "Random",
    src: IMG.TrainSong,
    alt: "full color graphic",
    name: "Train Song",
    fee: 3,
  },
  {
    id: nanoid(),
    category: "Random",
    src: IMG.truthHurts,
    alt: "full color graphic",
    name: "truth Hurts",
    fee: 3,
  },
  {
    id: nanoid(),
    category: "Random",
    src: IMG.UFOInvasion,
    alt: "full color graphic",
    name: "UFO Invasion",
    fee: 3,
  },
  {
    id: nanoid(),
    category: "Random",
    src: IMG.WarPeace,
    alt: "full color graphic",
    name: "War Peace",
    fee: 3,
  },
  {
    id: nanoid(),
    category: "Random",
    src: IMG.WeaponFlag,
    alt: "full color graphic",
    name: "Weapon Flag",
    fee: 3,
  },
  {
    id: nanoid(),
    category: "Random",
    src: IMG.WildBison,
    alt: "full color graphic",
    name: "Wild Bison",
    fee: 3,
  },
  {
    id: nanoid(),
    category: "Random",
    src: IMG.WildLife,
    alt: "full color graphic",
    name: "Wild Life",
    fee: 3,
  },
  {
    id: nanoid(),
    category: "Random",
    src: IMG.YinYangCats,
    alt: "full color graphic",
    name: "YinYang Cats",
    fee: 3,
  },
  {
    id: nanoid(),
    category: "Random",
    src: IMG.ZebraBones,
    alt: "full color graphic",
    name: "Zebra Bones",
    fee: 3,
  },
  //    ---------------- Snakes ------------
  {
    id: nanoid(),
    category: "SnakeCartoon",
    src: IMG.Snake1,
    alt: "snake head graphic in color",
    name: "Snake 1",
    fee: 3,
  },
  {
    id: nanoid(),
    category: "SnakeCartoon",
    src: IMG.Snake2,
    alt: "snake head graphic in color",
    name: "Snake 2",
    fee: 3,
  },
  {
    id: nanoid(),
    category: "SnakeCartoon",
    src: IMG.Snake3,
    alt: "snake head graphic in color",
    name: "Snake 3",
    fee: 3,
  },
  {
    id: nanoid(),
    category: "SnakeCartoon",
    src: IMG.Snake4,
    alt: "snake head graphic in color",
    name: "Snake 4",
    fee: 3,
  },
  {
    id: nanoid(),
    category: "SnakeCartoon",
    src: IMG.Snake5,
    alt: "snake head graphic in color",
    name: "Snake 5",
    fee: 3,
  },
  {
    id: nanoid(),
    category: "SnakeCartoon",
    src: IMG.Snake6,
    alt: "snake head graphic in color",
    name: "Snake 6",
    fee: 3,
  },
  {
    id: nanoid(),
    category: "SnakeCartoon",
    src: IMG.Snake7,
    alt: "snake head graphic in color",
    name: "Snake 7",
    fee: 3,
  },
  {
    id: nanoid(),
    category: "SnakeCartoon",
    src: IMG.Snake8,
    alt: "snake head graphic in color",
    name: "Snake 8",
    fee: 3,
  },
  {
    id: nanoid(),
    category: "SnakeCartoon",
    src: IMG.Snake9,
    alt: "snake head graphic in color",
    name: "Snake 9",
    fee: 3,
  },
  {
    id: nanoid(),
    category: "SnakeCartoon",
    src: IMG.Snake10,
    alt: "snake head graphic in color",
    name: "Snake 10",
    fee: 3,
  },
  {
    id: nanoid(),
    category: "SnakeCartoon",
    src: IMG.Snake11,
    alt: "snake head graphic in color",
    name: "Snake 11",
    fee: 3,
  },
  {
    id: nanoid(),
    category: "SnakeCartoon",
    src: IMG.Snake12,
    alt: "snake head graphic in color",
    name: "Snake 12",
    fee: 3,
  },
  {
    id: nanoid(),
    category: "SnakeCartoon",
    src: IMG.Snake13,
    alt: "snake head graphic in color",
    name: "Snake 13",
    fee: 3,
  },
  {
    id: nanoid(),
    category: "SnakeCartoon",
    src: IMG.Snake14,
    alt: "snake head graphic in color",
    name: "Snake 14",
    fee: 3,
  },
  {
    id: nanoid(),
    category: "SnakeCartoon",
    src: IMG.Snake15,
    alt: "snake head graphic in color",
    name: "Snake 15",
    fee: 3,
  },
  {
    id: nanoid(),
    category: "SnakeCartoon",
    src: IMG.Snake16,
    alt: "snake head graphic in color",
    name: "Snake 16",
    fee: 3,
  },
  {
    id: nanoid(),
    category: "SnakeCartoon",
    src: IMG.Snake17,
    alt: "snake head graphic in color",
    name: "Snake 17",
    fee: 3,
  },
  {
    id: nanoid(),
    category: "SnakeCartoon",
    src: IMG.Snake18,
    alt: "snake head graphic in color",
    name: "Snake 18",
    fee: 3,
  },
  {
    id: nanoid(),
    category: "SnakeCartoon",
    src: IMG.Snake19,
    alt: "snake head graphic in color",
    name: "Snake 19",
    fee: 3,
  },
  {
    id: nanoid(),
    category: "SnakeCartoon",
    src: IMG.Snake20,
    alt: "snake head graphic in color",
    name: "Snake 20",
    fee: 3,
  },
  {
    id: nanoid(),
    category: "SnakeCartoon",
    src: IMG.Snake21,
    alt: "snake head graphic in color",
    name: "Snake 21",
    fee: 3,
  },
  {
    id: nanoid(),
    category: "SnakeCartoon",
    src: IMG.Snake22,
    alt: "snake head graphic in color",
    name: "Snake 22",
    fee: 3,
  },
  {
    id: nanoid(),
    category: "SnakeCartoon",
    src: IMG.Snake23,
    alt: "snake head graphic in color",
    name: "Snake 23",
    fee: 3,
  },
  {
    id: nanoid(),
    category: "SnakeCartoon",
    src: IMG.Snake24,
    alt: "snake head graphic in color",
    name: "Snake 24",
    fee: 3,
  },
  {
    id: nanoid(),
    category: "SnakeCartoon",
    src: IMG.Snake25,
    alt: "snake head graphic in color",
    name: "Snake 25",
    fee: 3,
  },
  //    ------------------ SuperHero -----------
  {
    id: nanoid(),
    category: "SuperHero",
    src: IMG.ANTIVENOMPOP,
    alt: "ANTIVENOM POP",
    name: "ANTIVENOM POP",
    fee: 3,
  },
  {
    id: nanoid(),
    category: "SuperHero",
    src: IMG.ANTMANENDGAME,
    alt: "ANTMAN ENDGAME",
    name: "ANTMAN ENDGAME",
    fee: 3,
  },
  {
    id: nanoid(),
    category: "SuperHero",
    src: IMG.ARYASTARK,
    alt: "ARYASTARK",
    name: "ARYASTARK",
    fee: 3,
  },
  {
    id: nanoid(),
    category: "SuperHero",
    src: IMG.BACKTOTHEFUTURE,
    alt: "BACK TO THE FUTURE",
    name: "BACK TO THE FUTURE",
    fee: 3,
  },
  {
    id: nanoid(),
    category: "SuperHero",
    src: IMG.Battleforeternia,
    alt: "Battle for eternia",
    name: "Battle for eternia",
    fee: 3,
  },
  {
    id: nanoid(),
    category: "SuperHero",
    src: IMG.BATMANYROBIN,
    alt: "BATMAN & ROBIN",
    name: "BATMAN & ROBIN",
    fee: 3,
  },
  {
    id: nanoid(),
    category: "SuperHero",
    src: IMG.BezitaVader,
    alt: "Vader",
    name: "Vader",
    fee: 3,
  },
  {
    id: nanoid(),
    category: "SuperHero",
    src: IMG.blackpanter01,
    alt: "black panther 1",
    name: "black panther 1",
    fee: 3,
  },
  {
    id: nanoid(),
    category: "SuperHero",
    src: IMG.BlackTrooper,
    alt: "Black Trooper",
    name: "Black Trooper",
    fee: 3,
  },
  {
    id: nanoid(),
    category: "SuperHero",
    src: IMG.BLACKWIDOWENDGAME,
    alt: "BLACK WIDOW ENDGAME",
    name: "BLACK WIDOW ENDGAME",
    fee: 3,
  },
  {
    id: nanoid(),
    category: "SuperHero",
    src: IMG.BLACKW,
    alt: "BLACK WIDOW",
    name: "BLACK WIDOW",
    fee: 3,
  },
  {
    id: nanoid(),
    category: "SuperHero",
    src: IMG.BRITNEY,
    alt: "BRITNEY",
    name: "BRITNEY",
    fee: 3,
  },
  {
    id: nanoid(),
    category: "SuperHero",
    src: IMG.CAPITANAMERICA2,
    alt: "CAPTAIN AMERICA 2",
    name: "CAPTAIN AMERICA 2",
    fee: 3,
  },
  {
    id: nanoid(),
    category: "SuperHero",
    src: IMG.CAPITANAMERICA3,
    alt: "CAPTAIN AMERICA 3",
    name: "CAPTAIN AMERICA 3",
    fee: 3,
  },
  {
    id: nanoid(),
    category: "SuperHero",
    src: IMG.CAPITANAMARVEL,
    alt: "CAPTAIN MARVEL",
    name: "CAPTAIN MARVEL",
    fee: 3,
  },
  {
    id: nanoid(),
    category: "SuperHero",
    src: IMG.CAPTAINAMERICA1STAVENGER,
    alt: "CAPTAIN AMERICA 1ST AVENGER",
    name: "CAPTAIN AMERICA 1ST AVENGER",
    fee: 3,
  },
  {
    id: nanoid(),
    category: "SuperHero",
    src: IMG.CAPTAINENDGAMEV2,
    alt: "CAPTAIN ENDGAME V2",
    name: "CAPTAIN ENDGAME V2",
    fee: 3,
  },
  {
    id: nanoid(),
    category: "SuperHero",
    src: IMG.CAPTAINENDGAME,
    alt: "CAPTAIN ENDGAME",
    name: "CAPTAIN ENDGAME",
    fee: 3,
  },
  {
    id: nanoid(),
    category: "SuperHero",
    src: IMG.CAPTAIN1,
    alt: "CAPTAIN 1",
    name: "CAPTAIN 1",
    fee: 3,
  },
  {
    id: nanoid(),
    category: "SuperHero",
    src: IMG.CasadepapelDalírun,
    alt: "Casa de papel Dalírun",
    name: "Casa de papel Dalírun",
    fee: 3,
  },
  {
    id: nanoid(),
    category: "SuperHero",
    src: IMG.CasadepapelgrupoCartoon,
    alt: "Casa de papel group Cartoon",
    name: "Casa de papel group Cartoon",
    fee: 3,
  },
  {
    id: nanoid(),
    category: "SuperHero",
    src: IMG.casadepapel,
    alt: "casa de papel",
    name: "casa de papel",
    fee: 3,
  },
  {
    id: nanoid(),
    category: "SuperHero",
    src: IMG.CHEWBACCA,
    alt: "CHEWBACCA",
    name: "CHEWBACCA",
    fee: 3,
  },
  {
    id: nanoid(),
    category: "SuperHero",
    src: IMG.chubaca,
    alt: "chubaca",
    name: "chubaca",
    fee: 3,
  },
  {
    id: nanoid(),
    category: "SuperHero",
    src: IMG.DAENERYS1,
    alt: "DAENERYS 1",
    name: "DAENERYS 1",
    fee: 3,
  },
  {
    id: nanoid(),
    category: "SuperHero",
    src: IMG.DAERAVILFUNKOVECTOR,
    alt: "DAREDEVIL",
    name: "DAREDEVIL",
    fee: 3,
  },
  {
    id: nanoid(),
    category: "SuperHero",
    src: IMG.deadtina,
    alt: "dead tina",
    name: "dead tina",
    fee: 3,
  },
  {
    id: nanoid(),
    category: "SuperHero",
    src: IMG.deadpool01,
    alt: "deadpool 1",
    name: "deadpool 1",
    fee: 3,
  },
  {
    id: nanoid(),
    category: "SuperHero",
    src: IMG.DeadpoolMercenary,
    alt: "Deadpool Mercenary",
    name: "Deadpool Mercenary",
    fee: 3,
  },
  {
    id: nanoid(),
    category: "SuperHero",
    src: IMG.DeadpoolTacos,
    alt: "Deadpool Tacos",
    name: "Deadpool Tacos",
    fee: 3,
  },
  {
    id: nanoid(),
    category: "SuperHero",
    src: IMG.DEADPOOL,
    alt: "DEADPOOL",
    name: "DEADPOOL",
    fee: 3,
  },
  {
    id: nanoid(),
    category: "SuperHero",
    src: IMG.Droids,
    alt: "Droids",
    name: "Droids",
    fee: 3,
  },
  {
    id: nanoid(),
    category: "SuperHero",
    src: IMG.Dumbo2,
    alt: "Dumbo 2",
    name: "Dumbo 2",
    fee: 3,
  },
  {
    id: nanoid(),
    category: "SuperHero",
    src: IMG.FLINTSTONES,
    alt: "FLINTSTONES",
    name: "FLINTSTONES",
    fee: 3,
  },
  {
    id: nanoid(),
    category: "SuperHero",
    src: IMG.FLYINGDRAGON,
    alt: "FLYING DRAGON",
    name: "FLYING DRAGON",
    fee: 3,
  },
  {
    id: nanoid(),
    category: "SuperHero",
    src: IMG.FORTNITE,
    alt: "FORTNITE",
    name: "FORTNITE",
    fee: 3,
  },
  {
    id: nanoid(),
    category: "SuperHero",
    src: IMG.FreddyvsJason,
    alt: "Freddy vs Jason",
    name: "Freddy vs Jason",
    fee: 3,
  },
  {
    id: nanoid(),
    category: "SuperHero",
    src: IMG.Freddy,
    alt: "Freddy",
    name: "Freddy",
    fee: 3,
  },
  {
    id: nanoid(),
    category: "SuperHero",
    src: IMG.FUNKOIT,
    alt: "IT",
    name: "IT",
    fee: 3,
  },
  {
    id: nanoid(),
    category: "SuperHero",
    src: IMG.funkovegeta,
    alt: "vegeta",
    name: "vegeta",
    fee: 3,
  },
  {
    id: nanoid(),
    category: "SuperHero",
    src: IMG.GHOSTBUSTERS4,
    alt: "GHOSTBUSTERS 4",
    name: "GHOSTBUSTERS 4",
    fee: 3,
  },
  {
    id: nanoid(),
    category: "SuperHero",
    src: IMG.GHOSTBUSTERS,
    alt: "GHOSTBUSTERS",
    name: "GHOSTBUSTERS",
    fee: 3,
  },
  {
    id: nanoid(),
    category: "SuperHero",
    src: IMG.GROOT2,
    alt: "GROOT 2",
    name: "GROOT 2",
    fee: 3,
  },
  {
    id: nanoid(),
    category: "SuperHero",
    src: IMG.GROOT,
    alt: "GROOT",
    name: "GROOT",
    fee: 3,
  },
  {
    id: nanoid(),
    category: "SuperHero",
    src: IMG.HarleyQueen,
    alt: "Harley Queen",
    name: "Harley Queen",
    fee: 3,
  },
  {
    id: nanoid(),
    category: "SuperHero",
    src: IMG.HarleyQueenB,
    alt: "Harley Queen B",
    name: "Harley Queen B",
    fee: 3,
  },
  {
    id: nanoid(),
    category: "SuperHero",
    src: IMG.HARRYPOTTER2,
    alt: "HARRYPOTTER 2",
    name: "HARRYPOTTER 2",
    fee: 3,
  },
  {
    id: nanoid(),
    category: "SuperHero",
    src: IMG.HARRYPOTTER1,
    alt: "HARRYPOTTER 1",
    name: "HARRYPOTTER 1",
    fee: 3,
  },
  {
    id: nanoid(),
    category: "SuperHero",
    src: IMG.HEISENBERG,
    alt: "HEISENBERG",
    name: "HEISENBERG",
    fee: 3,
  },
  {
    id: nanoid(),
    category: "SuperHero",
    src: IMG.HERMIONE,
    alt: "HERMIONE",
    name: "HERMIONE",
    fee: 3,
  },
  {
    id: nanoid(),
    category: "SuperHero",
    src: IMG.ENDGAMEV2,
    alt: "ENDGAME V2",
    name: "ENDGAME V2",
    fee: 3,
  },
  {
    id: nanoid(),
    category: "SuperHero",
    src: IMG.ENDGAME,
    alt: "ENDGAME",
    name: "ENDGAME",
    fee: 3,
  },
  {
    id: nanoid(),
    category: "SuperHero",
    src: IMG.HULK,
    alt: "HULK",
    name: "HULK",
    fee: 3,
  },
  {
    id: nanoid(),
    category: "SuperHero",
    src: IMG.IRONSPIDER,
    alt: "IRON SPIDER",
    name: "IRON SPIDER",
    fee: 3,
  },
  {
    id: nanoid(),
    category: "SuperHero",
    src: IMG.IRONMANENDGAME,
    alt: "IRONMAN ENDGAME",
    name: "IRONMAN ENDGAME",
    fee: 3,
  },
  {
    id: nanoid(),
    category: "SuperHero",
    src: IMG.It,
    alt: "It 2",
    name: "It 2",
    fee: 3,
  },
  {
    id: nanoid(),
    category: "SuperHero",
    src: IMG.JIMIHENDRIX,
    alt: "JIMI HENDRIX",
    name: "JIMI HENDRIX",
    fee: 3,
  },
  {
    id: nanoid(),
    category: "SuperHero",
    src: IMG.JOKER,
    alt: "JOKER",
    name: "JOKER",
    fee: 3,
  },
  {
    id: nanoid(),
    category: "SuperHero",
    src: IMG.JURASICPOP,
    alt: "JURASIC POP",
    name: "JURASIC POP",
    fee: 3,
  },
  {
    id: nanoid(),
    category: "SuperHero",
    src: IMG.JURASIC2,
    alt: "JURASIC 2",
    name: "JURASIC 2",
    fee: 3,
  },
  {
    id: nanoid(),
    category: "SuperHero",
    src: IMG.kissfunko,
    alt: "kiss",
    name: "kiss",
    fee: 3,
  },
  {
    id: nanoid(),
    category: "SuperHero",
    src: IMG.LOKISARMY,
    alt: "LOKIS ARMY",
    name: "LOKIS ARMY",
    fee: 3,
  },
  {
    id: nanoid(),
    category: "SuperHero",
    src: IMG.MARTYSKATEBOARD,
    alt: "MARTY SKATEBOARD",
    name: "MARTY SKATEBOARD",
    fee: 3,
  },
  {
    id: nanoid(),
    category: "SuperHero",
    src: IMG.MARTY,
    alt: "MARTY",
    name: "MARTY",
    fee: 3,
  },
  {
    id: nanoid(),
    category: "SuperHero",
    src: IMG.MEGAMANFUNKO,
    alt: "MEGA MAN",
    name: "MEGA MAN",
    fee: 3,
  },
  {
    id: nanoid(),
    category: "SuperHero",
    src: IMG.NIGHTKING2,
    alt: "NIGHT KING 2",
    name: "NIGHT KING 2",
    fee: 3,
  },
  {
    id: nanoid(),
    category: "SuperHero",
    src: IMG.NIGHTKING3,
    alt: "NIGHT KING 3",
    name: "NIGHT KING 3",
    fee: 3,
  },
  {
    id: nanoid(),
    category: "SuperHero",
    src: IMG.NIGHTKING,
    alt: "NIGHT KING",
    name: "NIGHT KING",
    fee: 3,
  },
  {
    id: nanoid(),
    category: "SuperHero",
    src: IMG.PREDATOR,
    alt: "PREDATOR",
    name: "PREDATOR",
    fee: 3,
  },
  {
    id: nanoid(),
    category: "SuperHero",
    src: IMG.REBELLIONEMPIRE,
    alt: "REBELLION EMPIRE",
    name: "REBELLION EMPIRE",
    fee: 3,
  },
  {
    id: nanoid(),
    category: "SuperHero",
    src: IMG.ROCKSTEADY,
    alt: "ROCKSTEADY",
    name: "ROCKSTEADY",
    fee: 3,
  },
  {
    id: nanoid(),
    category: "SuperHero",
    src: IMG.RONINENDGAME,
    alt: "RONIN ENDGAME",
    name: "RONIN ENDGAME",
    fee: 3,
  },
  {
    id: nanoid(),
    category: "SuperHero",
    src: IMG.ScartTerry,
    alt: "Scary Terry",
    name: "Scary Terry",
    fee: 3,
  },
  {
    id: nanoid(),
    category: "SuperHero",
    src: IMG.SIRENITA,
    alt: "SIREN",
    name: "SIREN",
    fee: 3,
  },
  {
    id: nanoid(),
    category: "SuperHero",
    src: IMG.SKELETOR2,
    alt: "SKELETOR 2",
    name: "SKELETOR 2",
    fee: 3,
  },
  {
    id: nanoid(),
    category: "SuperHero",
    src: IMG.SKELETORCONQUERGRAYSKULL,
    alt: "SKELETOR CONQUER GRAYSKULL",
    name: "SKELETOR CONQUER GRAYSKULL",
    fee: 3,
  },
  {
    id: nanoid(),
    category: "SuperHero",
    src: IMG.SONIC,
    alt: "SONIC",
    name: "SONIC",
    fee: 3,
  },
  {
    id: nanoid(),
    category: "SuperHero",
    src: IMG.SPIDERMAN2,
    alt: "SPIDERMAN 2",
    name: "SPIDERMAN 2",
    fee: 3,
  },
  {
    id: nanoid(),
    category: "SuperHero",
    src: IMG.SPIDERMAN,
    alt: "SPIDERMAN",
    name: "SPIDERMAN",
    fee: 3,
  },
  {
    id: nanoid(),
    category: "SuperHero",
    src: IMG.STANLEECOMPL,
    alt: "STAN LEE",
    name: "STAN LEE",
    fee: 3,
  },
  {
    id: nanoid(),
    category: "SuperHero",
    src: IMG.STITCH,
    alt: "STITCH",
    name: "STITCH",
    fee: 3,
  },
  {
    id: nanoid(),
    category: "SuperHero",
    src: IMG.STORMTROOPER,
    alt: "STORMTROOPER",
    name: "STORMTROOPER",
    fee: 3,
  },
  {
    id: nanoid(),
    category: "SuperHero",
    src: IMG.SUPERMAN,
    alt: "SUPERMAN",
    name: "SUPERMAN",
    fee: 3,
  },
  {
    id: nanoid(),
    category: "SuperHero",
    src: IMG.TARGARYEN,
    alt: "TARGARYEN",
    name: "TARGARYEN",
    fee: 3,
  },
  {
    id: nanoid(),
    category: "SuperHero",
    src: IMG.THANOSENDGAMEV2,
    alt: "THANOS ENDGAME V2",
    name: "THANOS ENDGAME V2",
    fee: 3,
  },
  {
    id: nanoid(),
    category: "SuperHero",
    src: IMG.THANOSENDGAME,
    alt: "THANOS ENDGAME",
    name: "THANOS ENDGAME",
    fee: 3,
  },
  {
    id: nanoid(),
    category: "SuperHero",
    src: IMG.THANOS,
    alt: "THANOS",
    name: "THANOS",
    fee: 3,
  },
  {
    id: nanoid(),
    category: "SuperHero",
    src: IMG.TheJoker,
    alt: "The Joker",
    name: "The Joker",
    fee: 3,
  },
  {
    id: nanoid(),
    category: "SuperHero",
    src: IMG.THOR4,
    alt: "THOR 4",
    name: "THOR 4",
    fee: 3,
  },
  {
    id: nanoid(),
    category: "SuperHero",
    src: IMG.THORENDGAME,
    alt: "THOR ENDGAME",
    name: "THOR ENDGAME",
    fee: 3,
  },
  {
    id: nanoid(),
    category: "SuperHero",
    src: IMG.thor,
    alt: "thor",
    name: "thor",
    fee: 3,
  },
  {
    id: nanoid(),
    category: "SuperHero",
    src: IMG.TMNT2,
    alt: "TMNT 2",
    name: "TMNT 2",
    fee: 3,
  },
  {
    id: nanoid(),
    category: "SuperHero",
    src: IMG.Turtles,
    alt: "Turtles",
    name: "Turtles",
    fee: 3,
  },
  {
    id: nanoid(),
    category: "SuperHero",
    src: IMG.VADERKENOBI,
    alt: "VADER KENOBI",
    name: "VADER KENOBI",
    fee: 3,
  },
  {
    id: nanoid(),
    category: "SuperHero",
    src: IMG.VENOM2,
    alt: "VENOM 2",
    name: "VENOM 2",
    fee: 3,
  },
  {
    id: nanoid(),
    category: "SuperHero",
    src: IMG.VENOM1,
    alt: "VENOM 1",
    name: "VENOM 1",
    fee: 3,
  },
  {
    id: nanoid(),
    category: "SuperHero",
    src: IMG.WONDERWOMANRETRO,
    alt: "WONDER WOMAN RETRO",
    name: "WONDER WOMAN RETRO",
    fee: 3,
  },
  {
    id: nanoid(),
    category: "SuperHero",
    src: IMG.wonderwomanfunko,
    alt: "wonder woman",
    name: "wonder woman",
    fee: 3,
  },
];
export default Photos;

// {
//   id: nanoid(),
//   category: "",
//   src: IMG.stufffffff,
//   alt: "eraseThis",
//   name: "eraseThis",
//   fee: 3,
// },
