const IMG = {
  //charicatureGraphics ---------------------------------------------

  AstronautIceCream: require("../resources/graphics/charicatureGraphics/Astronaut Ice Cream.png"),
  BarberSkater: require("../resources/graphics/charicatureGraphics/Barber Skater.png"),
  BasketBallBombers: require("../resources/graphics/charicatureGraphics/Basketball Bombers.png"),
  Bomber: require("../resources/graphics/charicatureGraphics/Bomber.png"),
  BoomboxRobot: require("../resources/graphics/charicatureGraphics/Boombox Robot.png"),
  BoxingChampion: require("../resources/graphics/charicatureGraphics/Boxing Champion.png"),
  BrickGamers: require("../resources/graphics/charicatureGraphics/Brick Gamers.png"),
  BrooklynBaseball: require("../resources/graphics/charicatureGraphics/Brooklyn Baseball.png"),
  BurgerBastard: require("../resources/graphics/charicatureGraphics/Burger Bastard.png"),
  BurgerScooter: require("../resources/graphics/charicatureGraphics/Burger Scooter.png"),
  CaferacerHelmet: require("../resources/graphics/charicatureGraphics/Caferacer Helmet.png"),
  CashRules: require("../resources/graphics/charicatureGraphics/Cash Rules.png"),
  ChainsawKiller: require("../resources/graphics/charicatureGraphics/Chainsaw KIller.png"),
  ChocolateSquad: require("../resources/graphics/charicatureGraphics/Chocolate Squad.png"),
  CigaretteKiller: require("../resources/graphics/charicatureGraphics/Cigarette Killer.png"),
  ClassicCameraman: require("../resources/graphics/charicatureGraphics/Classic Cameraman.png"),
  Diver: require("../resources/graphics/charicatureGraphics/Diver.png"),
  DonutSkater: require("../resources/graphics/charicatureGraphics/Donut Skater.png"),
  DoubleStickMan: require("../resources/graphics/charicatureGraphics/Double Stick Man.png"),
  Fighter: require("../resources/graphics/charicatureGraphics/Fighter.png"),
  FootballKing: require("../resources/graphics/charicatureGraphics/Football King.png"),
  FootballPlayer: require("../resources/graphics/charicatureGraphics/Football Player.png"),
  FrankRace: require("../resources/graphics/charicatureGraphics/Frank Race.png"),
  GameKid: require("../resources/graphics/charicatureGraphics/Game Kid.png"),
  GameMachine: require("../resources/graphics/charicatureGraphics/Game Machine.png"),
  GameOn1: require("../resources/graphics/charicatureGraphics/Game On 1.png"),
  GameOn2: require("../resources/graphics/charicatureGraphics/Game On 2.png"),
  GamersKiller: require("../resources/graphics/charicatureGraphics/Gamers Killer.png"),
  GiftFromOuterSpace: require("../resources/graphics/charicatureGraphics/Gift From Outer Space.png"),
  Golfer: require("../resources/graphics/charicatureGraphics/Golfer.png"),
  GramophoneHead: require("../resources/graphics/charicatureGraphics/Gramophone Head.png"),
  GrenadeBrain: require("../resources/graphics/charicatureGraphics/Grenade Brain.png"),
  GrenadeHeart: require("../resources/graphics/charicatureGraphics/Grenade Heart.png"),
  GrenadeRibcage: require("../resources/graphics/charicatureGraphics/Grenade Ribcage.png"),
  Grenade: require("../resources/graphics/charicatureGraphics/Grenade.png"),
  HeartToKill: require("../resources/graphics/charicatureGraphics/Heart To Kill.png"),
  Hello: require("../resources/graphics/charicatureGraphics/Hello.png"),
  ILikeDonut: require("../resources/graphics/charicatureGraphics/I Like Donut.png"),
  ILoveBurger: require("../resources/graphics/charicatureGraphics/I Love Burger.png"),
  IceCreamNinja: require("../resources/graphics/charicatureGraphics/Ice Cream Ninja.png"),
  IceCreamTruck: require("../resources/graphics/charicatureGraphics/Ice Cream Truck.png"),
  KillerMinibike: require("../resources/graphics/charicatureGraphics/Killer Minibike.png"),
  KillerSkater: require("../resources/graphics/charicatureGraphics/Killer Skater.png"),
  LetsPaint: require("../resources/graphics/charicatureGraphics/Let's Paint.png"),
  LetsPlay: require("../resources/graphics/charicatureGraphics/Let's Play.png"),
  LetsPlay2: require("../resources/graphics/charicatureGraphics/Let's Play 2.png"),
  LightBoy: require("../resources/graphics/charicatureGraphics/Light Boy.png"),
  MicrophoneKing: require("../resources/graphics/charicatureGraphics/Microphone King.png"),
  MoneyTakers: require("../resources/graphics/charicatureGraphics/Money Takers.png"),
  Money: require("../resources/graphics/charicatureGraphics/Money.png"),
  MrCoffee: require("../resources/graphics/charicatureGraphics/Mr Coffee.png"),
  MummyRace: require("../resources/graphics/charicatureGraphics/Mummy Race.png"),
  PeaceChar: require("../resources/graphics/charicatureGraphics/Peace.png"),
  Pilot: require("../resources/graphics/charicatureGraphics/Pilot.png"),
  PizzaBeard: require("../resources/graphics/charicatureGraphics/Pizza Beard.png"),
  PizzaGangster: require("../resources/graphics/charicatureGraphics/Pizza Gangster.png"),
  PizzaSkater: require("../resources/graphics/charicatureGraphics/Pizza Skater.png"),
  PlayerHead1: require("../resources/graphics/charicatureGraphics/Player Head 1.png"),
  PlayerHead2: require("../resources/graphics/charicatureGraphics/Player Head 2.png"),
  PlayerSkater: require("../resources/graphics/charicatureGraphics/Player Skater.png"),
  Polaroid: require("../resources/graphics/charicatureGraphics/Polaroid.png"),
  Racer: require("../resources/graphics/charicatureGraphics/Racer.png"),
  RamenStyle: require("../resources/graphics/charicatureGraphics/Ramen Style.png"),
  RobotBoombox: require("../resources/graphics/charicatureGraphics/Robot Boombox.png"),
  RubixKiller: require("../resources/graphics/charicatureGraphics/Rubix Killer.png"),
  Sailor: require("../resources/graphics/charicatureGraphics/Sailor.png"),
  SamuraiRider: require("../resources/graphics/charicatureGraphics/Samurai Rider.png"),
  Samurai: require("../resources/graphics/charicatureGraphics/Samurai.png"),
  Savage: require("../resources/graphics/charicatureGraphics/Savage.png"),
  ScooterSkater: require("../resources/graphics/charicatureGraphics/Scooter Skater.png"),
  Shooter: require("../resources/graphics/charicatureGraphics/Shooter.png"),
  SkateBastard: require("../resources/graphics/charicatureGraphics/Skate Bastard.png"),
  SkaterBomb: require("../resources/graphics/charicatureGraphics/Skater Bomb.png"),
  Skatespace: require("../resources/graphics/charicatureGraphics/Skatespace.png"),
  Soldier: require("../resources/graphics/charicatureGraphics/Soldier.png"),
  SpaceBike: require("../resources/graphics/charicatureGraphics/Space Bike.png"),
  SpaceJump: require("../resources/graphics/charicatureGraphics/Space Jump.png"),
  SpaceRacer: require("../resources/graphics/charicatureGraphics/Space Racer.png"),
  SpaceSlider: require("../resources/graphics/charicatureGraphics/Space Slider.png"),
  StayFresh: require("../resources/graphics/charicatureGraphics/Stay Fresh.png"),
  SteampunkHeart: require("../resources/graphics/charicatureGraphics/Steampunk Heart.png"),
  SteampunkOwl: require("../resources/graphics/charicatureGraphics/Steampunk Owl.png"),
  SteampunkRibcage: require("../resources/graphics/charicatureGraphics/Steampunk Ribcage.png"),
  SteampunkTRex: require("../resources/graphics/charicatureGraphics/Steampunk T Rex.png"),
  StreetBasketball: require("../resources/graphics/charicatureGraphics/Street Basketball.png"),
  StreetBeetle: require("../resources/graphics/charicatureGraphics/Street Beetle.png"),
  StreetBomber: require("../resources/graphics/charicatureGraphics/Street Bomber.png"),
  StreetGamers: require("../resources/graphics/charicatureGraphics/Street Gamers.png"),
  StreetKing: require("../resources/graphics/charicatureGraphics/Street King.png"),
  StreetSoccer: require("../resources/graphics/charicatureGraphics/Street Soccer.png"),
  Surprise: require("../resources/graphics/charicatureGraphics/Surprise.png"),
  Taco: require("../resources/graphics/charicatureGraphics/Taco.png"),
  ToasterMonster: require("../resources/graphics/charicatureGraphics/Toaster Monster.png"),
  TrainKiller: require("../resources/graphics/charicatureGraphics/Train Killer.png"),
  Vandalism: require("../resources/graphics/charicatureGraphics/Vandalism.png"),
  Viking: require("../resources/graphics/charicatureGraphics/Viking.png"),
  VintageRobot: require("../resources/graphics/charicatureGraphics/Vintage Robot.png"),
  WarTank: require("../resources/graphics/charicatureGraphics/War Tank.png"),
  YourTimeWillCome: require("../resources/graphics/charicatureGraphics/Your Time Will Come.png"),
  ZombieCassette: require("../resources/graphics/charicatureGraphics/Zombie Cassette.png"),

  //pocketGraphics ---------------------------------------------

  Abduction: require("../resources/graphics/pocketGraphics/alien abduction pocketSource.png"),
  AngryWaves: require("../resources/graphics/pocketGraphics/Angry waves pocket.png"),
  Aquarium: require("../resources/graphics/pocketGraphics/aquarium pocket.png"),
  BeAwesome: require("../resources/graphics/pocketGraphics/be awesome pocketSource.png"),
  Cactus: require("../resources/graphics/pocketGraphics/cactus pocket.png"),
  CatSkeleton: require("../resources/graphics/pocketGraphics/cat skeleton pocketSource.png"),
  ChildMoon: require("../resources/graphics/pocketGraphics/Child on moon pocket.png"),
  CourageDog: require("../resources/graphics/pocketGraphics/courage dog pocketSource.png"),
  CuteCat: require("../resources/graphics/pocketGraphics/cute cat pocket.png"),
  Dollar: require("../resources/graphics/pocketGraphics/Dollar pocketSource.png"),
  FallingCat: require("../resources/graphics/pocketGraphics/falling cat pocketSource.png"),
  Fish: require("../resources/graphics/pocketGraphics/fish pocketSource.png"),
  Ghost: require("../resources/graphics/pocketGraphics/Ghost pocket.png"),
  GoldenCoins: require("../resources/graphics/pocketGraphics/Golden coins pocket.png"),
  Heart: require("../resources/graphics/pocketGraphics/Heart pocket.png"),
  Hotdog: require("../resources/graphics/pocketGraphics/Hotdog-pocket.png"),
  Husky: require("../resources/graphics/pocketGraphics/husky pocket.png"),
  Icecreampocket: require("../resources/graphics/pocketGraphics/icecream pocket.png"),
  Knife: require("../resources/graphics/pocketGraphics/knife pocket.png"),
  LoveAtFirstBite: require("../resources/graphics/pocketGraphics/Love at first bite.png"),
  Minion: require("../resources/graphics/pocketGraphics/minion pocketSource.png"),
  MonkeyButt: require("../resources/graphics/pocketGraphics/monkey butt pocketSource.png"),
  Octopus: require("../resources/graphics/pocketGraphics/Octopus pocket.png"),
  Palm: require("../resources/graphics/pocketGraphics/palm pocketSource.png"),
  Panda: require("../resources/graphics/pocketGraphics/Panda pocketSource.png"),
  PinupGirl: require("../resources/graphics/pocketGraphics/Pin up girl pocket.png"),
  PinkPanther: require("../resources/graphics/pocketGraphics/pink panter pocketSource.png"),
  Popcorn: require("../resources/graphics/pocketGraphics/Popcorn pocket.png"),
  Pug: require("../resources/graphics/pocketGraphics/pug pocketSource.png"),
  SeaStar: require("../resources/graphics/pocketGraphics/Seastarspocket.png"),
  Sun: require("../resources/graphics/pocketGraphics/Sun umbrella pocket.png"),
  Swimming: require("../resources/graphics/pocketGraphics/Swimming pocketSource.png"),
  TropicalFruit: require("../resources/graphics/pocketGraphics/Tropical fruits pocket.png"),
  WateringFlowers: require("../resources/graphics/pocketGraphics/Watering flowers.png"),
  ZombieHands: require("../resources/graphics/pocketGraphics/Zombie hands pocket.png"),

  // popArtGraphics ---------------------------------------------

  AlbertKisstein: require("../resources/graphics/PopArtGraphics/ALBERT KISSTEIN low.png"),
  AmericanPsycho2: require("../resources/graphics/PopArtGraphics/AMERICAN PSYCHO 2 low.png"),
  AmericanPsycho: require("../resources/graphics/PopArtGraphics/AMERICAN PSYCHO low.png"),
  BenjaminDranklin: require("../resources/graphics/PopArtGraphics/Benjamin Dranklin low.png"),
  CharimanMeow: require("../resources/graphics/PopArtGraphics/CHAIRMAN MEOW low.png"),
  Chef: require("../resources/graphics/PopArtGraphics/CHEF low.png"),
  Covfefe: require("../resources/graphics/PopArtGraphics/COVFEFE.png"),
  Dope: require("../resources/graphics/PopArtGraphics/DOPE.png"),
  Dream: require("../resources/graphics/PopArtGraphics/DREAM low.png"),
  GotMLK: require("../resources/graphics/PopArtGraphics/GOT MLK low.png"),
  Heilstein: require("../resources/graphics/PopArtGraphics/HEILSTEIN low.png"),
  HoHoHoChiMinh: require("../resources/graphics/PopArtGraphics/ho ho ho chi minh.png"),
  ICantBreathe: require("../resources/graphics/PopArtGraphics/I CANT BREATHE.png"),
  JusticeForGeorgeFloyd: require("../resources/graphics/PopArtGraphics/justice for george floyd low.png"),
  LincolnUnknown: require("../resources/graphics/PopArtGraphics/lincoln unknown low.png"),
  MakeAmericaGreyAgain: require("../resources/graphics/PopArtGraphics/MAKE AMERICA GREY AGAIN.png"),
  MeowTseTung: require("../resources/graphics/PopArtGraphics/Meow Tse Tung.png"),
  Merica: require("../resources/graphics/PopArtGraphics/MERICA low.png"),
  MericaTrump: require("../resources/graphics/PopArtGraphics/MERICA TRUMP low.png"),
  NoRacism: require("../resources/graphics/PopArtGraphics/NO RACISM.png"),
  Putintin: require("../resources/graphics/PopArtGraphics/PUTINTIN.png"),
  RocketBoy: require("../resources/graphics/PopArtGraphics/ROCKETBOY low.png"),
  RocketMan: require("../resources/graphics/PopArtGraphics/ROCKETMAN low.png"),
  StraigtOuttaPyongYang: require("../resources/graphics/PopArtGraphics/STRAIGHT OUTTA PYONGYANG.png"),
  SylvesterStalin: require("../resources/graphics/PopArtGraphics/SYLVESTER STALIN.png"),
  TheFuhrer: require("../resources/graphics/PopArtGraphics/THE FUHRER.png"),
  Trump: require("../resources/graphics/PopArtGraphics/TRUMP low.png"),
  UnderControl: require("../resources/graphics/PopArtGraphics/UNDER CONTROL.png"),
  VivaLaEvolucion: require("../resources/graphics/PopArtGraphics/viva la evolucion low.png"),
  WeCanDoIt: require("../resources/graphics/PopArtGraphics/WE CAN DO IT.png"),

  // presidentGraphics ---------------------------------------------

  Franklin: require("../resources/graphics/presidentGraphics/franklin.png"),
  Grant: require("../resources/graphics/presidentGraphics/grant.png"),
  Hamilton: require("../resources/graphics/presidentGraphics/hamilton.png"),
  Jackson: require("../resources/graphics/presidentGraphics/jackson.png"),
  Jefferson: require("../resources/graphics/presidentGraphics/jefferson.png"),
  Lincoln: require("../resources/graphics/presidentGraphics/lincoln.png"),
  Washington: require("../resources/graphics/presidentGraphics/washington.png"),

  // randomGraphics ---------------------------------------------

  AnchorBones: require("../resources/graphics/randomGraphics/Anchor Bones-02.png"),
  Anchor: require("../resources/graphics/randomGraphics/Anchor.png"),
  Astrocode: require("../resources/graphics/randomGraphics/Astrocode.png"),
  Awesome: require("../resources/graphics/randomGraphics/Awesome.png"),
  BananaSkateboard: require("../resources/graphics/randomGraphics/Banana Skateboard.png"),
  BaseballPlayer: require("../resources/graphics/randomGraphics/Baseball Player.png"),
  BasketballPlayer: require("../resources/graphics/randomGraphics/Basketball Player.png"),
  Beetle: require("../resources/graphics/randomGraphics/Beetle.png"),
  BicycleSkull: require("../resources/graphics/randomGraphics/Bicycle Skull.png"),
  BirdsBeard: require("../resources/graphics/randomGraphics/Birds Beard.png"),
  BrainGloves: require("../resources/graphics/randomGraphics/Brain Gloves.png"),
  BreakingNoise: require("../resources/graphics/randomGraphics/Breaking Noise.png"),
  Burger: require("../resources/graphics/randomGraphics/Burger.png"),
  Chainsaw: require("../resources/graphics/randomGraphics/Chainsaw.png"),
  CheSmiley: require("../resources/graphics/randomGraphics/Che Smiley.png"),
  CoffeeTree: require("../resources/graphics/randomGraphics/Coffee Tree.png"),
  Coffee: require("../resources/graphics/randomGraphics/Coffee.png"),
  Crab: require("../resources/graphics/randomGraphics/Crab.png"),
  CrystalLake: require("../resources/graphics/randomGraphics/Crystal Lake.png"),
  DeadSchool: require("../resources/graphics/randomGraphics/Dead  School.png"),
  DeadSea: require("../resources/graphics/randomGraphics/Dead Sea.png"),
  DeathCity: require("../resources/graphics/randomGraphics/Death City.png"),
  Deer2: require("../resources/graphics/randomGraphics/Deer 2.png"),
  Deer3: require("../resources/graphics/randomGraphics/Deer 3.png"),
  DeerButterfly: require("../resources/graphics/randomGraphics/Deer Butterfly.png"),
  Deer: require("../resources/graphics/randomGraphics/Deer.png"),
  DonutBarbell: require("../resources/graphics/randomGraphics/Donut Barbell.png"),
  Eagle: require("../resources/graphics/randomGraphics/Eagle.png"),
  ElectricAnchor: require("../resources/graphics/randomGraphics/Electric Anchor.png"),
  ElectricBalance: require("../resources/graphics/randomGraphics/Electric Balance.png"),
  ElectricBrain: require("../resources/graphics/randomGraphics/Electric Brain.png"),
  ElectricDeer: require("../resources/graphics/randomGraphics/Electric Deer.png"),
  ElectricSkull: require("../resources/graphics/randomGraphics/Electric Skull.png"),
  ElectricSmiley: require("../resources/graphics/randomGraphics/Electric Smiley.png"),
  ElectricalOwl: require("../resources/graphics/randomGraphics/Electrical Owl.png"),
  EnjoyYourLie: require("../resources/graphics/randomGraphics/Enjoy Your Lie.png"),
  FloatLikeButterflyStingLikeBee: require("../resources/graphics/randomGraphics/Float Like Butterfly Sting Like Bee.png"),
  FlourishVandalism: require("../resources/graphics/randomGraphics/Flourish Vandalism.png"),
  FlyingAstronaut: require("../resources/graphics/randomGraphics/Flying Astronaut.png"),
  FroggyNight: require("../resources/graphics/randomGraphics/Froggy Night.png"),
  GhostFaceBats: require("../resources/graphics/randomGraphics/Ghost Face Bats.png"),
  Godzilla: require("../resources/graphics/randomGraphics/Godzilla.png"),
  GoodIdea: require("../resources/graphics/randomGraphics/Good Idea.png"),
  GramophoneDonut: require("../resources/graphics/randomGraphics/Gramophone Donut.png"),
  GreenMonster: require("../resources/graphics/randomGraphics/Green Monster.png"),
  // eslint-disable-next-line
  Grenade: require("../resources/graphics/randomGraphics/Grenade.png"),
  HandOfRevolution: require("../resources/graphics/randomGraphics/Hand Of Revolution.png"),
  HandOfZombies: require("../resources/graphics/randomGraphics/Hand Of Zombies.png"),
  HeadphoneDonut: require("../resources/graphics/randomGraphics/Headphone Donut.png"),
  Hipster: require("../resources/graphics/randomGraphics/HIPSTER.png"),
  HomeHeart: require("../resources/graphics/randomGraphics/Home Heart.png"),
  Icecream: require("../resources/graphics/randomGraphics/Ice Cream.png"),
  JasonMoon: require("../resources/graphics/randomGraphics/Jason Moon.png"),
  Kaiju2: require("../resources/graphics/randomGraphics/Kaiju 2.png"),
  Kaiju: require("../resources/graphics/randomGraphics/Kaiju.png"),
  KnowYourRoots: require("../resources/graphics/randomGraphics/Know Your Roots.png"),
  Liberty: require("../resources/graphics/randomGraphics/Liberty.png"),
  LifeAndDeath: require("../resources/graphics/randomGraphics/Life And Death.png"),
  LOL: require("../resources/graphics/randomGraphics/LOL.png"),
  Milkyway: require("../resources/graphics/randomGraphics/Milky Way.png"),
  NatureOfCrime: require("../resources/graphics/randomGraphics/Nature of Crime.png"),
  Nerd: require("../resources/graphics/randomGraphics/NERD.png"),
  Peace: require("../resources/graphics/randomGraphics/Peace.png"),
  PizzaMoon: require("../resources/graphics/randomGraphics/Pizza Moon.png"),
  PizzaScratch: require("../resources/graphics/randomGraphics/Pizza Scratch.png"),
  PizzaUFO: require("../resources/graphics/randomGraphics/Pizza UFO.png"),
  Pizza: require("../resources/graphics/randomGraphics/Pizza.png"),
  Prismzza: require("../resources/graphics/randomGraphics/Prismzza.png"),
  ReaperScream: require("../resources/graphics/randomGraphics/Reaper Scream.png"),
  Recycling: require("../resources/graphics/randomGraphics/Recycling.png"),
  RhymeInPeace: require("../resources/graphics/randomGraphics/Rhyme In Peace.png"),
  RibcageBird: require("../resources/graphics/randomGraphics/Ribcage Bird.png"),
  Scooter: require("../resources/graphics/randomGraphics/Scooter.png"),
  SeaHorse: require("../resources/graphics/randomGraphics/Sea Horse.png"),
  SherlockHolmes: require("../resources/graphics/randomGraphics/Sherlock Holmes.png"),
  Skater: require("../resources/graphics/randomGraphics/Skater.png"),
  SkaterHook: require("../resources/graphics/randomGraphics/Skaterhook.png"),
  SkullNature: require("../resources/graphics/randomGraphics/Skull Nature.png"),
  SmileyMoon: require("../resources/graphics/randomGraphics/Smiley Moon.png"),
  Smiley: require("../resources/graphics/randomGraphics/Smiley.png"),
  SmokingKills: require("../resources/graphics/randomGraphics/Smoking Kills.png"),
  SoundCollector: require("../resources/graphics/randomGraphics/Sound Collector.png"),
  SoundOfRain: require("../resources/graphics/randomGraphics/Sound Of Rain.png"),
  StandAndBleed: require("../resources/graphics/randomGraphics/Stand And Bleed.png"),
  TheBridge: require("../resources/graphics/randomGraphics/The Bridge.png"),
  TheChronicle: require("../resources/graphics/randomGraphics/The Chronicle.png"),
  TheCrow: require("../resources/graphics/randomGraphics/The Crow.png"),
  TheMask: require("../resources/graphics/randomGraphics/The Mask.png"),
  Thunderbolt: require("../resources/graphics/randomGraphics/Thunderbolt.png"),
  TrainSong: require("../resources/graphics/randomGraphics/Train Song.png"),
  truthHurts: require("../resources/graphics/randomGraphics/Truth Hurts.png"),
  UFOInvasion: require("../resources/graphics/randomGraphics/UFO Invasion.png"),
  WarPeace: require("../resources/graphics/randomGraphics/War Peace.png"),
  WeaponFlag: require("../resources/graphics/randomGraphics/Weapon Flag.png"),
  WildBison: require("../resources/graphics/randomGraphics/Wild Bison.png"),
  WildLife: require("../resources/graphics/randomGraphics/Wild Life.png"),
  YinYangCats: require("../resources/graphics/randomGraphics/YinYang Cats.png"),
  ZebraBones: require("../resources/graphics/randomGraphics/Zebra Bones.png"),

  //BlackHistoryGraphics ---------------------------------------------

  BHM365Days: require("../resources/graphics/BlackHistoryGraphics/BLACK HISTORY MONT 365 DAYS.png"),
  BHMMalcolmX: require("../resources/graphics/BlackHistoryGraphics/BLACK HISTORY MONTH MALCOLM X.png"),
  BHMMap: require("../resources/graphics/BlackHistoryGraphics/BLACK HISTORY MONTH MAP.png"),
  BHMMLK: require("../resources/graphics/BlackHistoryGraphics/BLACK HISTORY MONTH MLK.png"),
  BHMPowerHand: require("../resources/graphics/BlackHistoryGraphics/BLACK HISTORY MONTH POWER HAND.png"),
  BHM: require("../resources/graphics/BlackHistoryGraphics/BLACK HISTORY MONTH.png"),
  BH: require("../resources/graphics/BlackHistoryGraphics/BLACK HISTORY.png"),
  BLMHand: require("../resources/graphics/BlackHistoryGraphics/BLACK LIVES MATTER HAND.png"),
  MartinLutherJunior: require("../resources/graphics/BlackHistoryGraphics/BLACK LIVES MATTER Martin Luther Junior.png"),
  BLMMLK: require("../resources/graphics/BlackHistoryGraphics/BLACK LIVES MATTER MLK.png"),
  BlackLivesMatter: require("../resources/graphics/BlackHistoryGraphics/BLACKLIVESMATTER.png"),
  DreamBH: require("../resources/graphics/BlackHistoryGraphics/DREAM.png"),
  EnoughIsEnough: require("../resources/graphics/BlackHistoryGraphics/ENOUGH IS ENOUGH.png"),
  FightForChange: require("../resources/graphics/BlackHistoryGraphics/FIGHT FOR CHANGE.png"),
  FrederickDouglass: require("../resources/graphics/BlackHistoryGraphics/FREDERICK DOUGLASS.png"),
  FreedomBH: require("../resources/graphics/BlackHistoryGraphics/FREEDOM.png"),
  JohnLewis: require("../resources/graphics/BlackHistoryGraphics/JOHN LEWIS.png"),
  EveryMonthBH: require("../resources/graphics/BlackHistoryGraphics/MAKE EVERY MONTH BLACK HISTORY MONTH.png"),
  MalcolmXBH: require("../resources/graphics/BlackHistoryGraphics/MALCOLM X BLACK HISTORY.png"),
  MLKBH: require("../resources/graphics/BlackHistoryGraphics/MARTIN LUTHER KING BLACK HISTORY.png"),
  Riot: require("../resources/graphics/BlackHistoryGraphics/RIOT.png"),
  // eslint-disable-next-line
  WeCanDoIt: require("../resources/graphics/BlackHistoryGraphics/WE CAN DO IT.png"),

  //CartoonGraphics ---------------------------------------------

  Cat1: require("../resources/graphics/CartoonGraphics/Cat 1.png"),
  Cat2: require("../resources/graphics/CartoonGraphics/Cat 2.png"),
  Cat3: require("../resources/graphics/CartoonGraphics/Cat 3.png"),
  Cat4: require("../resources/graphics/CartoonGraphics/Cat 4.png"),
  Cat5: require("../resources/graphics/CartoonGraphics/Cat 5.png"),
  Cat6: require("../resources/graphics/CartoonGraphics/Cat 6.png"),
  Cat7: require("../resources/graphics/CartoonGraphics/Cat 7.png"),
  Cat8: require("../resources/graphics/CartoonGraphics/Cat 8.png"),
  Cat9: require("../resources/graphics/CartoonGraphics/Cat 9.png"),
  Cat10: require("../resources/graphics/CartoonGraphics/Cat 10.png"),
  Cat11: require("../resources/graphics/CartoonGraphics/Cat 11.png"),
  Cat12: require("../resources/graphics/CartoonGraphics/Cat 12.png"),
  Cat13: require("../resources/graphics/CartoonGraphics/Cat 13.png"),
  Cat14: require("../resources/graphics/CartoonGraphics/Cat 14.png"),
  Cat15: require("../resources/graphics/CartoonGraphics/Cat 15.png"),
  Cat16: require("../resources/graphics/CartoonGraphics/Cat 16.png"),
  Cat17: require("../resources/graphics/CartoonGraphics/Cat 17.png"),
  Cat18: require("../resources/graphics/CartoonGraphics/Cat 18.png"),
  Cat19: require("../resources/graphics/CartoonGraphics/Cat 19.png"),
  Cat20: require("../resources/graphics/CartoonGraphics/Cat 20.png"),
  Cat21: require("../resources/graphics/CartoonGraphics/Cat 21.png"),
  Cat22: require("../resources/graphics/CartoonGraphics/Cat 22.png"),
  Cat23: require("../resources/graphics/CartoonGraphics/Cat 23.png"),
  Cat24: require("../resources/graphics/CartoonGraphics/Cat 24.png"),
  Cat25: require("../resources/graphics/CartoonGraphics/Cat 25.png"),
  Dog1: require("../resources/graphics/CartoonGraphics/Dog 1.png"),
  Dog2: require("../resources/graphics/CartoonGraphics/Dog 2.png"),
  Dog3: require("../resources/graphics/CartoonGraphics/Dog 3.png"),
  Dog4: require("../resources/graphics/CartoonGraphics/Dog 4.png"),
  Dog5: require("../resources/graphics/CartoonGraphics/Dog 5.png"),
  Dog6: require("../resources/graphics/CartoonGraphics/Dog 6.png"),
  Dog7: require("../resources/graphics/CartoonGraphics/Dog 7.png"),
  Dog8: require("../resources/graphics/CartoonGraphics/Dog 8.png"),
  Dog9: require("../resources/graphics/CartoonGraphics/Dog 9.png"),
  Dog10: require("../resources/graphics/CartoonGraphics/Dog 10.png"),
  Dog11: require("../resources/graphics/CartoonGraphics/Dog 11.png"),
  Dog12: require("../resources/graphics/CartoonGraphics/Dog 12.png"),
  Dog13: require("../resources/graphics/CartoonGraphics/Dog 13.png"),
  Dog14: require("../resources/graphics/CartoonGraphics/Dog 14.png"),
  Dog15: require("../resources/graphics/CartoonGraphics/Dog 15.png"),
  Dog16: require("../resources/graphics/CartoonGraphics/Dog 16.png"),
  Dog17: require("../resources/graphics/CartoonGraphics/Dog 17.png"),
  Dog18: require("../resources/graphics/CartoonGraphics/Dog 18.png"),
  Dog19: require("../resources/graphics/CartoonGraphics/Dog 19.png"),
  Dog20: require("../resources/graphics/CartoonGraphics/Dog 20.png"),
  Dog21: require("../resources/graphics/CartoonGraphics/Dog 21.png"),
  Dog22: require("../resources/graphics/CartoonGraphics/Dog 22.png"),
  Dog23: require("../resources/graphics/CartoonGraphics/Dog 23.png"),
  Dog24: require("../resources/graphics/CartoonGraphics/Dog 24.png"),
  Dog25: require("../resources/graphics/CartoonGraphics/Dog 25.png"),
  Dragon1: require("../resources/graphics/CartoonGraphics/Dragon 1.png"),
  Dragon2: require("../resources/graphics/CartoonGraphics/Dragon 2.png"),
  Dragon3: require("../resources/graphics/CartoonGraphics/Dragon 3.png"),
  Dragon4: require("../resources/graphics/CartoonGraphics/Dragon 4.png"),
  Dragon5: require("../resources/graphics/CartoonGraphics/Dragon 5.png"),
  Dragon6: require("../resources/graphics/CartoonGraphics/Dragon 6.png"),
  Dragon7: require("../resources/graphics/CartoonGraphics/Dragon 7.png"),
  Dragon8: require("../resources/graphics/CartoonGraphics/Dragon 8.png"),
  Dragon9: require("../resources/graphics/CartoonGraphics/Dragon 9.png"),
  Dragon10: require("../resources/graphics/CartoonGraphics/Dragon 10.png"),
  Dragon11: require("../resources/graphics/CartoonGraphics/Dragon 11.png"),
  Dragon12: require("../resources/graphics/CartoonGraphics/Dragon 12.png"),
  Dragon13: require("../resources/graphics/CartoonGraphics/Dragon 13.png"),
  Dragon14: require("../resources/graphics/CartoonGraphics/Dragon 14.png"),
  Dragon15: require("../resources/graphics/CartoonGraphics/Dragon 15.png"),
  Dragon16: require("../resources/graphics/CartoonGraphics/Dragon 16.png"),
  Dragon17: require("../resources/graphics/CartoonGraphics/Dragon 17.png"),
  Dragon18: require("../resources/graphics/CartoonGraphics/Dragon 18.png"),
  Dragon19: require("../resources/graphics/CartoonGraphics/Dragon 19.png"),
  Dragon20: require("../resources/graphics/CartoonGraphics/Dragon 20.png"),
  Dragon21: require("../resources/graphics/CartoonGraphics/Dragon 21.png"),
  Dragon22: require("../resources/graphics/CartoonGraphics/Dragon 22.png"),
  Dragon23: require("../resources/graphics/CartoonGraphics/Dragon 23.png"),
  Dragon24: require("../resources/graphics/CartoonGraphics/Dragon 24.png"),
  Dragon25: require("../resources/graphics/CartoonGraphics/Dragon 25.png"),
  Monster: require("../resources/graphics/CartoonGraphics/Monster.png"),
  Monster1: require("../resources/graphics/CartoonGraphics/Monster1.png"),
  Monster2: require("../resources/graphics/CartoonGraphics/Monster2.png"),
  Monster3: require("../resources/graphics/CartoonGraphics/Monster3.png"),
  Monster4: require("../resources/graphics/CartoonGraphics/Monster4.png"),
  Monster5: require("../resources/graphics/CartoonGraphics/Monster5.png"),
  Monster6: require("../resources/graphics/CartoonGraphics/Monster6.png"),
  Monster7: require("../resources/graphics/CartoonGraphics/Monster7.png"),
  Monster8: require("../resources/graphics/CartoonGraphics/Monster8.png"),
  Monster9: require("../resources/graphics/CartoonGraphics/Monster9.png"),
  Monster10: require("../resources/graphics/CartoonGraphics/Monster10.png"),
  Monster11: require("../resources/graphics/CartoonGraphics/Monster11.png"),
  Monster12: require("../resources/graphics/CartoonGraphics/Monster12.png"),
  Monster13: require("../resources/graphics/CartoonGraphics/Monster13.png"),
  Monster14: require("../resources/graphics/CartoonGraphics/Monster14.png"),
  Monster15: require("../resources/graphics/CartoonGraphics/Monster15.png"),
  Monster16: require("../resources/graphics/CartoonGraphics/Monster16.png"),
  Monster17: require("../resources/graphics/CartoonGraphics/Monster17.png"),
  Monster18: require("../resources/graphics/CartoonGraphics/Monster18.png"),
  Monster19: require("../resources/graphics/CartoonGraphics/Monster19.png"),
  Monster20: require("../resources/graphics/CartoonGraphics/Monster20.png"),
  Monster21: require("../resources/graphics/CartoonGraphics/Monster21.png"),
  Monster22: require("../resources/graphics/CartoonGraphics/Monster22.png"),
  Monster23: require("../resources/graphics/CartoonGraphics/Monster23.png"),
  Monster24: require("../resources/graphics/CartoonGraphics/Monster24.png"),
  Monster25: require("../resources/graphics/CartoonGraphics/Monster25.png"),
  Monster26: require("../resources/graphics/CartoonGraphics/Monster26.png"),
  Monster27: require("../resources/graphics/CartoonGraphics/Monster27.png"),
  Monster28: require("../resources/graphics/CartoonGraphics/Monster28.png"),
  Monster29: require("../resources/graphics/CartoonGraphics/Monster29.png"),
  Monster30: require("../resources/graphics/CartoonGraphics/Monster30.png"),
  Monster31: require("../resources/graphics/CartoonGraphics/Monster31.png"),
  Monster32: require("../resources/graphics/CartoonGraphics/Monster32.png"),
  Monster33: require("../resources/graphics/CartoonGraphics/Monster33.png"),
  Monster34: require("../resources/graphics/CartoonGraphics/Monster34.png"),
  Monster35: require("../resources/graphics/CartoonGraphics/Monster35.png"),
  Monster36: require("../resources/graphics/CartoonGraphics/Monster36.png"),
  Monster37: require("../resources/graphics/CartoonGraphics/Monster37.png"),
  Monster38: require("../resources/graphics/CartoonGraphics/Monster38.png"),
  Monster39: require("../resources/graphics/CartoonGraphics/Monster39.png"),
  Monster40: require("../resources/graphics/CartoonGraphics/Monster40.png"),
  Monster41: require("../resources/graphics/CartoonGraphics/Monster41.png"),
  Monster42: require("../resources/graphics/CartoonGraphics/Monster42.png"),
  Monster43: require("../resources/graphics/CartoonGraphics/Monster43.png"),
  Monster44: require("../resources/graphics/CartoonGraphics/Monster44.png"),
  Monster45: require("../resources/graphics/CartoonGraphics/Monster45.png"),
  Monster46: require("../resources/graphics/CartoonGraphics/Monster46.png"),
  Monster47: require("../resources/graphics/CartoonGraphics/Monster47.png"),
  Monster48: require("../resources/graphics/CartoonGraphics/Monster48.png"),
  Monster49: require("../resources/graphics/CartoonGraphics/Monster49.png"),
  Monster50: require("../resources/graphics/CartoonGraphics/Monster50.png"),
  Snake1: require("../resources/graphics/CartoonGraphics/Snake 1.png"),
  Snake2: require("../resources/graphics/CartoonGraphics/Snake 2.png"),
  Snake3: require("../resources/graphics/CartoonGraphics/Snake 3.png"),
  Snake4: require("../resources/graphics/CartoonGraphics/Snake 4.png"),
  Snake5: require("../resources/graphics/CartoonGraphics/Snake 5.png"),
  Snake6: require("../resources/graphics/CartoonGraphics/Snake 6.png"),
  Snake7: require("../resources/graphics/CartoonGraphics/Snake 7.png"),
  Snake8: require("../resources/graphics/CartoonGraphics/Snake 8.png"),
  Snake9: require("../resources/graphics/CartoonGraphics/Snake 9.png"),
  Snake10: require("../resources/graphics/CartoonGraphics/Snake 10.png"),
  Snake11: require("../resources/graphics/CartoonGraphics/Snake 11.png"),
  Snake12: require("../resources/graphics/CartoonGraphics/Snake 12.png"),
  Snake13: require("../resources/graphics/CartoonGraphics/Snake 13.png"),
  Snake14: require("../resources/graphics/CartoonGraphics/Snake 14.png"),
  Snake15: require("../resources/graphics/CartoonGraphics/Snake 15.png"),
  Snake16: require("../resources/graphics/CartoonGraphics/Snake 16.png"),
  Snake17: require("../resources/graphics/CartoonGraphics/Snake 17.png"),
  Snake18: require("../resources/graphics/CartoonGraphics/Snake 18.png"),
  Snake19: require("../resources/graphics/CartoonGraphics/Snake 19.png"),
  Snake20: require("../resources/graphics/CartoonGraphics/Snake 20.png"),
  Snake21: require("../resources/graphics/CartoonGraphics/Snake 21.png"),
  Snake22: require("../resources/graphics/CartoonGraphics/Snake 22.png"),
  Snake23: require("../resources/graphics/CartoonGraphics/Snake 23.png"),
  Snake24: require("../resources/graphics/CartoonGraphics/Snake 24.png"),
  Snake25: require("../resources/graphics/CartoonGraphics/Snake 25.png"),

  // Super Hero Graphics ---------------------------------------------

  ANTIVENOMPOP: require("../resources/graphics/SuperHeroGraphics/ANTI VENOM POP.png"),
  ANTMANENDGAME: require("../resources/graphics/SuperHeroGraphics/ANTMAN ENDGAME.png"),
  ARYASTARK: require("../resources/graphics/SuperHeroGraphics/ARYA STARK.png"),
  BACKTOTHEFUTURE: require("../resources/graphics/SuperHeroGraphics/BACK TO THE FUTURE.png"),
  Battleforeternia: require("../resources/graphics/SuperHeroGraphics/Battle for eternia.png"),
  BATMANYROBIN: require("../resources/graphics/SuperHeroGraphics/BATMAN Y ROBIN.png"),
  BezitaVader: require("../resources/graphics/SuperHeroGraphics/Bezita Vader.png"),
  blackpanter01: require("../resources/graphics/SuperHeroGraphics/black panter 01.png"),
  BlackTrooper: require("../resources/graphics/SuperHeroGraphics/Black Trooper.png"),
  BLACKWIDOWENDGAME: require("../resources/graphics/SuperHeroGraphics/BLACK WIDOW ENDGAME.png"),
  BLACKW: require("../resources/graphics/SuperHeroGraphics/BLACKW.png"),
  BRITNEY: require("../resources/graphics/SuperHeroGraphics/BRITNEY.png"),
  CAPITANAMERICA2: require("../resources/graphics/SuperHeroGraphics/CAPITAN AMERICA 2.png"),
  CAPITANAMERICA3: require("../resources/graphics/SuperHeroGraphics/CAPITAN AMERICA 3.png"),
  CAPITANAMARVEL: require("../resources/graphics/SuperHeroGraphics/CAPITANA MARVEL.png"),
  CAPTAINAMERICA1STAVENGER: require("../resources/graphics/SuperHeroGraphics/CAPTAIN AMERICA 1ST AVENGER.png"),
  CAPTAINENDGAMEV2: require("../resources/graphics/SuperHeroGraphics/CAPTAIN ENDGAME V2.png"),
  CAPTAINENDGAME: require("../resources/graphics/SuperHeroGraphics/CAPTAIN ENDGAME.png"),
  CAPTAIN1: require("../resources/graphics/SuperHeroGraphics/CAPTAIN1.png"),
  CasadepapelDalírun: require("../resources/graphics/SuperHeroGraphics/Casa de papel Dalí run.png"),
  CasadepapelgrupoCartoon: require("../resources/graphics/SuperHeroGraphics/Casa de papel grupo Cartoon.png"),
  casadepapel: require("../resources/graphics/SuperHeroGraphics/casa de papel.png"),
  CHEWBACCA: require("../resources/graphics/SuperHeroGraphics/CHEWBACCA.png"),
  chubaca: require("../resources/graphics/SuperHeroGraphics/chubaca.png"),
  DAENERYS1: require("../resources/graphics/SuperHeroGraphics/DAENERYS 1.png"),
  DAERAVILFUNKOVECTOR: require("../resources/graphics/SuperHeroGraphics/DAERAVIL FUNKO VECTOR.png"),
  deadtina: require("../resources/graphics/SuperHeroGraphics/dead tina.png"),
  deadpool01: require("../resources/graphics/SuperHeroGraphics/deadpool 01.png"),
  DeadpoolMercenary: require("../resources/graphics/SuperHeroGraphics/Deadpool Mercenary.png"),
  DeadpoolTacos: require("../resources/graphics/SuperHeroGraphics/Deadpool Tacos.png"),
  DEADPOOL: require("../resources/graphics/SuperHeroGraphics/DEADPOOL.png"),
  Droids: require("../resources/graphics/SuperHeroGraphics/Droids.png"),
  Dumbo2: require("../resources/graphics/SuperHeroGraphics/Dumbo 2.png"),
  FLINTSTONES: require("../resources/graphics/SuperHeroGraphics/FLINTSTONES.png"),
  FLYINGDRAGON: require("../resources/graphics/SuperHeroGraphics/FLYINGDRAGON.png"),
  FORTNITE: require("../resources/graphics/SuperHeroGraphics/FORTNITE.png"),
  FreddyvsJason: require("../resources/graphics/SuperHeroGraphics/Freddy vs Jason.png"),
  Freddy: require("../resources/graphics/SuperHeroGraphics/Freddy.png"),
  FUNKOIT: require("../resources/graphics/SuperHeroGraphics/FUNKO IT.png"),
  funkovegeta: require("../resources/graphics/SuperHeroGraphics/funko vegeta.png"),
  GHOSTBUSTERS4: require("../resources/graphics/SuperHeroGraphics/GHOSTBUSTERS 4.png"),
  GHOSTBUSTERS: require("../resources/graphics/SuperHeroGraphics/GHOSTBUSTERS.png"),
  GROOT2: require("../resources/graphics/SuperHeroGraphics/GROOT 2.png"),
  GROOT: require("../resources/graphics/SuperHeroGraphics/GROOT.png"),
  HarleyQueen: require("../resources/graphics/SuperHeroGraphics/HarleyQueen.png"),
  HarleyQueenB: require("../resources/graphics/SuperHeroGraphics/HarleyQueenB.png"),
  HARRYPOTTER2: require("../resources/graphics/SuperHeroGraphics/HARRY POTTER 2.png"),
  HARRYPOTTER1: require("../resources/graphics/SuperHeroGraphics/HARRY POTTER1.png"),
  HEISENBERG: require("../resources/graphics/SuperHeroGraphics/HEISENBERG.png"),
  HERMIONE: require("../resources/graphics/SuperHeroGraphics/HERMIONE.png"),
  ENDGAMEV2: require("../resources/graphics/SuperHeroGraphics/HULK ENDGAME V2.png"),
  ENDGAME: require("../resources/graphics/SuperHeroGraphics/HULK ENDGAME.png"),
  HULK: require("../resources/graphics/SuperHeroGraphics/HULK.png"),
  IRONSPIDER: require("../resources/graphics/SuperHeroGraphics/IRON SPIDER.png"),
  IRONMANENDGAME: require("../resources/graphics/SuperHeroGraphics/IRONMAN ENDGAME.png"),
  It: require("../resources/graphics/SuperHeroGraphics/It.png"),
  JIMIHENDRIX: require("../resources/graphics/SuperHeroGraphics/JIMI HENDRIX.png"),
  JOKER: require("../resources/graphics/SuperHeroGraphics/JOKER.png"),
  JURASICPOP: require("../resources/graphics/SuperHeroGraphics/JURASIC POP.png"),
  JURASIC2: require("../resources/graphics/SuperHeroGraphics/JURASSIC2.png"),
  kissfunko: require("../resources/graphics/SuperHeroGraphics/kiss funko.png"),
  LOKISARMY: require("../resources/graphics/SuperHeroGraphics/LOKIS ARMY.png"),
  MARTYSKATEBOARD: require("../resources/graphics/SuperHeroGraphics/MARTY SKATEBOARD.png"),
  MARTY: require("../resources/graphics/SuperHeroGraphics/MARTY.png"),
  MEGAMANFUNKO: require("../resources/graphics/SuperHeroGraphics/MEGAMAN FUNKO.png"),
  NIGHTKING2: require("../resources/graphics/SuperHeroGraphics/NIGHT KING 2.png"),
  NIGHTKING3: require("../resources/graphics/SuperHeroGraphics/NIGHT KING 3.png"),
  NIGHTKING: require("../resources/graphics/SuperHeroGraphics/NIGHT KING.png"),
  PREDATOR: require("../resources/graphics/SuperHeroGraphics/PREDATOR.png"),
  REBELLIONEMPIRE: require("../resources/graphics/SuperHeroGraphics/REBELLION EMPIRE.png"),
  ROCKSTEADY: require("../resources/graphics/SuperHeroGraphics/ROCKSTEADY.png"),
  RONINENDGAME: require("../resources/graphics/SuperHeroGraphics/RONIN ENDGAME.png"),
  ScartTerry: require("../resources/graphics/SuperHeroGraphics/Scart Terry.png"),
  SIRENITA: require("../resources/graphics/SuperHeroGraphics/SIRENITA.png"),
  SKELETOR2: require("../resources/graphics/SuperHeroGraphics/SKELETOR 2.png"),
  SKELETORCONQUERGRAYSKULL: require("../resources/graphics/SuperHeroGraphics/SKELETOR CONQUER GRAYSKULL.png"),
  SONIC: require("../resources/graphics/SuperHeroGraphics/SONIC.png"),
  SPIDERMAN2: require("../resources/graphics/SuperHeroGraphics/SPIDERMAN 2.png"),
  SPIDERMAN: require("../resources/graphics/SuperHeroGraphics/SPIDERMAN.png"),
  STANLEECOMPL: require("../resources/graphics/SuperHeroGraphics/STAN LEE COMPL.png"),
  STITCH: require("../resources/graphics/SuperHeroGraphics/STITCH.png"),
  STORMTROOPER: require("../resources/graphics/SuperHeroGraphics/STORM TROOPER.png"),
  SUPERMAN: require("../resources/graphics/SuperHeroGraphics/SUPERMAN.png"),
  TARGARYEN: require("../resources/graphics/SuperHeroGraphics/TARGARYEN.png"),
  THANOSENDGAMEV2: require("../resources/graphics/SuperHeroGraphics/THANOS ENDGAME V2.png"),
  THANOSENDGAME: require("../resources/graphics/SuperHeroGraphics/THANOS ENDGAME.png"),
  THANOS: require("../resources/graphics/SuperHeroGraphics/THANOS.png"),
  TheJoker: require("../resources/graphics/SuperHeroGraphics/The Joker.png"),
  THOR4: require("../resources/graphics/SuperHeroGraphics/THOR 4.png"),
  THORENDGAME: require("../resources/graphics/SuperHeroGraphics/THOR ENDGAME.png"),
  thor: require("../resources/graphics/SuperHeroGraphics/thor.png"),
  TMNT2: require("../resources/graphics/SuperHeroGraphics/TMNT 2.png"),
  Turtles: require("../resources/graphics/SuperHeroGraphics/Turtles.png"),
  VADERKENOBI: require("../resources/graphics/SuperHeroGraphics/VADER KENOBI.png"),
  VENOM2: require("../resources/graphics/SuperHeroGraphics/VENOM 2.png"),
  VENOM1: require("../resources/graphics/SuperHeroGraphics/VENOM1.png"),
  WONDERWOMANRETRO: require("../resources/graphics/SuperHeroGraphics/WONDER WOMAN RETRO.png"),
  wonderwomanfunko: require("../resources/graphics/SuperHeroGraphics/wonder woman funko.png"),
};

export default IMG;
