import IMG from "./_photoIMPORTS";
import { nanoid } from "nanoid";

const Photos = [
  {
    id: nanoid(),
    src: IMG.AlbertKisstein,
    alt: "eraseThis",
    name: "Albert Kisstein",
    fee: 3,
  },
  {
    id: nanoid(),
    src: IMG.AmericanPsycho2,
    alt: "eraseThis",
    name: "American Psycho 2",
    fee: 3,
  },
  {
    id: nanoid(),
    src: IMG.AmericanPsycho,
    alt: "eraseThis",
    name: "American Psycho",
    fee: 3,
  },
  {
    id: nanoid(),
    src: IMG.BenjaminDranklin,
    alt: "eraseThis",
    name: "Benjamin Dranklin",
    fee: 3,
  },
  {
    id: nanoid(),
    src: IMG.CharimanMeow,
    alt: "eraseThis",
    name: "Chariman Meow",
    fee: 3,
  },
  {
    id: nanoid(),
    src: IMG.Chef,
    alt: "eraseThis",
    name: "Chef",
    fee: 3,
  },
  {
    id: nanoid(),
    src: IMG.Covfefe,
    alt: "eraseThis",
    name: "Covfefe",
    fee: 3,
  },
  {
    id: nanoid(),
    src: IMG.Dope,
    alt: "eraseThis",
    name: "Dope",
    fee: 3,
  },
  {
    id: nanoid(),
    src: IMG.Dream,
    alt: "eraseThis",
    name: "Dream",
    fee: 3,
  },
  {
    id: nanoid(),
    src: IMG.GotMLK,
    alt: "eraseThis",
    name: "Got MLK",
    fee: 3,
  },
  {
    id: nanoid(),
    src: IMG.Heilstein,
    alt: "eraseThis",
    name: "Heilstein",
    fee: 3,
  },
  {
    id: nanoid(),
    src: IMG.HoHoHoChiMinh,
    alt: "eraseThis",
    name: "HoHoHo Chi Minh",
    fee: 3,
  },
  {
    id: nanoid(),
    src: IMG.ICantBreathe,
    alt: "eraseThis",
    name: "I Can't Breathe",
    fee: 3,
  },
  {
    id: nanoid(),
    src: IMG.JusticeForGeorgeFloyd,
    alt: "eraseThis",
    name: "Justice For George Floyd",
    fee: 3,
  },
  {
    id: nanoid(),
    src: IMG.LincolnUnknown,
    alt: "eraseThis",
    name: "Lincoln Unknown",
    fee: 3,
  },
  {
    id: nanoid(),
    src: IMG.MakeAmericaGreyAgain,
    alt: "eraseThis",
    name: "Make America Grey Again",
    fee: 3,
  },
  {
    id: nanoid(),
    src: IMG.MeowTseTung,
    alt: "eraseThis",
    name: "Meow Tse Tung",
    fee: 3,
  },
  {
    id: nanoid(),
    src: IMG.Merica,
    alt: "eraseThis",
    name: "Merica",
    fee: 3,
  },
  {
    id: nanoid(),
    src: IMG.MericaTrump,
    alt: "eraseThis",
    name: "Merica Trump",
    fee: 3,
  },
  {
    id: nanoid(),
    src: IMG.NoRacism,
    alt: "eraseThis",
    name: "No Racism",
    fee: 3,
  },
  {
    id: nanoid(),
    src: IMG.Putintin,
    alt: "eraseThis",
    name: "Putintin",
    fee: 3,
  },
  {
    id: nanoid(),
    src: IMG.RocketBoy,
    alt: "eraseThis",
    name: "Rocket Boy",
    fee: 3,
  },
  {
    id: nanoid(),
    src: IMG.RocketMan,
    alt: "eraseThis",
    name: "Rocket Man",
    fee: 3,
  },
  {
    id: nanoid(),
    src: IMG.StraigtOuttaPyongYang,
    alt: "eraseThis",
    name: "Straigt Outta Pyong Yang",
    fee: 3,
  },
  {
    id: nanoid(),
    src: IMG.SylvesterStalin,
    alt: "eraseThis",
    name: "Sylvester Stalin",
    fee: 3,
  },
  {
    id: nanoid(),
    src: IMG.TheFuhrer,
    alt: "eraseThis",
    name: "The Fuhrer",
    fee: 3,
  },
  {
    id: nanoid(),
    src: IMG.Trump,
    alt: "eraseThis",
    name: "Trump",
    fee: 3,
  },
  {
    id: nanoid(),
    src: IMG.UnderControl,
    alt: "eraseThis",
    name: "Under Control",
    fee: 3,
  },
  {
    id: nanoid(),
    src: IMG.VivaLaEvolucion,
    alt: "eraseThis",
    name: "Viva La Evolucion",
    fee: 3,
  },
  {
    id: nanoid(),
    src: IMG.WeCanDoIt,
    alt: "eraseThis",
    name: "We Can Do It",
    fee: 3,
  },
];
export default Photos;

// {
//   id: nanoid(),
//   src: IMG.stufffffff,
//   alt: "eraseThis",
//   name: "eraseThis",
//   fee: 3,
// },


