import IMG from "./__photoIMPORTS";
import { nanoid } from "nanoid";

const Photos = [
  {
    id: nanoid(),
    src: IMG.Cat1,
    alt: "Full color cartoon cat",
    name: "Cat 1",
    fee: 3,
  },
  {
    id: nanoid(),
    src: IMG.Cat2,
    alt: "Full color cartoon cat",
    name: "Cat 2",
    fee: 3,
  },
  {
    id: nanoid(),
    src: IMG.Cat3,
    alt: "Full color cartoon cat",
    name: "Cat 3",
    fee: 3,
  },
  {
    id: nanoid(),
    src: IMG.Cat4,
    alt: "Full color cartoon cat",
    name: "Cat 4",
    fee: 3,
  },
  {
    id: nanoid(),
    src: IMG.Cat5,
    alt: "Full color cartoon cat",
    name: "Cat 5",
    fee: 3,
  },
  {
    id: nanoid(),
    src: IMG.Cat6,
    alt: "Full color cartoon cat",
    name: "Cat 6",
    fee: 3,
  },
  {
    id: nanoid(),
    src: IMG.Cat7,
    alt: "Full color cartoon cat",
    name: "Cat 7",
    fee: 3,
  },
  {
    id: nanoid(),
    src: IMG.Cat8,
    alt: "Full color cartoon cat",
    name: "Cat 8",
    fee: 3,
  },
  {
    id: nanoid(),
    src: IMG.Cat9,
    alt: "Full color cartoon cat",
    name: "Cat 9",
    fee: 3,
  },
  {
    id: nanoid(),
    src: IMG.Cat10,
    alt: "Full color cartoon cat",
    name: "Cat 10",
    fee: 3,
  },
  {
    id: nanoid(),
    src: IMG.Cat11,
    alt: "Full color cartoon cat",
    name: "Cat 11",
    fee: 3,
  },
  {
    id: nanoid(),
    src: IMG.Cat12,
    alt: "Full color cartoon cat",
    name: "Cat 12",
    fee: 3,
  },
  {
    id: nanoid(),
    src: IMG.Cat13,
    alt: "Full color cartoon cat",
    name: "Cat 13",
    fee: 3,
  },
  {
    id: nanoid(),
    src: IMG.Cat14,
    alt: "Full color cartoon cat",
    name: "Cat 14",
    fee: 3,
  },
  {
    id: nanoid(),
    src: IMG.Cat15,
    alt: "Full color cartoon cat",
    name: "Cat 15",
    fee: 3,
  },
  {
    id: nanoid(),
    src: IMG.Cat16,
    alt: "Full color cartoon cat",
    name: "Cat 16",
    fee: 3,
  },
  {
    id: nanoid(),
    src: IMG.Cat17,
    alt: "Full color cartoon cat",
    name: "Cat 17",
    fee: 3,
  },
  {
    id: nanoid(),
    src: IMG.Cat18,
    alt: "Full color cartoon cat",
    name: "Cat 18",
    fee: 3,
  },
  {
    id: nanoid(),
    src: IMG.Cat19,
    alt: "Full color cartoon cat",
    name: "Cat 19",
    fee: 3,
  },
  {
    id: nanoid(),
    src: IMG.Cat20,
    alt: "Full color cartoon cat",
    name: "Cat 20",
    fee: 3,
  },
  {
    id: nanoid(),
    src: IMG.Cat21,
    alt: "Full color cartoon cat",
    name: "Cat 21",
    fee: 3,
  },
  {
    id: nanoid(),
    src: IMG.Cat22,
    alt: "Full color cartoon cat",
    name: "Cat 22",
    fee: 3,
  },
  {
    id: nanoid(),
    src: IMG.Cat23,
    alt: "Full color cartoon cat",
    name: "Cat 23",
    fee: 3,
  },
  {
    id: nanoid(),
    src: IMG.Cat24,
    alt: "Full color cartoon cat",
    name: "Cat 24",
    fee: 3,
  },
  {
    id: nanoid(),
    src: IMG.Cat25,
    alt: "Full color cartoon cat",
    name: "Cat 25",
    fee: 3,
  },
];
export default Photos;

// {
//   id: nanoid(),
//   src: IMG.stufffffff,
//   alt: "eraseThis",
//   name: "eraseThis",
//   fee: 3,
// },
