import IMG from "./_photoIMPORTS";
import { nanoid } from "nanoid";

const Photos = [
  {
    id: nanoid(),
    src: IMG.Abduction,
    alt: "a cat being abducted by aliens in color",
    name: "Abduction",
    fee: 3,
  },
  {
    id: nanoid(),
    src: IMG.AngryWaves,
    alt: "a tug boat in stormy waves in color",
    name: "Angry Waves",
    fee: 3,
  },
  {
    id: nanoid(),
    src: IMG.Aquarium,
    alt: "cats staring a fish in a pocket in color",
    name: "Aquarium",
    fee: 3,
  },
  {
    id: nanoid(),
    src: IMG.BeAwesome,
    alt: "school supplies in a pokcet in color",
    name: "Be Awesome",
    fee: 3,
  },
  {
    id: nanoid(),
    src: IMG.Cactus,
    alt: "a cactus in a pocket in color",
    name: "Cactus",
    fee: 3,
  },
  {
    id: nanoid(),
    src: IMG.CatSkeleton,
    alt: "an x-ray image of a cat in color",
    name: "Cat Skeleton",
    fee: 3,
  },
  {
    id: nanoid(),
    src: IMG.ChildMoon,
    alt: "a person on the moon fishing in color",
    name: "ChildMoon",
    fee: 3,
  },
  {
    id: nanoid(),
    src: IMG.CourageDog,
    alt: "a dog with a worried look on his face in color",
    name: "Courage Dog",
    fee: 3,
  },
  {
    id: nanoid(),
    src: IMG.CuteCat,
    alt: "a cat staring ahead in color",
    name: "Cute Cat",
    fee: 3,
  },
  {
    id: nanoid(),
    src: IMG.Dollar,
    alt: "hundred dollar bills coming out of a pocket in color",
    name: "Dollar",
    fee: 3,
  },
  {
    id: nanoid(),
    src: IMG.FallingCat,
    alt: "cat falling down out of inverted pocket in color",
    name: "Falling Cat",
    fee: 3,
  },
  {
    id: nanoid(),
    src: IMG.Fish,
    alt: "a fish swimming in a pocket in color",
    name: "Fish",
    fee: 3,
  },
  {
    id: nanoid(),
    src: IMG.Ghost,
    alt: "ghosts coming out of pocket with a net in color",
    name: "Ghost",
    fee: 3,
  },
  {
    id: nanoid(),
    src: IMG.GoldenCoins,
    alt: "gold coins overflowing out of pocket in color",
    name: "Golden Coins",
    fee: 3,
  },
  {
    id: nanoid(),
    src: IMG.Heart,
    alt: "a heart in a pocket with flowers growing out of it in color",
    name: "Heart",
    fee: 3,
  },
  {
    id: nanoid(),
    src: IMG.Hotdog,
    alt: "a weiner dog in a bun in color",
    name: "Hotdog",
    fee: 3,
  },
  {
    id: nanoid(),
    src: IMG.Husky,
    alt: "a husky poking his head out of a pocket in color",
    name: "Husky",
    fee: 3,
  },
  {
    id: nanoid(),
    src: IMG.Icecreampocket,
    alt: "two ice cream cones coming out of a pocket in color",
    name: "Ice cream",
    fee: 3,
  },
  {
    id: nanoid(),
    src: IMG.Knife,
    alt: "a knife in a pocket in color",
    name: "Knife",
    fee: 3,
  },
  {
    id: nanoid(),
    src: IMG.LoveAtFirstBite,
    alt: "pizza in a pocket in color",
    name: "Love At First Bite",
    fee: 3,
  },
  {
    id: nanoid(),
    src: IMG.Minion,
    alt: "a minion sticking his head out of a pocket in color",
    name: "Minion",
    fee: 3,
  },
  {
    id: nanoid(),
    src: IMG.MonkeyButt,
    alt: "a monkey bending over and showing his butt in color",
    name: "Monkey Butt",
    fee: 3,
  },
  {
    id: nanoid(),
    src: IMG.Octopus,
    alt: "an octopus in a pocket in color",
    name: "Octopus",
    fee: 3,
  },
  {
    id: nanoid(),
    src: IMG.Palm,
    alt: "palm trees growing out of a pocket in color",
    name: "Palm",
    fee: 3,
  },
  {
    id: nanoid(),
    src: IMG.Panda,
    alt: "a happy panda bear in a pocket in color",
    name: "Panda",
    fee: 3,
  },
  {
    id: nanoid(),
    src: IMG.PinupGirl,
    alt: "a sexy woman with head and legs coming out of pocket in color",
    name: "Pinup Girl",
    fee: 3,
  },
  {
    id: nanoid(),
    src: IMG.PinkPanther,
    alt: "Pink Panther in a pocket in color",
    name: "Pink Panther",
    fee: 3,
  },
  {
    id: nanoid(),
    src: IMG.Popcorn,
    alt: "a movie-style popcorn in color",
    name: "Popcorn",
    fee: 3,
  },
  {
    id: nanoid(),
    src: IMG.Pug,
    alt: "a pug dog in a pocket in color",
    name: "Pug",
    fee: 3,
  },
  {
    id: nanoid(),
    src: IMG.SeaStar,
    alt: "star fish in a pocket in color",
    name: "Sea Star",
    fee: 3,
  },
  {
    id: nanoid(),
    src: IMG.Sun,
    alt: "sun and beach umbrellas in a pocket in color",
    name: "Sun",
    fee: 3,
  },
  {
    id: nanoid(),
    src: IMG.Swimming,
    alt: "a man swimming in a pocket with a life in color",
    name: "Swimming",
    fee: 3,
  },
  {
    id: nanoid(),
    src: IMG.TropicalFruit,
    alt: "a tropical themed pocket in color",
    name: "Tropical Fruit",
    fee: 3,
  },
  {
    id: nanoid(),
    src: IMG.WateringFlowers,
    alt: "a girl watering flowers that a boy is holding below in color",
    name: "Watering Flowers",
    fee: 3,
  },
  {
    id: nanoid(),
    src: IMG.ZombieHands,
    alt: "zombie hands coming out of pocket in color",
    name: "Zombie Hands",
    fee: 3,
  },
];
export default Photos;

// {
//   id: nanoid(),
//   src: IMG.stufffffff,
//   alt: "eraseThis",
//   name: "eraseThis",
//   fee: 3,
// },
