import IMG from "./_photoIMPORTS";
import { nanoid } from "nanoid";

const Photos = [
  {
    id: nanoid(),
    src: IMG.BHM365Days,
    alt: "Black history poster with fist in color",
    name: "BHM 365 Days",
    fee: 3,
  },
  {
    id: nanoid(),
    src: IMG.BHMMalcolmX,
    alt: "Malcolm X caricature poster in color",
    name: "BHM Malcolm X",
    fee: 3,
  },
  {
    id: nanoid(),
    src: IMG.BHMMap,
    alt: "USA and Africa map poster in color",
    name: "BHM pan-Africa Map",
    fee: 3,
  },
  {
    id: nanoid(),
    src: IMG.BHMMLK,
    alt: "MLK badge poster in color",
    name: "BHM MLK",
    fee: 3,
  },
  {
    id: nanoid(),
    src: IMG.BHMPowerHand,
    alt: "black power fist in front of map poster in color",
    name: "BHM Power Hand",
    fee: 3,
  },
  {
    id: nanoid(),
    src: IMG.BHM,
    alt: "text with fist in foreground poster in color",
    name: "BHM",
    fee: 3,
  },
  {
    id: nanoid(),
    src: IMG.BH,
    alt: "malcolm x head poster in color",
    name: "Black Hx",
    fee: 3,
  },
  {
    id: nanoid(),
    src: IMG.BLMHand,
    alt: "power fist with text poster in color",
    name: "BLM Hand",
    fee: 3,
  },
  {
    id: nanoid(),
    src: IMG.MartinLutherJunior,
    alt: "MLK jr. poster in color",
    name: "Martin Luther Junior",
    fee: 3,
  },
  {
    id: nanoid(),
    src: IMG.BLMMLK,
    alt: "MLK jr. poster in color",
    name: "BLM",
    fee: 3,
  },
  {
    id: nanoid(),
    src: IMG.BlackLivesMatter,
    alt: "afro charicature in front of flag in color",
    name: "Black Lives Matter",
    fee: 3,
  },
  {
    id: nanoid(),
    src: IMG.DreamBH,
    alt: "MLK dream poster in color",
    name: "Dream BHx",
    fee: 3,
  },
  {
    id: nanoid(),
    src: IMG.EnoughIsEnough,
    alt: "George Floyd in front of text poster in color",
    name: "Enough Is Enough",
    fee: 3,
  },
  {
    id: nanoid(),
    src: IMG.FrederickDouglass,
    alt: "Frederick Douglass badge poster in color",
    name: "Frederick Douglass",
    fee: 3,
  },
  {
    id: nanoid(),
    src: IMG.FreedomBH,
    alt: "afro female poster in color",
    name: "Freedom BHx",
    fee: 3,
  },
  {
    id: nanoid(),
    src: IMG.JohnLewis,
    alt: "john lweis poster in color",
    name: "John Lewis",
    fee: 3,
  },
  {
    id: nanoid(),
    src: IMG.EveryMonthBH,
    alt: "hands in shackles poster in color",
    name: "Every Month BHx",
    fee: 3,
  },
  {
    id: nanoid(),
    src: IMG.MalcolmXBH,
    alt: "Malcolm x poster in color",
    name: "Malcolm X BHx",
    fee: 3,
  },
  {
    id: nanoid(),
    src: IMG.MLKBH,
    alt: "MLK poster in color",
    name: "MLK BHx",
    fee: 3,
  },
  {
    id: nanoid(),
    src: IMG.Riot,
    alt: "call to action poster in color",
    name: "Riot",
    fee: 3,
  },
  {
    id: nanoid(),
    src: IMG.WeCanDoIt,
    alt: "strong afro female poster in color",
    name: "We Can Do It",
    fee: 3,
  },
];
export default Photos;

// {
//   id: nanoid(),
//   src: IMG.stufffffff,
//   alt: "eraseThis",
//   name: "eraseThis",
//   fee: 3,
// },
