import IMG from "./photoIMPORTS";
import { nanoid } from "nanoid";

const Photos = [
  {
    id: nanoid(),
    src: IMG.Dragon1,
    alt: "eraseThis",
    name: "Dragon 1",
    fee: 3,
  },
  {
    id: nanoid(),
    src: IMG.Dragon2,
    alt: "eraseThis",
    name: "Dragon 2",
    fee: 3,
  },
  {
    id: nanoid(),
    src: IMG.Dragon3,
    alt: "eraseThis",
    name: "Dragon 3",
    fee: 3,
  },
  {
    id: nanoid(),
    src: IMG.Dragon4,
    alt: "eraseThis",
    name: "Dragon 4",
    fee: 3,
  },
  {
    id: nanoid(),
    src: IMG.Dragon5,
    alt: "eraseThis",
    name: "Dragon 5",
    fee: 3,
  },
  {
    id: nanoid(),
    src: IMG.Dragon6,
    alt: "eraseThis",
    name: "Dragon 6",
    fee: 3,
  },
  {
    id: nanoid(),
    src: IMG.Dragon7,
    alt: "eraseThis",
    name: "Dragon 7",
    fee: 3,
  },
  {
    id: nanoid(),
    src: IMG.Dragon8,
    alt: "eraseThis",
    name: "Dragon 8",
    fee: 3,
  },
  {
    id: nanoid(),
    src: IMG.Dragon9,
    alt: "eraseThis",
    name: "Dragon 9",
    fee: 3,
  },
  {
    id: nanoid(),
    src: IMG.Dragon10,
    alt: "eraseThis",
    name: "Dragon 10",
    fee: 3,
  },
  {
    id: nanoid(),
    src: IMG.Dragon11,
    alt: "eraseThis",
    name: "Dragon 11",
    fee: 3,
  },
  {
    id: nanoid(),
    src: IMG.Dragon12,
    alt: "eraseThis",
    name: "Dragon 12",
    fee: 3,
  },
  {
    id: nanoid(),
    src: IMG.Dragon13,
    alt: "eraseThis",
    name: "Dragon 13",
    fee: 3,
  },
  {
    id: nanoid(),
    src: IMG.Dragon14,
    alt: "eraseThis",
    name: "Dragon 14",
    fee: 3,
  },
  {
    id: nanoid(),
    src: IMG.Dragon15,
    alt: "eraseThis",
    name: "Dragon 15",
    fee: 3,
  },
  {
    id: nanoid(),
    src: IMG.Dragon16,
    alt: "eraseThis",
    name: "Dragon 16",
    fee: 3,
  },
  {
    id: nanoid(),
    src: IMG.Dragon17,
    alt: "eraseThis",
    name: "Dragon 17",
    fee: 3,
  },
  {
    id: nanoid(),
    src: IMG.Dragon18,
    alt: "eraseThis",
    name: "Dragon 18",
    fee: 3,
  },
  {
    id: nanoid(),
    src: IMG.Dragon19,
    alt: "eraseThis",
    name: "Dragon 19",
    fee: 3,
  },
  {
    id: nanoid(),
    src: IMG.Dragon20,
    alt: "eraseThis",
    name: "Dragon 20",
    fee: 3,
  },
  {
    id: nanoid(),
    src: IMG.Dragon21,
    alt: "eraseThis",
    name: "Dragon 21",
    fee: 3,
  },
  {
    id: nanoid(),
    src: IMG.Dragon22,
    alt: "eraseThis",
    name: "Dragon 22",
    fee: 3,
  },
  {
    id: nanoid(),
    src: IMG.Dragon23,
    alt: "eraseThis",
    name: "Dragon 23",
    fee: 3,
  },
  {
    id: nanoid(),
    src: IMG.Dragon24,
    alt: "eraseThis",
    name: "Dragon 24",
    fee: 3,
  },
  {
    id: nanoid(),
    src: IMG.Dragon25,
    alt: "eraseThis",
    name: "Dragon 25",
    fee: 3,
  },
];
export default Photos;

// {
//   id: nanoid(),
//   src: IMG.stufffffff,
//   alt: "eraseThis",
//   name: "eraseThis",
//   fee: 3,
// },
