import IMG from "./__photoIMPORTS";
import { nanoid } from "nanoid";

const Photos = [
  {
    id: nanoid(),
    src: IMG.AnchorBones,
    alt: "full color graphic",
    name: "Anchor Bones",
    fee: 3,
  },
  {
    id: nanoid(),
    src: IMG.Anchor,
    alt: "full color graphic",
    name: "Anchor",
    fee: 3,
  },
  {
    id: nanoid(),
    src: IMG.Astrocode,
    alt: "full color graphic",
    name: "Astrocode",
    fee: 3,
  },
  {
    id: nanoid(),
    src: IMG.Awesome,
    alt: "full color graphic",
    name: "Awesome",
    fee: 3,
  },
  {
    id: nanoid(),
    src: IMG.BananaSkateboard,
    alt: "full color graphic",
    name: "Banana Skateboard",
    fee: 3,
  },
  {
    id: nanoid(),
    src: IMG.BaseballPlayer,
    alt: "full color graphic",
    name: "Baseball Player",
    fee: 3,
  },
  {
    id: nanoid(),
    src: IMG.BasketballPlayer,
    alt: "full color graphic",
    name: "Basketball Player",
    fee: 3,
  },
  {
    id: nanoid(),
    src: IMG.Beetle,
    alt: "full color graphic",
    name: "Beetle",
    fee: 3,
  },
  {
    id: nanoid(),
    src: IMG.BicycleSkull,
    alt: "full color graphic",
    name: "Bicycle Skull",
    fee: 3,
  },
  {
    id: nanoid(),
    src: IMG.BirdsBeard,
    alt: "full color graphic",
    name: "Birds Beard",
    fee: 3,
  },
  {
    id: nanoid(),
    src: IMG.BrainGloves,
    alt: "full color graphic",
    name: "Brain Gloves",
    fee: 3,
  },
  {
    id: nanoid(),
    src: IMG.BreakingNoise,
    alt: "full color graphic",
    name: "Breaking Noise",
    fee: 3,
  },
  {
    id: nanoid(),
    src: IMG.Burger,
    alt: "full color graphic",
    name: "Burger",
    fee: 3,
  },
  {
    id: nanoid(),
    src: IMG.CheSmiley,
    alt: "full color graphic",
    name: "Che Smiley",
    fee: 3,
  },
  {
    id: nanoid(),
    src: IMG.CoffeeTree,
    alt: "full color graphic",
    name: "Coffee Tree",
    fee: 3,
  },
  {
    id: nanoid(),
    src: IMG.Coffee,
    alt: "full color graphic",
    name: "Coffee",
    fee: 3,
  },
  {
    id: nanoid(),
    src: IMG.Crab,
    alt: "full color graphic",
    name: "Crab",
    fee: 3,
  },
  {
    id: nanoid(),
    src: IMG.CrystalLake,
    alt: "full color graphic",
    name: "Crystal Lake",
    fee: 3,
  },
  {
    id: nanoid(),
    src: IMG.DeadSchool,
    alt: "full color graphic",
    name: "Dead School",
    fee: 3,
  },
  {
    id: nanoid(),
    src: IMG.DeadSea,
    alt: "full color graphic",
    name: "Dead Sea",
    fee: 3,
  },
  {
    id: nanoid(),
    src: IMG.DeathCity,
    alt: "full color graphic",
    name: "Death City",
    fee: 3,
  },
  {
    id: nanoid(),
    src: IMG.Deer2,
    alt: "full color graphic",
    name: "Deer 2",
    fee: 3,
  },
  {
    id: nanoid(),
    src: IMG.Deer3,
    alt: "full color graphic",
    name: "Deer 3",
    fee: 3,
  },
  {
    id: nanoid(),
    src: IMG.DeerButterfly,
    alt: "full color graphic",
    name: "Deer Butterfly",
    fee: 3,
  },
  {
    id: nanoid(),
    src: IMG.Deer,
    alt: "full color graphic",
    name: "Deer",
    fee: 3,
  },
  {
    id: nanoid(),
    src: IMG.DonutBarbell,
    alt: "full color graphic",
    name: "Donut Barbell",
    fee: 3,
  },
  {
    id: nanoid(),
    src: IMG.Eagle,
    alt: "full color graphic",
    name: "Eagle",
    fee: 3,
  },
  {
    id: nanoid(),
    src: IMG.ElectricAnchor,
    alt: "full color graphic",
    name: "Electric Anchor",
    fee: 3,
  },
  {
    id: nanoid(),
    src: IMG.ElectricBalance,
    alt: "full color graphic",
    name: "Electric Balance",
    fee: 3,
  },
  {
    id: nanoid(),
    src: IMG.ElectricBrain,
    alt: "full color graphic",
    name: "Electric Brain",
    fee: 3,
  },
  {
    id: nanoid(),
    src: IMG.ElectricDeer,
    alt: "full color graphic",
    name: "Electric Deer",
    fee: 3,
  },
  {
    id: nanoid(),
    src: IMG.ElectricSkull,
    alt: "full color graphic",
    name: "Electric Skull",
    fee: 3,
  },
  {
    id: nanoid(),
    src: IMG.ElectricSmiley,
    alt: "full color graphic",
    name: "Electric Smiley",
    fee: 3,
  },
  {
    id: nanoid(),
    src: IMG.ElectricalOwl,
    alt: "full color graphic",
    name: "Electrical Owl",
    fee: 3,
  },
  {
    id: nanoid(),
    src: IMG.EnjoyYourLie,
    alt: "full color graphic",
    name: "Enjoy Your Lie",
    fee: 3,
  },
  {
    id: nanoid(),
    src: IMG.FloatLikeButterflyStingLikeBee,
    alt: "full color graphic",
    name: "Float Like Butterfly",
    fee: 3,
  },
  {
    id: nanoid(),
    src: IMG.FlourishVandalism,
    alt: "full color graphic",
    name: "Flourish Vandalism",
    fee: 3,
  },
  {
    id: nanoid(),
    src: IMG.FlyingAstronaut,
    alt: "full color graphic",
    name: "Flying Astronaut",
    fee: 3,
  },
  {
    id: nanoid(),
    src: IMG.FroggyNight,
    alt: "full color graphic",
    name: "Froggy Night",
    fee: 3,
  },
  {
    id: nanoid(),
    src: IMG.GhostFaceBats,
    alt: "full color graphic",
    name: "Ghostface Bats",
    fee: 3,
  },
  {
    id: nanoid(),
    src: IMG.Godzilla,
    alt: "full color graphic",
    name: "Godzilla",
    fee: 3,
  },
  {
    id: nanoid(),
    src: IMG.GoodIdea,
    alt: "full color graphic",
    name: "Good Idea",
    fee: 3,
  },
  {
    id: nanoid(),
    src: IMG.GramophoneDonut,
    alt: "full color graphic",
    name: "Gramophone Donut",
    fee: 3,
  },
  {
    id: nanoid(),
    src: IMG.GreenMonster,
    alt: "full color graphic",
    name: "Green Monster",
    fee: 3,
  },
  {
    id: nanoid(),
    src: IMG.Grenade,
    alt: "full color graphic",
    name: "Grenade",
    fee: 3,
  },
  {
    id: nanoid(),
    src: IMG.HandOfRevolution,
    alt: "full color graphic",
    name: "Hand Of Revolution",
    fee: 3,
  },
  {
    id: nanoid(),
    src: IMG.HandOfZombies,
    alt: "full color graphic",
    name: "Hand Of Zombies",
    fee: 3,
  },
  {
    id: nanoid(),
    src: IMG.HeadphoneDonut,
    alt: "full color graphic",
    name: "Headphone Donut",
    fee: 3,
  },
  {
    id: nanoid(),
    src: IMG.Hipster,
    alt: "full color graphic",
    name: "Hipster",
    fee: 3,
  },
  {
    id: nanoid(),
    src: IMG.HomeHeart,
    alt: "full color graphic",
    name: "Home Heart",
    fee: 3,
  },
  {
    id: nanoid(),
    src: IMG.Icecream,
    alt: "full color graphic",
    name: "Icecream",
    fee: 3,
  },
  {
    id: nanoid(),
    src: IMG.JasonMoon,
    alt: "full color graphic",
    name: "Jason Moon",
    fee: 3,
  },
  {
    id: nanoid(),
    src: IMG.Kaiju2,
    alt: "full color graphic",
    name: "Kaiju2",
    fee: 3,
  },
  {
    id: nanoid(),
    src: IMG.Kaiju,
    alt: "full color graphic",
    name: "Kaiju",
    fee: 3,
  },
  {
    id: nanoid(),
    src: IMG.KnowYourRoots,
    alt: "full color graphic",
    name: "Know Your Roots",
    fee: 3,
  },
  {
    id: nanoid(),
    src: IMG.Liberty,
    alt: "full color graphic",
    name: "Liberty",
    fee: 3,
  },
  {
    id: nanoid(),
    src: IMG.LifeAndDeath,
    alt: "full color graphic",
    name: "Life and Death",
    fee: 3,
  },
  {
    id: nanoid(),
    src: IMG.LOL,
    alt: "full color graphic",
    name: "LOL",
    fee: 3,
  },
  {
    id: nanoid(),
    src: IMG.Milkyway,
    alt: "full color graphic",
    name: "Milkyway",
    fee: 3,
  },
  {
    id: nanoid(),
    src: IMG.NatureOfCrime,
    alt: "full color graphic",
    name: "Nature Of Crime",
    fee: 3,
  },
  {
    id: nanoid(),
    src: IMG.Nerd,
    alt: "full color graphic",
    name: "Nerd",
    fee: 3,
  },
  {
    id: nanoid(),
    src: IMG.Peace,
    alt: "full color graphic",
    name: "Peace",
    fee: 3,
  },
  {
    id: nanoid(),
    src: IMG.PizzaMoon,
    alt: "full color graphic",
    name: "Pizza Moon",
    fee: 3,
  },
  {
    id: nanoid(),
    src: IMG.PizzaScratch,
    alt: "full color graphic",
    name: "Pizza Scratch",
    fee: 3,
  },
  {
    id: nanoid(),
    src: IMG.PizzaUFO,
    alt: "full color graphic",
    name: "Pizza UFO",
    fee: 3,
  },
  {
    id: nanoid(),
    src: IMG.Pizza,
    alt: "full color graphic",
    name: "Pizza",
    fee: 3,
  },
  {
    id: nanoid(),
    src: IMG.Prismzza,
    alt: "full color graphic",
    name: "Prismzza",
    fee: 3,
  },
  {
    id: nanoid(),
    src: IMG.ReaperScream,
    alt: "full color graphic",
    name: "Reaper Scream",
    fee: 3,
  },
  {
    id: nanoid(),
    src: IMG.Recycling,
    alt: "full color graphic",
    name: "Recycling",
    fee: 3,
  },
  {
    id: nanoid(),
    src: IMG.RhymeInPeace,
    alt: "full color graphic",
    name: "Rhyme in Peace",
    fee: 3,
  },
  {
    id: nanoid(),
    src: IMG.RibcageBird,
    alt: "full color graphic",
    name: "Ribcage Bird",
    fee: 3,
  },
  {
    id: nanoid(),
    src: IMG.Scooter,
    alt: "full color graphic",
    name: "Scooter",
    fee: 3,
  },
  {
    id: nanoid(),
    src: IMG.SeaHorse,
    alt: "full color graphic",
    name: "Sea Horse",
    fee: 3,
  },
  {
    id: nanoid(),
    src: IMG.SherlockHolmes,
    alt: "full color graphic",
    name: "Sherlock Holmes",
    fee: 3,
  },
  {
    id: nanoid(),
    src: IMG.Skater,
    alt: "full color graphic",
    name: "Skater",
    fee: 3,
  },
  {
    id: nanoid(),
    src: IMG.SkaterHook,
    alt: "full color graphic",
    name: "Skater Hook",
    fee: 3,
  },
  {
    id: nanoid(),
    src: IMG.SkullNature,
    alt: "full color graphic",
    name: "Skull Nature",
    fee: 3,
  },
  {
    id: nanoid(),
    src: IMG.SmileyMoon,
    alt: "full color graphic",
    name: "Smiley Moon",
    fee: 3,
  },
  {
    id: nanoid(),
    src: IMG.Smiley,
    alt: "full color graphic",
    name: "Smiley",
    fee: 3,
  },
  {
    id: nanoid(),
    src: IMG.SmokingKills,
    alt: "full color graphic",
    name: "Smoking Kills",
    fee: 3,
  },
  {
    id: nanoid(),
    src: IMG.SoundCollector,
    alt: "full color graphic",
    name: "Sound Collector",
    fee: 3,
  },
  {
    id: nanoid(),
    src: IMG.SoundOfRain,
    alt: "full color graphic",
    name: "Sound Of Rain",
    fee: 3,
  },
  {
    id: nanoid(),
    src: IMG.StandAndBleed,
    alt: "full color graphic",
    name: "Stand and Bleed",
    fee: 3,
  },
  {
    id: nanoid(),
    src: IMG.TheBridge,
    alt: "full color graphic",
    name: "The Bridge",
    fee: 3,
  },
  {
    id: nanoid(),
    src: IMG.TheChronicle,
    alt: "full color graphic",
    name: "The Chronicle",
    fee: 3,
  },
  {
    id: nanoid(),
    src: IMG.TheCrow,
    alt: "full color graphic",
    name: "The Crow",
    fee: 3,
  },
  {
    id: nanoid(),
    src: IMG.TheMask,
    alt: "full color graphic",
    name: "The Mask",
    fee: 3,
  },
  {
    id: nanoid(),
    src: IMG.Thunderbolt,
    alt: "full color graphic",
    name: "Thunderbolt",
    fee: 3,
  },
  {
    id: nanoid(),
    src: IMG.TrainSong,
    alt: "full color graphic",
    name: "Train Song",
    fee: 3,
  },
  {
    id: nanoid(),
    src: IMG.truthHurts,
    alt: "full color graphic",
    name: "truth Hurts",
    fee: 3,
  },
  {
    id: nanoid(),
    src: IMG.UFOInvasion,
    alt: "full color graphic",
    name: "UFO Invasion",
    fee: 3,
  },
  {
    id: nanoid(),
    src: IMG.WarPeace,
    alt: "full color graphic",
    name: "War Peace",
    fee: 3,
  },
  {
    id: nanoid(),
    src: IMG.WeaponFlag,
    alt: "full color graphic",
    name: "Weapon Flag",
    fee: 3,
  },
  {
    id: nanoid(),
    src: IMG.WildBison,
    alt: "full color graphic",
    name: "Wild Bison",
    fee: 3,
  },
  {
    id: nanoid(),
    src: IMG.WildLife,
    alt: "full color graphic",
    name: "Wild Life",
    fee: 3,
  },
  {
    id: nanoid(),
    src: IMG.YinYangCats,
    alt: "full color graphic",
    name: "YinYang Cats",
    fee: 3,
  },
  {
    id: nanoid(),
    src: IMG.ZebraBones,
    alt: "full color graphic",
    name: "Zebra Bones",
    fee: 3,
  },
];
export default Photos;

// {
//   id: nanoid(),
//   src: IMG.stufffffff,
//   alt: "eraseThis",
//   name: "eraseThis",
//   fee: 3,
// },
