import IMG from "./_photoIMPORTS";
import { nanoid } from "nanoid";

const Photos = [
  {
    id: nanoid(),
    src: IMG.Snake1,
    alt: "snake head graphic in color",
    name: "Snake 1",
    fee: 3,
  },
  {
    id: nanoid(),
    src: IMG.Snake2,
    alt: "snake head graphic in color",
    name: "Snake 2",
    fee: 3,
  },
  {
    id: nanoid(),
    src: IMG.Snake3,
    alt: "snake head graphic in color",
    name: "Snake 3",
    fee: 3,
  },
  {
    id: nanoid(),
    src: IMG.Snake4,
    alt: "snake head graphic in color",
    name: "Snake 4",
    fee: 3,
  },
  {
    id: nanoid(),
    src: IMG.Snake5,
    alt: "snake head graphic in color",
    name: "Snake 5",
    fee: 3,
  },
  {
    id: nanoid(),
    src: IMG.Snake6,
    alt: "snake head graphic in color",
    name: "Snake 6",
    fee: 3,
  },
  {
    id: nanoid(),
    src: IMG.Snake7,
    alt: "snake head graphic in color",
    name: "Snake 7",
    fee: 3,
  },
  {
    id: nanoid(),
    src: IMG.Snake8,
    alt: "snake head graphic in color",
    name: "Snake 8",
    fee: 3,
  },
  {
    id: nanoid(),
    src: IMG.Snake9,
    alt: "snake head graphic in color",
    name: "Snake 9",
    fee: 3,
  },
  {
    id: nanoid(),
    src: IMG.Snake10,
    alt: "snake head graphic in color",
    name: "Snake 10",
    fee: 3,
  },
  {
    id: nanoid(),
    src: IMG.Snake11,
    alt: "snake head graphic in color",
    name: "Snake 11",
    fee: 3,
  },
  {
    id: nanoid(),
    src: IMG.Snake12,
    alt: "snake head graphic in color",
    name: "Snake 12",
    fee: 3,
  },
  {
    id: nanoid(),
    src: IMG.Snake13,
    alt: "snake head graphic in color",
    name: "Snake 13",
    fee: 3,
  },
  {
    id: nanoid(),
    src: IMG.Snake14,
    alt: "snake head graphic in color",
    name: "Snake 14",
    fee: 3,
  },
  {
    id: nanoid(),
    src: IMG.Snake15,
    alt: "snake head graphic in color",
    name: "Snake 15",
    fee: 3,
  },
  {
    id: nanoid(),
    src: IMG.Snake16,
    alt: "snake head graphic in color",
    name: "Snake 16",
    fee: 3,
  },
  {
    id: nanoid(),
    src: IMG.Snake17,
    alt: "snake head graphic in color",
    name: "Snake 17",
    fee: 3,
  },
  {
    id: nanoid(),
    src: IMG.Snake18,
    alt: "snake head graphic in color",
    name: "Snake 18",
    fee: 3,
  },
  {
    id: nanoid(),
    src: IMG.Snake19,
    alt: "snake head graphic in color",
    name: "Snake 19",
    fee: 3,
  },
  {
    id: nanoid(),
    src: IMG.Snake20,
    alt: "snake head graphic in color",
    name: "Snake 20",
    fee: 3,
  },
  {
    id: nanoid(),
    src: IMG.Snake21,
    alt: "snake head graphic in color",
    name: "Snake 21",
    fee: 3,
  },
  {
    id: nanoid(),
    src: IMG.Snake22,
    alt: "snake head graphic in color",
    name: "Snake 22",
    fee: 3,
  },
  {
    id: nanoid(),
    src: IMG.Snake23,
    alt: "snake head graphic in color",
    name: "Snake 23",
    fee: 3,
  },
  {
    id: nanoid(),
    src: IMG.Snake24,
    alt: "snake head graphic in color",
    name: "Snake 24",
    fee: 3,
  },
  {
    id: nanoid(),
    src: IMG.Snake25,
    alt: "snake head graphic in color",
    name: "Snake 25",
    fee: 3,
  },
];
export default Photos;

// {
//   id: nanoid(),
//   src: IMG.stufffffff,
//   alt: "eraseThis",
//   name: "eraseThis",
//   fee: 3,
// },
