import IMG from "./__photoIMPORTS";
import { nanoid } from "nanoid";

const Photos = [
  {
    id: nanoid(),
    src: IMG.Monster,
    alt: "Monster",
    name: "Monster",
    fee: 3,
  },
  {
    id: nanoid(),
    src: IMG.Monster1,
    alt: "Monster 1",
    name: "Monster 1",
    fee: 3,
  },
  {
    id: nanoid(),
    src: IMG.Monster2,
    alt: "Monster 2",
    name: "Monster 2",
    fee: 3,
  },
  {
    id: nanoid(),
    src: IMG.Monster3,
    alt: "Monster 3",
    name: "Monster 3",
    fee: 3,
  },
  {
    id: nanoid(),
    src: IMG.Monster4,
    alt: "Monster 4",
    name: "Monster 4",
    fee: 3,
  },
  {
    id: nanoid(),
    src: IMG.Monster5,
    alt: "Monster 5",
    name: "Monster 5",
    fee: 3,
  },
  {
    id: nanoid(),
    src: IMG.Monster6,
    alt: "Monster 6",
    name: "Monster 6",
    fee: 3,
  },
  {
    id: nanoid(),
    src: IMG.Monster7,
    alt: "Monster 7",
    name: "Monster 7",
    fee: 3,
  },
  {
    id: nanoid(),
    src: IMG.Monster8,
    alt: "Monster 8",
    name: "Monster 8",
    fee: 3,
  },
  {
    id: nanoid(),
    src: IMG.Monster9,
    alt: "Monster 9",
    name: "Monster 9",
    fee: 3,
  },
  {
    id: nanoid(),
    src: IMG.Monster10,
    alt: "Monster 10",
    name: "Monster 10",
    fee: 3,
  },
  {
    id: nanoid(),
    src: IMG.Monster11,
    alt: "Monster 11",
    name: "Monster 11",
    fee: 3,
  },
  {
    id: nanoid(),
    src: IMG.Monster12,
    alt: "Monster 12",
    name: "Monster 12",
    fee: 3,
  },
  {
    id: nanoid(),
    src: IMG.Monster13,
    alt: "Monster 13",
    name: "Monster 13",
    fee: 3,
  },
  {
    id: nanoid(),
    src: IMG.Monster14,
    alt: "Monster 14",
    name: "Monster 14",
    fee: 3,
  },
  {
    id: nanoid(),
    src: IMG.Monster15,
    alt: "Monster 15",
    name: "Monster 15",
    fee: 3,
  },
  {
    id: nanoid(),
    src: IMG.Monster16,
    alt: "Monster 16",
    name: "Monster 16",
    fee: 3,
  },
  {
    id: nanoid(),
    src: IMG.Monster17,
    alt: "Monster 17",
    name: "Monster 17",
    fee: 3,
  },
  {
    id: nanoid(),
    src: IMG.Monster18,
    alt: "Monster 18",
    name: "Monster 18",
    fee: 3,
  },
  {
    id: nanoid(),
    src: IMG.Monster19,
    alt: "Monster 19",
    name: "Monster 19",
    fee: 3,
  },
  {
    id: nanoid(),
    src: IMG.Monster20,
    alt: "Monster 20",
    name: "Monster 20",
    fee: 3,
  },
  {
    id: nanoid(),
    src: IMG.Monster21,
    alt: "Monster 21",
    name: "Monster 21",
    fee: 3,
  },
  {
    id: nanoid(),
    src: IMG.Monster22,
    alt: "Monster 22",
    name: "Monster 22",
    fee: 3,
  },
  {
    id: nanoid(),
    src: IMG.Monster23,
    alt: "Monster 23",
    name: "Monster 23",
    fee: 3,
  },
  {
    id: nanoid(),
    src: IMG.Monster24,
    alt: "Monster 24",
    name: "Monster 24",
    fee: 3,
  },
  {
    id: nanoid(),
    src: IMG.Monster25,
    alt: "Monster 25",
    name: "Monster 25",
    fee: 3,
  },
  {
    id: nanoid(),
    src: IMG.Monster26,
    alt: "Monster 26",
    name: "Monster 26",
    fee: 3,
  },
  {
    id: nanoid(),
    src: IMG.Monster27,
    alt: "Monster 27",
    name: "Monster 27",
    fee: 3,
  },
  {
    id: nanoid(),
    src: IMG.Monster28,
    alt: "Monster 28",
    name: "Monster 28",
    fee: 3,
  },
  {
    id: nanoid(),
    src: IMG.Monster29,
    alt: "Monster 29",
    name: "Monster 29",
    fee: 3,
  },
  {
    id: nanoid(),
    src: IMG.Monster30,
    alt: "Monster 30",
    name: "Monster 30",
    fee: 3,
  },
  {
    id: nanoid(),
    src: IMG.Monster31,
    alt: "Monster 31",
    name: "Monster 31",
    fee: 3,
  },
  {
    id: nanoid(),
    src: IMG.Monster32,
    alt: "Monster 32",
    name: "Monster 32",
    fee: 3,
  },
  {
    id: nanoid(),
    src: IMG.Monster33,
    alt: "Monster 33",
    name: "Monster 33",
    fee: 3,
  },
  {
    id: nanoid(),
    src: IMG.Monster34,
    alt: "Monster 34",
    name: "Monster 34",
    fee: 3,
  },
  {
    id: nanoid(),
    src: IMG.Monster35,
    alt: "Monster 35",
    name: "Monster 35",
    fee: 3,
  },
  {
    id: nanoid(),
    src: IMG.Monster36,
    alt: "Monster 36",
    name: "Monster 36",
    fee: 3,
  },
  {
    id: nanoid(),
    src: IMG.Monster37,
    alt: "Monster 37",
    name: "Monster 37",
    fee: 3,
  },
  {
    id: nanoid(),
    src: IMG.Monster38,
    alt: "Monster 38",
    name: "Monster 38",
    fee: 3,
  },
  {
    id: nanoid(),
    src: IMG.Monster39,
    alt: "Monster 39",
    name: "Monster 39",
    fee: 3,
  },
  {
    id: nanoid(),
    src: IMG.Monster40,
    alt: "Monster 40",
    name: "Monster 40",
    fee: 3,
  },
  {
    id: nanoid(),
    src: IMG.Monster41,
    alt: "Monster 41",
    name: "Monster 41",
    fee: 3,
  },
  {
    id: nanoid(),
    src: IMG.Monster42,
    alt: "Monster 42",
    name: "Monster 42",
    fee: 3,
  },
  {
    id: nanoid(),
    src: IMG.Monster43,
    alt: "Monster 43",
    name: "Monster 43",
    fee: 3,
  },
  {
    id: nanoid(),
    src: IMG.Monster44,
    alt: "Monster 44",
    name: "Monster 44",
    fee: 3,
  },
  {
    id: nanoid(),
    src: IMG.Monster45,
    alt: "Monster 45",
    name: "Monster 45",
    fee: 3,
  },
  {
    id: nanoid(),
    src: IMG.Monster46,
    alt: "Monster 46",
    name: "Monster 46",
    fee: 3,
  },
  {
    id: nanoid(),
    src: IMG.Monster47,
    alt: "Monster 47",
    name: "Monster 47",
    fee: 3,
  },
  {
    id: nanoid(),
    src: IMG.Monster48,
    alt: "Monster 48",
    name: "Monster 48",
    fee: 3,
  },
  {
    id: nanoid(),
    src: IMG.Monster49,
    alt: "Monster 49",
    name: "Monster 49",
    fee: 3,
  },
  {
    id: nanoid(),
    src: IMG.Monster50,
    alt: "Monster 50",
    name: "Monster 50",
    fee: 3,
  },
];
export default Photos;

// {
//   id: nanoid(),
//   src: IMG.stufffffff,
//   alt: "eraseThis",
//   name: "eraseThis",
//   fee: 3,
// },
