import IMG from "./_photoIMPORTS";
import { nanoid } from "nanoid";

const Photos = [
  {
    id: nanoid(),
    src: IMG.ANTIVENOMPOP,
    alt: "ANTIVENOM POP",
    name: "ANTIVENOM POP",
    fee: 3,
  },
  {
    id: nanoid(),
    src: IMG.ANTMANENDGAME,
    alt: "ANTMAN ENDGAME",
    name: "ANTMAN ENDGAME",
    fee: 3,
  },
  {
    id: nanoid(),
    src: IMG.ARYASTARK,
    alt: "ARYASTARK",
    name: "ARYASTARK",
    fee: 3,
  },
  {
    id: nanoid(),
    src: IMG.BACKTOTHEFUTURE,
    alt: "BACK TO THE FUTURE",
    name: "BACK TO THE FUTURE",
    fee: 3,
  },
  {
    id: nanoid(),
    src: IMG.Battleforeternia,
    alt: "Battle for eternia",
    name: "Battle for eternia",
    fee: 3,
  },
  {
    id: nanoid(),
    src: IMG.BATMANYROBIN,
    alt: "BATMAN & ROBIN",
    name: "BATMAN & ROBIN",
    fee: 3,
  },
  {
    id: nanoid(),
    src: IMG.BezitaVader,
    alt: "Vader",
    name: "Vader",
    fee: 3,
  },
  {
    id: nanoid(),
    src: IMG.blackpanter01,
    alt: "black panther 1",
    name: "black panther 1",
    fee: 3,
  },
  {
    id: nanoid(),
    src: IMG.BlackTrooper,
    alt: "Black Trooper",
    name: "Black Trooper",
    fee: 3,
  },
  {
    id: nanoid(),
    src: IMG.BLACKWIDOWENDGAME,
    alt: "BLACK WIDOW ENDGAME",
    name: "BLACK WIDOW ENDGAME",
    fee: 3,
  },
  {
    id: nanoid(),
    src: IMG.BLACKW,
    alt: "BLACK WIDOW",
    name: "BLACK WIDOW",
    fee: 3,
  },
  {
    id: nanoid(),
    src: IMG.BRITNEY,
    alt: "BRITNEY",
    name: "BRITNEY",
    fee: 3,
  },
  {
    id: nanoid(),
    src: IMG.CAPITANAMERICA2,
    alt: "CAPTAIN AMERICA 2",
    name: "CAPTAIN AMERICA 2",
    fee: 3,
  },
  {
    id: nanoid(),
    src: IMG.CAPITANAMERICA3,
    alt: "CAPTAIN AMERICA 3",
    name: "CAPTAIN AMERICA 3",
    fee: 3,
  },
  {
    id: nanoid(),
    src: IMG.CAPITANAMARVEL,
    alt: "CAPTAIN MARVEL",
    name: "CAPTAIN MARVEL",
    fee: 3,
  },
  {
    id: nanoid(),
    src: IMG.CAPTAINAMERICA1STAVENGER,
    alt: "CAPTAIN AMERICA 1ST AVENGER",
    name: "CAPTAIN AMERICA 1ST AVENGER",
    fee: 3,
  },
  {
    id: nanoid(),
    src: IMG.CAPTAINENDGAMEV2,
    alt: "CAPTAIN ENDGAME V2",
    name: "CAPTAIN ENDGAME V2",
    fee: 3,
  },
  {
    id: nanoid(),
    src: IMG.CAPTAINENDGAME,
    alt: "CAPTAIN ENDGAME",
    name: "CAPTAIN ENDGAME",
    fee: 3,
  },
  {
    id: nanoid(),
    src: IMG.CAPTAIN1,
    alt: "CAPTAIN 1",
    name: "CAPTAIN 1",
    fee: 3,
  },
  {
    id: nanoid(),
    src: IMG.CasadepapelDalírun,
    alt: "Casa de papel Dalírun",
    name: "Casa de papel Dalírun",
    fee: 3,
  },
  {
    id: nanoid(),
    src: IMG.CasadepapelgrupoCartoon,
    alt: "Casa de papel group Cartoon",
    name: "Casa de papel group Cartoon",
    fee: 3,
  },
  {
    id: nanoid(),
    src: IMG.casadepapel,
    alt: "casa de papel",
    name: "casa de papel",
    fee: 3,
  },
  {
    id: nanoid(),
    src: IMG.CHEWBACCA,
    alt: "CHEWBACCA",
    name: "CHEWBACCA",
    fee: 3,
  },
  {
    id: nanoid(),
    src: IMG.chubaca,
    alt: "chubaca",
    name: "chubaca",
    fee: 3,
  },
  {
    id: nanoid(),
    src: IMG.DAENERYS1,
    alt: "DAENERYS 1",
    name: "DAENERYS 1",
    fee: 3,
  },
  {
    id: nanoid(),
    src: IMG.DAERAVILFUNKOVECTOR,
    alt: "DAERAVIL FUNKOVECTOR",
    name: "DAERAVIL FUNKOVECTOR",
    fee: 3,
  },
  {
    id: nanoid(),
    src: IMG.deadtina,
    alt: "dead tina",
    name: "dead tina",
    fee: 3,
  },
  {
    id: nanoid(),
    src: IMG.deadpool01,
    alt: "deadpool 01",
    name: "deadpool 01",
    fee: 3,
  },
  {
    id: nanoid(),
    src: IMG.DeadpoolMercenary,
    alt: "Deadpool Mercenary",
    name: "Deadpool Mercenary",
    fee: 3,
  },
  {
    id: nanoid(),
    src: IMG.DeadpoolTacos,
    alt: "Deadpool Tacos",
    name: "Deadpool Tacos",
    fee: 3,
  },
  {
    id: nanoid(),
    src: IMG.DEADPOOL,
    alt: "DEADPOOL",
    name: "DEADPOOL",
    fee: 3,
  },
  {
    id: nanoid(),
    src: IMG.Droids,
    alt: "Droids",
    name: "Droids",
    fee: 3,
  },
  {
    id: nanoid(),
    src: IMG.Dumbo2,
    alt: "Dumbo 2",
    name: "Dumbo 2",
    fee: 3,
  },
  {
    id: nanoid(),
    src: IMG.FLINTSTONES,
    alt: "FLINTSTONES",
    name: "FLINTSTONES",
    fee: 3,
  },
  {
    id: nanoid(),
    src: IMG.FLYINGDRAGON,
    alt: "FLYING DRAGON",
    name: "FLYING DRAGON",
    fee: 3,
  },
  {
    id: nanoid(),
    src: IMG.FORTNITE,
    alt: "FORTNITE",
    name: "FORTNITE",
    fee: 3,
  },
  {
    id: nanoid(),
    src: IMG.FreddyvsJason,
    alt: "Freddy vs Jason",
    name: "Freddy vs Jason",
    fee: 3,
  },
  {
    id: nanoid(),
    src: IMG.Freddy,
    alt: "Freddy",
    name: "Freddy",
    fee: 3,
  },
  {
    id: nanoid(),
    src: IMG.FUNKOIT,
    alt: "IT",
    name: "IT",
    fee: 3,
  },
  {
    id: nanoid(),
    src: IMG.funkovegeta,
    alt: "vegeta",
    name: "vegeta",
    fee: 3,
  },
  {
    id: nanoid(),
    src: IMG.GHOSTBUSTERS4,
    alt: "GHOSTBUSTERS 4",
    name: "GHOSTBUSTERS 4",
    fee: 3,
  },
  {
    id: nanoid(),
    src: IMG.GHOSTBUSTERS,
    alt: "GHOSTBUSTERS",
    name: "GHOSTBUSTERS",
    fee: 3,
  },
  {
    id: nanoid(),
    src: IMG.GROOT2,
    alt: "GROOT 2",
    name: "GROOT 2",
    fee: 3,
  },
  {
    id: nanoid(),
    src: IMG.GROOT,
    alt: "GROOT",
    name: "GROOT",
    fee: 3,
  },
  {
    id: nanoid(),
    src: IMG.HarleyQueen,
    alt: "Harley Queen",
    name: "Harley Queen",
    fee: 3,
  },
  {
    id: nanoid(),
    src: IMG.HarleyQueenB,
    alt: "Harley Queen B",
    name: "Harley Queen B",
    fee: 3,
  },
  {
    id: nanoid(),
    src: IMG.HARRYPOTTER2,
    alt: "HARRYPOTTER 2",
    name: "HARRYPOTTER 2",
    fee: 3,
  },
  {
    id: nanoid(),
    src: IMG.HARRYPOTTER1,
    alt: "HARRYPOTTER 1",
    name: "HARRYPOTTER 1",
    fee: 3,
  },
  {
    id: nanoid(),
    src: IMG.HEISENBERG,
    alt: "HEISENBERG",
    name: "HEISENBERG",
    fee: 3,
  },
  {
    id: nanoid(),
    src: IMG.HERMIONE,
    alt: "HERMIONE",
    name: "HERMIONE",
    fee: 3,
  },
  {
    id: nanoid(),
    src: IMG.ENDGAMEV2,
    alt: "ENDGAME V2",
    name: "ENDGAME V2",
    fee: 3,
  },
  {
    id: nanoid(),
    src: IMG.ENDGAME,
    alt: "ENDGAME",
    name: "ENDGAME",
    fee: 3,
  },
  {
    id: nanoid(),
    src: IMG.HULK,
    alt: "HULK",
    name: "HULK",
    fee: 3,
  },
  {
    id: nanoid(),
    src: IMG.IRONSPIDER,
    alt: "IRON SPIDER",
    name: "IRON SPIDER",
    fee: 3,
  },
  {
    id: nanoid(),
    src: IMG.IRONMANENDGAME,
    alt: "IRONMAN ENDGAME",
    name: "IRONMAN ENDGAME",
    fee: 3,
  },
  {
    id: nanoid(),
    src: IMG.It,
    alt: "It 2",
    name: "It 2",
    fee: 3,
  },
  {
    id: nanoid(),
    src: IMG.JIMIHENDRIX,
    alt: "JIMI HENDRIX",
    name: "JIMI HENDRIX",
    fee: 3,
  },
  {
    id: nanoid(),
    src: IMG.JOKER,
    alt: "JOKER",
    name: "JOKER",
    fee: 3,
  },
  {
    id: nanoid(),
    src: IMG.JURASICPOP,
    alt: "JURASIC POP",
    name: "JURASIC POP",
    fee: 3,
  },
  {
    id: nanoid(),
    src: IMG.JURASIC2,
    alt: "JURASIC 2",
    name: "JURASIC 2",
    fee: 3,
  },
  {
    id: nanoid(),
    src: IMG.kissfunko,
    alt: "kiss",
    name: "kiss",
    fee: 3,
  },
  {
    id: nanoid(),
    src: IMG.LOKISARMY,
    alt: "LOKIS ARMY",
    name: "LOKIS ARMY",
    fee: 3,
  },
  {
    id: nanoid(),
    src: IMG.MARTYSKATEBOARD,
    alt: "MARTY SKATEBOARD",
    name: "MARTY SKATEBOARD",
    fee: 3,
  },
  {
    id: nanoid(),
    src: IMG.MARTY,
    alt: "MARTY",
    name: "MARTY",
    fee: 3,
  },
  {
    id: nanoid(),
    src: IMG.MEGAMANFUNKO,
    alt: "MEGA MAN",
    name: "MEGA MAN",
    fee: 3,
  },
  {
    id: nanoid(),
    src: IMG.NIGHTKING2,
    alt: "NIGHT KING 2",
    name: "NIGHT KING 2",
    fee: 3,
  },
  {
    id: nanoid(),
    src: IMG.NIGHTKING3,
    alt: "NIGHT KING 3",
    name: "NIGHT KING 3",
    fee: 3,
  },
  {
    id: nanoid(),
    src: IMG.NIGHTKING,
    alt: "NIGHT KING",
    name: "NIGHT KING",
    fee: 3,
  },
  {
    id: nanoid(),
    src: IMG.PREDATOR,
    alt: "PREDATOR",
    name: "PREDATOR",
    fee: 3,
  },
  {
    id: nanoid(),
    src: IMG.REBELLIONEMPIRE,
    alt: "REBELLION EMPIRE",
    name: "REBELLION EMPIRE",
    fee: 3,
  },
  {
    id: nanoid(),
    src: IMG.ROCKSTEADY,
    alt: "ROCKSTEADY",
    name: "ROCKSTEADY",
    fee: 3,
  },
  {
    id: nanoid(),
    src: IMG.RONINENDGAME,
    alt: "RONIN ENDGAME",
    name: "RONIN ENDGAME",
    fee: 3,
  },
  {
    id: nanoid(),
    src: IMG.ScartTerry,
    alt: "Scary Terry",
    name: "Scary Terry",
    fee: 3,
  },
  {
    id: nanoid(),
    src: IMG.SIRENITA,
    alt: "SIREN",
    name: "SIREN",
    fee: 3,
  },
  {
    id: nanoid(),
    src: IMG.SKELETOR2,
    alt: "SKELETOR 2",
    name: "SKELETOR 2",
    fee: 3,
  },
  {
    id: nanoid(),
    src: IMG.SKELETORCONQUERGRAYSKULL,
    alt: "SKELETOR CONQUER GRAYSKULL",
    name: "SKELETOR CONQUER GRAYSKULL",
    fee: 3,
  },
  {
    id: nanoid(),
    src: IMG.SONIC,
    alt: "SONIC",
    name: "SONIC",
    fee: 3,
  },
  {
    id: nanoid(),
    src: IMG.SPIDERMAN2,
    alt: "SPIDERMAN 2",
    name: "SPIDERMAN 2",
    fee: 3,
  },
  {
    id: nanoid(),
    src: IMG.SPIDERMAN,
    alt: "SPIDERMAN",
    name: "SPIDERMAN",
    fee: 3,
  },
  {
    id: nanoid(),
    src: IMG.STANLEECOMPL,
    alt: "STAN LEE",
    name: "STAN LEE",
    fee: 3,
  },
  {
    id: nanoid(),
    src: IMG.STITCH,
    alt: "STITCH",
    name: "STITCH",
    fee: 3,
  },
  {
    id: nanoid(),
    src: IMG.STORMTROOPER,
    alt: "STORMTROOPER",
    name: "STORMTROOPER",
    fee: 3,
  },
  {
    id: nanoid(),
    src: IMG.SUPERMAN,
    alt: "SUPERMAN",
    name: "SUPERMAN",
    fee: 3,
  },
  {
    id: nanoid(),
    src: IMG.TARGARYEN,
    alt: "TARGARYEN",
    name: "TARGARYEN",
    fee: 3,
  },
  {
    id: nanoid(),
    src: IMG.THANOSENDGAMEV2,
    alt: "THANOS ENDGAME V2",
    name: "THANOS ENDGAME V2",
    fee: 3,
  },
  {
    id: nanoid(),
    src: IMG.THANOSENDGAME,
    alt: "THANOS ENDGAME",
    name: "THANOS ENDGAME",
    fee: 3,
  },
  {
    id: nanoid(),
    src: IMG.THANOS,
    alt: "THANOS",
    name: "THANOS",
    fee: 3,
  },
  {
    id: nanoid(),
    src: IMG.TheJoker,
    alt: "The Joker",
    name: "The Joker",
    fee: 3,
  },
  {
    id: nanoid(),
    src: IMG.THOR4,
    alt: "THOR 4",
    name: "THOR 4",
    fee: 3,
  },
  {
    id: nanoid(),
    src: IMG.THORENDGAME,
    alt: "THOR ENDGAME",
    name: "THOR ENDGAME",
    fee: 3,
  },
  {
    id: nanoid(),
    src: IMG.thor,
    alt: "thor",
    name: "thor",
    fee: 3,
  },
  {
    id: nanoid(),
    src: IMG.TMNT2,
    alt: "TMNT 2",
    name: "TMNT 2",
    fee: 3,
  },
  {
    id: nanoid(),
    src: IMG.Turtles,
    alt: "Turtles",
    name: "Turtles",
    fee: 3,
  },
  {
    id: nanoid(),
    src: IMG.VADERKENOBI,
    alt: "VADER KENOBI",
    name: "VADER KENOBI",
    fee: 3,
  },
  {
    id: nanoid(),
    src: IMG.VENOM2,
    alt: "VENOM 2",
    name: "VENOM 2",
    fee: 3,
  },
  {
    id: nanoid(),
    src: IMG.VENOM1,
    alt: "VENOM 1",
    name: "VENOM 1",
    fee: 3,
  },
  {
    id: nanoid(),
    src: IMG.WONDERWOMANRETRO,
    alt: "WONDER WOMAN RETRO",
    name: "WONDER WOMAN RETRO",
    fee: 3,
  },
  {
    id: nanoid(),
    src: IMG.wonderwomanfunko,
    alt: "wonder woman",
    name: "wonder woman",
    fee: 3,
  },
];
export default Photos;

// {
//   id: nanoid(),
//   src: IMG.stufffffff,
//   alt: "eraseThis",
//   name: "eraseThis",
//   fee: 3,
// },
