import IMG from "./photoIMPORTS";
import { nanoid } from "nanoid";

const Photos = [
  {
    id: nanoid(),
    src: IMG.Dog1,
    alt: "eraseThis",
    name: "Dog 1",
    fee: 3,
  },
  {
    id: nanoid(),
    src: IMG.Dog2,
    alt: "eraseThis",
    name: "Dog 2",
    fee: 3,
  },
  {
    id: nanoid(),
    src: IMG.Dog3,
    alt: "eraseThis",
    name: "Dog 3",
    fee: 3,
  },
  {
    id: nanoid(),
    src: IMG.Dog4,
    alt: "eraseThis",
    name: "Dog 4",
    fee: 3,
  },
  {
    id: nanoid(),
    src: IMG.Dog5,
    alt: "eraseThis",
    name: "Dog 5",
    fee: 3,
  },
  {
    id: nanoid(),
    src: IMG.Dog6,
    alt: "eraseThis",
    name: "Dog 6",
    fee: 3,
  },
  {
    id: nanoid(),
    src: IMG.Dog7,
    alt: "eraseThis",
    name: "Dog 7",
    fee: 3,
  },
  {
    id: nanoid(),
    src: IMG.Dog8,
    alt: "eraseThis",
    name: "Dog 8",
    fee: 3,
  },
  {
    id: nanoid(),
    src: IMG.Dog9,
    alt: "eraseThis",
    name: "Dog 9",
    fee: 3,
  },
  {
    id: nanoid(),
    src: IMG.Dog10,
    alt: "eraseThis",
    name: "Dog 10",
    fee: 3,
  },
  {
    id: nanoid(),
    src: IMG.Dog11,
    alt: "eraseThis",
    name: "Dog 11",
    fee: 3,
  },
  {
    id: nanoid(),
    src: IMG.Dog12,
    alt: "eraseThis",
    name: "Dog 12",
    fee: 3,
  },
  {
    id: nanoid(),
    src: IMG.Dog13,
    alt: "eraseThis",
    name: "Dog 13",
    fee: 3,
  },
  {
    id: nanoid(),
    src: IMG.Dog14,
    alt: "eraseThis",
    name: "Dog 14",
    fee: 3,
  },
  {
    id: nanoid(),
    src: IMG.Dog15,
    alt: "eraseThis",
    name: "Dog 15",
    fee: 3,
  },
  {
    id: nanoid(),
    src: IMG.Dog16,
    alt: "eraseThis",
    name: "Dog 16",
    fee: 3,
  },
  {
    id: nanoid(),
    src: IMG.Dog17,
    alt: "eraseThis",
    name: "Dog 17",
    fee: 3,
  },
  {
    id: nanoid(),
    src: IMG.Dog18,
    alt: "eraseThis",
    name: "Dog 18",
    fee: 3,
  },
  {
    id: nanoid(),
    src: IMG.Dog19,
    alt: "eraseThis",
    name: "Dog 19",
    fee: 3,
  },
  {
    id: nanoid(),
    src: IMG.Dog20,
    alt: "eraseThis",
    name: "Dog 20",
    fee: 3,
  },
  {
    id: nanoid(),
    src: IMG.Dog21,
    alt: "eraseThis",
    name: "Dog 21",
    fee: 3,
  },
  {
    id: nanoid(),
    src: IMG.Dog22,
    alt: "eraseThis",
    name: "Dog 22",
    fee: 3,
  },
  {
    id: nanoid(),
    src: IMG.Dog23,
    alt: "eraseThis",
    name: "Dog 23",
    fee: 3,
  },
  {
    id: nanoid(),
    src: IMG.Dog24,
    alt: "eraseThis",
    name: "Dog 24",
    fee: 3,
  },
  {
    id: nanoid(),
    src: IMG.Dog25,
    alt: "eraseThis",
    name: "Dog 25",
    fee: 3,
  },
];
export default Photos;

// {
//   id: nanoid(),
//   src: IMG.stufffffff,
//   alt: "eraseThis",
//   name: "eraseThis",
//   fee: 3,
// },
