const IMG = {

//charicatureGraphics

  AstronautIceCream: require("./images/charicatureGraphics/Astronaut Ice Cream.png"),
  BarberSkater: require("./images/charicatureGraphics/Barber Skater.png"),
  BasketBallBombers: require("./images/charicatureGraphics/Basketball Bombers.png"),
  Bomber: require("./images/charicatureGraphics/Bomber.png"),
  BoomboxRobot: require("./images/charicatureGraphics/Boombox Robot.png"),
  BoxingChampion: require("./images/charicatureGraphics/Boxing Champion.png"),
  BrickGamers: require("./images/charicatureGraphics/Brick Gamers.png"),
  BrooklynBaseball: require("./images/charicatureGraphics/Brooklyn Baseball.png"),
  BurgerBastard: require("./images/charicatureGraphics/Burger Bastard.png"),
  BurgerScooter: require("./images/charicatureGraphics/Burger Scooter.png"),
  CaferacerHelmet: require("./images/charicatureGraphics/Caferacer Helmet.png"),
  CashRules: require("./images/charicatureGraphics/Cash Rules.png"),
  ChainsawKiller: require("./images/charicatureGraphics/Chainsaw KIller.png"),
  ChocolateSquad: require("./images/charicatureGraphics/Chocolate Squad.png"),
  CigaretteKiller: require("./images/charicatureGraphics/Cigarette Killer.png"),
  ClassicCameraman: require("./images/charicatureGraphics/Classic Cameraman.png"),
  Diver: require("./images/charicatureGraphics/Diver.png"),
  DonutSkater: require("./images/charicatureGraphics/Donut Skater.png"),
  DoubleStickMan: require("./images/charicatureGraphics/Double Stick Man.png"),
  Fighter: require("./images/charicatureGraphics/Fighter.png"),
  FootballKing: require("./images/charicatureGraphics/Football King.png"),
  FootballPlayer: require("./images/charicatureGraphics/Football Player.png"),
  FrankRace: require("./images/charicatureGraphics/Frank Race.png"),
  GameKid: require("./images/charicatureGraphics/Game Kid.png"),
  GameMachine: require("./images/charicatureGraphics/Game Machine.png"),
  GameOn1: require("./images/charicatureGraphics/Game On 1.png"),
  GameOn2: require("./images/charicatureGraphics/Game On 2.png"),
  GamersKiller: require("./images/charicatureGraphics/Gamers Killer.png"),
  GiftFromOuterSpace: require("./images/charicatureGraphics/Gift From Outer Space.png"),
  Golfer: require("./images/charicatureGraphics/Golfer.png"),
  GramophoneHead: require("./images/charicatureGraphics/Gramophone Head.png"),
  GrenadeBrain: require("./images/charicatureGraphics/Grenade Brain.png"),
  GrenadeHeart: require("./images/charicatureGraphics/Grenade Heart.png"),
  GrenadeRibcage: require("./images/charicatureGraphics/Grenade Ribcage.png"),
  Grenade: require("./images/charicatureGraphics/Grenade.png"),
  HeartToKill: require("./images/charicatureGraphics/Heart To Kill.png"),
  Hello: require("./images/charicatureGraphics/Hello.png"),
  ILikeDonut: require("./images/charicatureGraphics/I Like Donut.png"),
  ILoveBurger: require("./images/charicatureGraphics/I Love Burger.png"),
  IceCreamNinja: require("./images/charicatureGraphics/Ice Cream Ninja.png"),
  IceCreamTruck: require("./images/charicatureGraphics/Ice Cream Truck.png"),
  KillerMinibike: require("./images/charicatureGraphics/Killer Minibike.png"),
  KillerSkater: require("./images/charicatureGraphics/Killer Skater.png"),
  LetsPaint: require("./images/charicatureGraphics/Let's Paint.png"),
  LetsPlay: require("./images/charicatureGraphics/Let's Play.png"),
  LetsPlay2: require("./images/charicatureGraphics/Let's Play 2.png"),
  LightBoy: require("./images/charicatureGraphics/Light Boy.png"),
  MicrophoneKing: require("./images/charicatureGraphics/Microphone King.png"),
  MoneyTakers: require("./images/charicatureGraphics/Money Takers.png"),
  Money: require("./images/charicatureGraphics/Money.png"),
  MrCoffee: require("./images/charicatureGraphics/Mr Coffee.png"),
  MummyRace: require("./images/charicatureGraphics/Mummy Race.png"),
  Peace: require("./images/charicatureGraphics/Peace.png"),
  Pilot: require("./images/charicatureGraphics/Pilot.png"),
  PizzaBeard: require("./images/charicatureGraphics/Pizza Beard.png"),
  PizzaGangster: require("./images/charicatureGraphics/Pizza Gangster.png"),
  PizzaSkater: require("./images/charicatureGraphics/Pizza Skater.png"),
  PlayerHead1: require("./images/charicatureGraphics/Player Head 1.png"),
  PlayerHead2: require("./images/charicatureGraphics/Player Head 2.png"),
  PlayerSkater: require("./images/charicatureGraphics/Player Skater.png"),
  Polaroid: require("./images/charicatureGraphics/Polaroid.png"),
  Racer: require("./images/charicatureGraphics/Racer.png"),
  RamenStyle: require("./images/charicatureGraphics/Ramen Style.png"),
  RobotBoombox: require("./images/charicatureGraphics/Robot Boombox.png"),
  RubixKiller: require("./images/charicatureGraphics/Rubix Killer.png"),
  Sailor: require("./images/charicatureGraphics/Sailor.png"),
  SamuraiRider: require("./images/charicatureGraphics/Samurai Rider.png"),
  Samurai: require("./images/charicatureGraphics/Samurai.png"),
  Savage: require("./images/charicatureGraphics/Savage.png"),
  ScooterSkater: require("./images/charicatureGraphics/Scooter Skater.png"),
  Shooter: require("./images/charicatureGraphics/Shooter.png"),
  SkateBastard: require("./images/charicatureGraphics/Skate Bastard.png"),
  SkaterBomb: require("./images/charicatureGraphics/Skater Bomb.png"),
  Skatespace: require("./images/charicatureGraphics/Skatespace.png"),
  Soldier: require("./images/charicatureGraphics/Soldier.png"),
  SpaceBike: require("./images/charicatureGraphics/Space Bike.png"),
  SpaceJump: require("./images/charicatureGraphics/Space Jump.png"),
  SpaceRacer: require("./images/charicatureGraphics/Space Racer.png"),
  SpaceSlider: require("./images/charicatureGraphics/Space Slider.png"),
  StayFresh: require("./images/charicatureGraphics/Stay Fresh.png"),
  SteampunkHeart: require("./images/charicatureGraphics/Steampunk Heart.png"),
  SteampunkOwl: require("./images/charicatureGraphics/Steampunk Owl.png"),
  SteampunkRibcage: require("./images/charicatureGraphics/Steampunk Ribcage.png"),
  SteampunkTRex: require("./images/charicatureGraphics/Steampunk T Rex.png"),
  StreetBasketball: require("./images/charicatureGraphics/Street Basketball.png"),
  StreetBeetle: require("./images/charicatureGraphics/Street Beetle.png"),
  StreetBomber: require("./images/charicatureGraphics/Street Bomber.png"),
  StreetGamers: require("./images/charicatureGraphics/Street Gamers.png"),
  StreetKing: require("./images/charicatureGraphics/Street King.png"),
  StreetSoccer: require("./images/charicatureGraphics/Street Soccer.png"),
  Surprise: require("./images/charicatureGraphics/Surprise.png"),
  Taco: require("./images/charicatureGraphics/Taco.png"),
  ToasterMonster: require("./images/charicatureGraphics/Toaster Monster.png"),
  TrainKiller: require("./images/charicatureGraphics/Train Killer.png"),
  Vandalism: require("./images/charicatureGraphics/Vandalism.png"),
  Viking: require("./images/charicatureGraphics/Viking.png"),
  VintageRobot: require("./images/charicatureGraphics/Vintage Robot.png"),
  WarTank: require("./images/charicatureGraphics/War Tank.png"),
  YourTimeWillCome: require("./images/charicatureGraphics/Your Time Will Come.png"),
  ZombieCassette: require("./images/charicatureGraphics/Zombie Cassette.png"),
  
  //pocketGraphics
  
  Abduction: require("./images/pocketGraphics/alien abduction pocketSource.png"),
  AngryWaves: require("./images/pocketGraphics/Angry waves pocket.png"),
  Aquarium: require("./images/pocketGraphics/aquarium pocket.png"),
  BeAwesome: require("./images/pocketGraphics/be awesome pocketSource.png"),
  Cactus: require("./images/pocketGraphics/cactus pocket.png"),
  CatSkeleton: require("./images/pocketGraphics/cat skeleton pocketSource.png"),
  ChildMoon: require("./images/pocketGraphics/Child on moon pocket.png"),
  CourageDog: require("./images/pocketGraphics/courage dog pocketSource.png"),
  CuteCat: require("./images/pocketGraphics/cute cat pocket.png"),
  Dollar: require("./images/pocketGraphics/Dollar pocketSource.png"),
  FallingCat: require("./images/pocketGraphics/falling cat pocketSource.png"),
  Fish: require("./images/pocketGraphics/fish pocketSource.png"),
  Ghost: require("./images/pocketGraphics/Ghost pocket.png"),
  GoldenCoins: require("./images/pocketGraphics/Golden coins pocket.png"),
  Heart: require("./images/pocketGraphics/Heart pocket.png"),
  Hotdog: require("./images/pocketGraphics/Hotdog-pocket.png"),
  Husky: require("./images/pocketGraphics/husky pocket.png"),
  Icecream: require("./images/pocketGraphics/icecream pocket.png"),
  Knife: require("./images/pocketGraphics/knife pocket.png"),
  LoveAtFirstBite: require("./images/pocketGraphics/Love at first bite.png"),
  Minion: require("./images/pocketGraphics/minion pocketSource.png"),
  MonkeyButt: require("./images/pocketGraphics/monkey butt pocketSource.png"),
  Octopus: require("./images/pocketGraphics/Octopus pocket.png"),
  Palm: require("./images/pocketGraphics/palm pocketSource.png"),
  Panda: require("./images/pocketGraphics/Panda pocketSource.png"),
  PinupGirl: require("./images/pocketGraphics/Pin up girl pocket.png"),
  PinkPanther: require("./images/pocketGraphics/pink panter pocketSource.png"),
  Popcorn: require("./images/pocketGraphics/Popcorn pocket.png"),
  Pug: require("./images/pocketGraphics/pug pocketSource.png"),
  SeaStar: require("./images/pocketGraphics/Seastarspocket.png"),
  Sun: require("./images/pocketGraphics/Sun umbrella pocket.png"),
  Swimming: require("./images/pocketGraphics/Swimming pocketSource.png"),
  TropicalFruit: require("./images/pocketGraphics/Tropical fruits pocket.png"),
  WateringFlowers: require("./images/pocketGraphics/Watering flowers.png"),
  ZombieHands: require("./images/pocketGraphics/Zombie hands pocket.png"),
  
  // popArtGraphics
  
  AlbertKisstein: require("./images/PopArtGraphics/ALBERT KISSTEIN low.png"),
  AmericanPsycho2: require("./images/PopArtGraphics/AMERICAN PSYCHO 2 low.png"),
  AmericanPsycho: require("./images/PopArtGraphics/AMERICAN PSYCHO low.png"),
  BenjaminDranklin: require("./images/PopArtGraphics/Benjamin Dranklin low.png"),
  CharimanMeow: require("./images/PopArtGraphics/CHAIRMAN MEOW low.png"),
  Chef: require("./images/PopArtGraphics/CHEF low.png"),
  Covfefe: require("./images/PopArtGraphics/COVFEFE.png"),
  Dope: require("./images/PopArtGraphics/DOPE.png"),
  Dream: require("./images/PopArtGraphics/DREAM low.png"),
  GotMLK: require("./images/PopArtGraphics/GOT MLK low.png"),
  Heilstein: require("./images/PopArtGraphics/HEILSTEIN low.png"),
  HoHoHoChiMinh: require("./images/PopArtGraphics/ho ho ho chi minh.png"),
  ICantBreathe: require("./images/PopArtGraphics/I CANT BREATHE.png"),
  JusticeForGeorgeFloyd: require("./images/PopArtGraphics/justice for george floyd low.png"),
  LincolnUnknown: require("./images/PopArtGraphics/lincoln unknown low.png"),
  MakeAmericaGreyAgain: require("./images/PopArtGraphics/MAKE AMERICA GREY AGAIN.png"),
  MeowTseTung: require("./images/PopArtGraphics/Meow Tse Tung.png"),
  Merica: require("./images/PopArtGraphics/MERICA low.png"),
  MericaTrump: require("./images/PopArtGraphics/MERICA TRUMP low.png"),
  NoRacism: require("./images/PopArtGraphics/NO RACISM.png"),
  Putintin: require("./images/PopArtGraphics/PUTINTIN.png"),
  RocketBoy: require("./images/PopArtGraphics/ROCKETBOY low.png"),
  RocketMan: require("./images/PopArtGraphics/ROCKETMAN low.png"),
  StraigtOuttaPyongYang: require("./images/PopArtGraphics/STRAIGHT OUTTA PYONGYANG.png"),
  SylvesterStalin: require("./images/PopArtGraphics/SYLVESTER STALIN.png"),
  TheFuhrer: require("./images/PopArtGraphics/THE FUHRER.png"),
  Trump: require("./images/PopArtGraphics/TRUMP low.png"),
  UnderControl: require("./images/PopArtGraphics/UNDER CONTROL.png"),
  VivaLaEvolucion: require("./images/PopArtGraphics/viva la evolucion low.png"),
  WeCanDoIt: require("./images/PopArtGraphics/WE CAN DO IT.png"),

};

export default IMG;








