import IMG from "./photoIMPORTS";
import { nanoid } from "nanoid";

const Photos = [
  {
    id: nanoid(),
    src: IMG.Abduction,
    alt: "a cat being abducted by aliens in color",
    name: "Abduction",
    fee: 3,
  },
  {
    id: nanoid(),
    src: IMG.AngryWaves,
    alt: "a tug boat in stormy waves in color",
    name: "Angry Waves",
    fee: 3,
  },
  {
    id: nanoid(),
    src: IMG.Aquarium,
    alt: "cats staring a fish in a pocket in color",
    name: "Aquarium",
    fee: 3,
  },
  {
    id: nanoid(),
    src: IMG.BeAwesome,
    alt: "school supplies in a pokcet in color",
    name: "Be Awesome",
    fee: 3,
  },
  {
    id: nanoid(),
    src: IMG.Cactus,
    alt: "a cactus in a pocket in color",
    name: "Cactus",
    fee: 3,
  },
  {
    id: nanoid(),
    src: IMG.stufffffff,
    alt: "eraseThis",
    name: "eraseThis",
    fee: 3,
  },
  {
    id: nanoid(),
    src: IMG.stufffffff,
    alt: "eraseThis",
    name: "eraseThis",
    fee: 3,
  },
  {
    id: nanoid(),
    src: IMG.stufffffff,
    alt: "eraseThis",
    name: "eraseThis",
    fee: 3,
  },
  {
    id: nanoid(),
    src: IMG.stufffffff,
    alt: "eraseThis",
    name: "eraseThis",
    fee: 3,
  },
  {
    id: nanoid(),
    src: IMG.stufffffff,
    alt: "eraseThis",
    name: "eraseThis",
    fee: 3,
  },
  {
    id: nanoid(),
    src: IMG.stufffffff,
    alt: "eraseThis",
    name: "eraseThis",
    fee: 3,
  },
  {
    id: nanoid(),
    src: IMG.stufffffff,
    alt: "eraseThis",
    name: "eraseThis",
    fee: 3,
  },
  {
    id: nanoid(),
    src: IMG.stufffffff,
    alt: "eraseThis",
    name: "eraseThis",
    fee: 3,
  },
  {
    id: nanoid(),
    src: IMG.stufffffff,
    alt: "eraseThis",
    name: "eraseThis",
    fee: 3,
  },
  {
    id: nanoid(),
    src: IMG.stufffffff,
    alt: "eraseThis",
    name: "eraseThis",
    fee: 3,
  },
  {
    id: nanoid(),
    src: IMG.stufffffff,
    alt: "eraseThis",
    name: "eraseThis",
    fee: 3,
  },
  {
    id: nanoid(),
    src: IMG.stufffffff,
    alt: "eraseThis",
    name: "eraseThis",
    fee: 3,
  },
  {
    id: nanoid(),
    src: IMG.stufffffff,
    alt: "eraseThis",
    name: "eraseThis",
    fee: 3,
  },
  {
    id: nanoid(),
    src: IMG.stufffffff,
    alt: "eraseThis",
    name: "eraseThis",
    fee: 3,
  },
  {
    id: nanoid(),
    src: IMG.stufffffff,
    alt: "eraseThis",
    name: "eraseThis",
    fee: 3,
  },
  {
    id: nanoid(),
    src: IMG.stufffffff,
    alt: "eraseThis",
    name: "eraseThis",
    fee: 3,
  },
  {
    id: nanoid(),
    src: IMG.stufffffff,
    alt: "eraseThis",
    name: "eraseThis",
    fee: 3,
  },
  {
    id: nanoid(),
    src: IMG.stufffffff,
    alt: "eraseThis",
    name: "eraseThis",
    fee: 3,
  },
];
export default Photos;

// {
//   id: nanoid(),
//   src: IMG.stufffffff,
//   alt: "eraseThis",
//   name: "eraseThis",
//   fee: 3,
// },



// CatSkeleton: require("./images/pocketGraphics/cat skeleton pocketSource.png"),
// ChildMoon: require("./images/pocketGraphics/Child on moon pocket.png"),
// CourageDog: require("./images/pocketGraphics/courage dog pocketSource.png"),
// CuteCat: require("./images/pocketGraphics/cute cat pocket.png"),
// Dollar: require("./images/pocketGraphics/Dollar pocketSource.png"),
// FallingCat: require("./images/pocketGraphics/falling cat pocketSource.png"),
// Fish: require("./images/pocketGraphics/fish pocketSource.png"),
// Ghost: require("./images/pocketGraphics/Ghost pocket.png"),
// GoldenCoins: require("./images/pocketGraphics/Golden coins pocket.png"),
// Heart: require("./images/pocketGraphics/Heart pocket.png"),
// Hotdog: require("./images/pocketGraphics/Hotdog-pocket.png"),
// Husky: require("./images/pocketGraphics/husky pocket.png"),
// Icecream: require("./images/pocketGraphics/icecream pocket.png"),
// Knife: require("./images/pocketGraphics/knife pocket.png"),
// LoveAtFirstBite: require("./images/pocketGraphics/Love at first bite.png"),
// Minion: require("./images/pocketGraphics/minion pocketSource.png"),
// MonkeyButt: require("./images/pocketGraphics/monkey butt pocketSource.png"),
// Octopus: require("./images/pocketGraphics/Octopus pocket.png"),
// Palm: require("./images/pocketGraphics/palm pocketSource.png"),
// Panda: require("./images/pocketGraphics/Panda pocketSource.png"),
// PinupGirl: require("./images/pocketGraphics/Pin up girl pocket.png"),
// PinkPanther: require("./images/pocketGraphics/pink panter pocketSource.png"),
// Popcorn: require("./images/pocketGraphics/Popcorn pocket.png"),
// Pug: require("./images/pocketGraphics/pug pocketSource.png"),
// SeaStar: require("./images/pocketGraphics/Seastarspocket.png"),
// Sun: require("./images/pocketGraphics/Sun umbrella pocket.png"),
// Swimming: require("./images/pocketGraphics/Swimming pocketSource.png"),
// TropicalFruit: require("./images/pocketGraphics/Tropical fruits pocket.png"),
// WateringFlowers: require("./images/pocketGraphics/Watering flowers.png"),
// ZombieHands: require("./images/pocketGraphics/Zombie hands pocket.png"),