const IMG = {

//charicatureGraphics

  AstronautIceCream: require("./images/charicatureGraphics/Astronaut Ice Cream.png"),
  BarberSkater: require("./images/charicatureGraphics/Barber Skater.png"),
  BasketBallBombers: require("./images/charicatureGraphics/Basketball Bombers.png"),
  Bomber: require("./images/charicatureGraphics/Bomber.png"),
  BoomboxRobot: require("./images/charicatureGraphics/Boombox Robot.png"),
  BoxingChampion: require("./images/charicatureGraphics/Boxing Champion.png"),
  BrickGamers: require("./images/charicatureGraphics/Brick Gamers.png"),
  BrooklynBaseball: require("./images/charicatureGraphics/Brooklyn Baseball.png"),
  BurgerBastard: require("./images/charicatureGraphics/Burger Bastard.png"),
  BurgerScooter: require("./images/charicatureGraphics/Burger Scooter.png"),
  CaferacerHelmet: require("./images/charicatureGraphics/Caferacer Helmet.png"),
  CashRules: require("./images/charicatureGraphics/Cash Rules.png"),
  ChainsawKiller: require("./images/charicatureGraphics/Chainsaw KIller.png"),
  ChocolateSquad: require("./images/charicatureGraphics/Chocolate Squad.png"),
  CigaretteKiller: require("./images/charicatureGraphics/Cigarette Killer.png"),
  ClassicCameraman: require("./images/charicatureGraphics/Classic Cameraman.png"),
  Diver: require("./images/charicatureGraphics/Diver.png"),
  DonutSkater: require("./images/charicatureGraphics/Donut Skater.png"),
  DoubleStickMan: require("./images/charicatureGraphics/Double Stick Man.png"),
  Fighter: require("./images/charicatureGraphics/Fighter.png"),
  FootballKing: require("./images/charicatureGraphics/Football King.png"),
  FootballPlayer: require("./images/charicatureGraphics/Football Player.png"),
  FrankRace: require("./images/charicatureGraphics/Frank Race.png"),
  GameKid: require("./images/charicatureGraphics/Game Kid.png"),
  GameMachine: require("./images/charicatureGraphics/Game Machine.png"),
  GameOn1: require("./images/charicatureGraphics/Game On 1.png"),
  GameOn2: require("./images/charicatureGraphics/Game On 2.png"),
  GamersKiller: require("./images/charicatureGraphics/Gamers Killer.png"),
  GiftFromOuterSpace: require("./images/charicatureGraphics/Gift From Outer Space.png"),
  Golfer: require("./images/charicatureGraphics/Golfer.png"),
  GramophoneHead: require("./images/charicatureGraphics/Gramophone Head.png"),
  GrenadeBrain: require("./images/charicatureGraphics/Grenade Brain.png"),
  GrenadeHeart: require("./images/charicatureGraphics/Grenade Heart.png"),
  GrenadeRibcage: require("./images/charicatureGraphics/Grenade Ribcage.png"),
  Grenade: require("./images/charicatureGraphics/Grenade.png"),
  HeartToKill: require("./images/charicatureGraphics/Heart To Kill.png"),
  Hello: require("./images/charicatureGraphics/Hello.png"),
  ILikeDonut: require("./images/charicatureGraphics/I Like Donut.png"),
  ILoveBurger: require("./images/charicatureGraphics/I Love Burger.png"),
  IceCreamNinja: require("./images/charicatureGraphics/Ice Cream Ninja.png"),
  IceCreamTruck: require("./images/charicatureGraphics/Ice Cream Truck.png"),
  KillerMinibike: require("./images/charicatureGraphics/Killer Minibike.png"),
  KillerSkater: require("./images/charicatureGraphics/Killer Skater.png"),
  LetsPaint: require("./images/charicatureGraphics/Let's Paint.png"),
  LetsPlay: require("./images/charicatureGraphics/Let's Play.png"),
  LetsPlay2: require("./images/charicatureGraphics/Let's Play 2.png"),
  LightBoy: require("./images/charicatureGraphics/Light Boy.png"),
  MicrophoneKing: require("./images/charicatureGraphics/Microphone King.png"),
  MoneyTakers: require("./images/charicatureGraphics/Money Takers.png"),
  Money: require("./images/charicatureGraphics/Money.png"),
  MrCoffee: require("./images/charicatureGraphics/Mr Coffee.png"),
  MummyRace: require("./images/charicatureGraphics/Mummy Race.png"),
  PeaceChar: require("./images/charicatureGraphics/Peace.png"),
  Pilot: require("./images/charicatureGraphics/Pilot.png"),
  PizzaBeard: require("./images/charicatureGraphics/Pizza Beard.png"),
  PizzaGangster: require("./images/charicatureGraphics/Pizza Gangster.png"),
  PizzaSkater: require("./images/charicatureGraphics/Pizza Skater.png"),
  PlayerHead1: require("./images/charicatureGraphics/Player Head 1.png"),
  PlayerHead2: require("./images/charicatureGraphics/Player Head 2.png"),
  PlayerSkater: require("./images/charicatureGraphics/Player Skater.png"),
  Polaroid: require("./images/charicatureGraphics/Polaroid.png"),
  Racer: require("./images/charicatureGraphics/Racer.png"),
  RamenStyle: require("./images/charicatureGraphics/Ramen Style.png"),
  RobotBoombox: require("./images/charicatureGraphics/Robot Boombox.png"),
  RubixKiller: require("./images/charicatureGraphics/Rubix Killer.png"),
  Sailor: require("./images/charicatureGraphics/Sailor.png"),
  SamuraiRider: require("./images/charicatureGraphics/Samurai Rider.png"),
  Samurai: require("./images/charicatureGraphics/Samurai.png"),
  Savage: require("./images/charicatureGraphics/Savage.png"),
  ScooterSkater: require("./images/charicatureGraphics/Scooter Skater.png"),
  Shooter: require("./images/charicatureGraphics/Shooter.png"),
  SkateBastard: require("./images/charicatureGraphics/Skate Bastard.png"),
  SkaterBomb: require("./images/charicatureGraphics/Skater Bomb.png"),
  Skatespace: require("./images/charicatureGraphics/Skatespace.png"),
  Soldier: require("./images/charicatureGraphics/Soldier.png"),
  SpaceBike: require("./images/charicatureGraphics/Space Bike.png"),
  SpaceJump: require("./images/charicatureGraphics/Space Jump.png"),
  SpaceRacer: require("./images/charicatureGraphics/Space Racer.png"),
  SpaceSlider: require("./images/charicatureGraphics/Space Slider.png"),
  StayFresh: require("./images/charicatureGraphics/Stay Fresh.png"),
  SteampunkHeart: require("./images/charicatureGraphics/Steampunk Heart.png"),
  SteampunkOwl: require("./images/charicatureGraphics/Steampunk Owl.png"),
  SteampunkRibcage: require("./images/charicatureGraphics/Steampunk Ribcage.png"),
  SteampunkTRex: require("./images/charicatureGraphics/Steampunk T Rex.png"),
  StreetBasketball: require("./images/charicatureGraphics/Street Basketball.png"),
  StreetBeetle: require("./images/charicatureGraphics/Street Beetle.png"),
  StreetBomber: require("./images/charicatureGraphics/Street Bomber.png"),
  StreetGamers: require("./images/charicatureGraphics/Street Gamers.png"),
  StreetKing: require("./images/charicatureGraphics/Street King.png"),
  StreetSoccer: require("./images/charicatureGraphics/Street Soccer.png"),
  Surprise: require("./images/charicatureGraphics/Surprise.png"),
  Taco: require("./images/charicatureGraphics/Taco.png"),
  ToasterMonster: require("./images/charicatureGraphics/Toaster Monster.png"),
  TrainKiller: require("./images/charicatureGraphics/Train Killer.png"),
  Vandalism: require("./images/charicatureGraphics/Vandalism.png"),
  Viking: require("./images/charicatureGraphics/Viking.png"),
  VintageRobot: require("./images/charicatureGraphics/Vintage Robot.png"),
  WarTank: require("./images/charicatureGraphics/War Tank.png"),
  YourTimeWillCome: require("./images/charicatureGraphics/Your Time Will Come.png"),
  ZombieCassette: require("./images/charicatureGraphics/Zombie Cassette.png"),
  
  //pocketGraphics
  
  Abduction: require("./images/pocketGraphics/alien abduction pocketSource.png"),
  AngryWaves: require("./images/pocketGraphics/Angry waves pocket.png"),
  Aquarium: require("./images/pocketGraphics/aquarium pocket.png"),
  BeAwesome: require("./images/pocketGraphics/be awesome pocketSource.png"),
  Cactus: require("./images/pocketGraphics/cactus pocket.png"),
  CatSkeleton: require("./images/pocketGraphics/cat skeleton pocketSource.png"),
  ChildMoon: require("./images/pocketGraphics/Child on moon pocket.png"),
  CourageDog: require("./images/pocketGraphics/courage dog pocketSource.png"),
  CuteCat: require("./images/pocketGraphics/cute cat pocket.png"),
  Dollar: require("./images/pocketGraphics/Dollar pocketSource.png"),
  FallingCat: require("./images/pocketGraphics/falling cat pocketSource.png"),
  Fish: require("./images/pocketGraphics/fish pocketSource.png"),
  Ghost: require("./images/pocketGraphics/Ghost pocket.png"),
  GoldenCoins: require("./images/pocketGraphics/Golden coins pocket.png"),
  Heart: require("./images/pocketGraphics/Heart pocket.png"),
  Hotdog: require("./images/pocketGraphics/Hotdog-pocket.png"),
  Husky: require("./images/pocketGraphics/husky pocket.png"),
  Icecreampocket: require("./images/pocketGraphics/icecream pocket.png"),
  Knife: require("./images/pocketGraphics/knife pocket.png"),
  LoveAtFirstBite: require("./images/pocketGraphics/Love at first bite.png"),
  Minion: require("./images/pocketGraphics/minion pocketSource.png"),
  MonkeyButt: require("./images/pocketGraphics/monkey butt pocketSource.png"),
  Octopus: require("./images/pocketGraphics/Octopus pocket.png"),
  Palm: require("./images/pocketGraphics/palm pocketSource.png"),
  Panda: require("./images/pocketGraphics/Panda pocketSource.png"),
  PinupGirl: require("./images/pocketGraphics/Pin up girl pocket.png"),
  PinkPanther: require("./images/pocketGraphics/pink panter pocketSource.png"),
  Popcorn: require("./images/pocketGraphics/Popcorn pocket.png"),
  Pug: require("./images/pocketGraphics/pug pocketSource.png"),
  SeaStar: require("./images/pocketGraphics/Seastarspocket.png"),
  Sun: require("./images/pocketGraphics/Sun umbrella pocket.png"),
  Swimming: require("./images/pocketGraphics/Swimming pocketSource.png"),
  TropicalFruit: require("./images/pocketGraphics/Tropical fruits pocket.png"),
  WateringFlowers: require("./images/pocketGraphics/Watering flowers.png"),
  ZombieHands: require("./images/pocketGraphics/Zombie hands pocket.png"),
  
  // popArtGraphics
  
  AlbertKisstein: require("./images/PopArtGraphics/ALBERT KISSTEIN low.png"),
  AmericanPsycho2: require("./images/PopArtGraphics/AMERICAN PSYCHO 2 low.png"),
  AmericanPsycho: require("./images/PopArtGraphics/AMERICAN PSYCHO low.png"),
  BenjaminDranklin: require("./images/PopArtGraphics/Benjamin Dranklin low.png"),
  CharimanMeow: require("./images/PopArtGraphics/CHAIRMAN MEOW low.png"),
  Chef: require("./images/PopArtGraphics/CHEF low.png"),
  Covfefe: require("./images/PopArtGraphics/COVFEFE.png"),
  Dope: require("./images/PopArtGraphics/DOPE.png"),
  Dream: require("./images/PopArtGraphics/DREAM low.png"),
  GotMLK: require("./images/PopArtGraphics/GOT MLK low.png"),
  Heilstein: require("./images/PopArtGraphics/HEILSTEIN low.png"),
  HoHoHoChiMinh: require("./images/PopArtGraphics/ho ho ho chi minh.png"),
  ICantBreathe: require("./images/PopArtGraphics/I CANT BREATHE.png"),
  JusticeForGeorgeFloyd: require("./images/PopArtGraphics/justice for george floyd low.png"),
  LincolnUnknown: require("./images/PopArtGraphics/lincoln unknown low.png"),
  MakeAmericaGreyAgain: require("./images/PopArtGraphics/MAKE AMERICA GREY AGAIN.png"),
  MeowTseTung: require("./images/PopArtGraphics/Meow Tse Tung.png"),
  Merica: require("./images/PopArtGraphics/MERICA low.png"),
  MericaTrump: require("./images/PopArtGraphics/MERICA TRUMP low.png"),
  NoRacism: require("./images/PopArtGraphics/NO RACISM.png"),
  Putintin: require("./images/PopArtGraphics/PUTINTIN.png"),
  RocketBoy: require("./images/PopArtGraphics/ROCKETBOY low.png"),
  RocketMan: require("./images/PopArtGraphics/ROCKETMAN low.png"),
  StraigtOuttaPyongYang: require("./images/PopArtGraphics/STRAIGHT OUTTA PYONGYANG.png"),
  SylvesterStalin: require("./images/PopArtGraphics/SYLVESTER STALIN.png"),
  TheFuhrer: require("./images/PopArtGraphics/THE FUHRER.png"),
  Trump: require("./images/PopArtGraphics/TRUMP low.png"),
  UnderControl: require("./images/PopArtGraphics/UNDER CONTROL.png"),
  VivaLaEvolucion: require("./images/PopArtGraphics/viva la evolucion low.png"),
  WeCanDoIt: require("./images/PopArtGraphics/WE CAN DO IT.png"),
  
  // presidentGraphics 
  
  Franklin: require("./images/presidentGraphics/franklin.png"),
  Grant: require("./images/presidentGraphics/grant.png"),
  Hamilton: require("./images/presidentGraphics/hamilton.png"),
  Jackson: require("./images/presidentGraphics/jackson.png"),
  Jefferson: require("./images/presidentGraphics/jefferson.png"),
  Lincoln: require("./images/presidentGraphics/lincoln.png"),
  Washington: require("./images/presidentGraphics/washington.png"),
  
  // randomGraphics
  
  AnchorBones: require("./images/randomGraphics/Anchor Bones-02.png"),
  Anchor: require("./images/randomGraphics/Anchor.png"),
  Astrocode: require("./images/randomGraphics/Astrocode.png"),
  Awesome: require("./images/randomGraphics/Awesome.png"),
  BananaSkateboard: require("./images/randomGraphics/Banana Skateboard.png"),
  BaseballPlayer: require("./images/randomGraphics/Baseball Player.png"),
  BasketballPlayer: require("./images/randomGraphics/Basketball Player.png"),
  Beetle: require("./images/randomGraphics/Beetle.png"),
  BicycleSkull: require("./images/randomGraphics/Bicycle Skull.png"),
  BirdsBeard: require("./images/randomGraphics/Birds Beard.png"),
  BrainGloves: require("./images/randomGraphics/Brain Gloves.png"),
  BreakingNoise: require("./images/randomGraphics/Breaking Noise.png"),
  Burger: require("./images/randomGraphics/Burger.png"),
  Chainsaw: require("./images/randomGraphics/Chainsaw.png"),
  CheSmiley: require("./images/randomGraphics/Che Smiley.png"),
  CoffeeTree: require("./images/randomGraphics/Coffee Tree.png"),
  Coffee: require("./images/randomGraphics/Coffee.png"),
  Crab: require("./images/randomGraphics/Crab.png"),
  CrystalLake: require("./images/randomGraphics/Crystal Lake.png"),
  DeadSchool: require("./images/randomGraphics/Dead  School.png"),
  DeadSea: require("./images/randomGraphics/Dead Sea.png"),
  DeathCity: require("./images/randomGraphics/Death City.png"),
  Deer2: require("./images/randomGraphics/Deer 2.png"),
  Deer3: require("./images/randomGraphics/Deer 3.png"),
  DeerButterfly: require("./images/randomGraphics/Deer Butterfly.png"),
  Deer: require("./images/randomGraphics/Deer.png"),
  DonutBarbell: require("./images/randomGraphics/Donut Barbell.png"),
  Eagle: require("./images/randomGraphics/Eagle.png"),
  ElectricAnchor: require("./images/randomGraphics/Electric Anchor.png"),
  ElectricBalance: require("./images/randomGraphics/Electric Balance.png"),
  ElectricBrain: require("./images/randomGraphics/Electric Brain.png"),
  ElectricDeer: require("./images/randomGraphics/Electric Deer.png"),
  ElectricSkull: require("./images/randomGraphics/Electric Skull.png"),
  ElectricSmiley: require("./images/randomGraphics/Electric Smiley.png"),
  ElectricalOwl: require("./images/randomGraphics/Electrical Owl.png"),
  EnjoyYourLie: require("./images/randomGraphics/Enjoy Your Lie.png"),
  FloatLikeButterflyStingLikeBee: require("./images/randomGraphics/Float Like Butterfly Sting Like Bee.png"),
  FlourishVandalism: require("./images/randomGraphics/Flourish Vandalism.png"),
  FlyingAstronaut: require("./images/randomGraphics/Flying Astronaut.png"),
  FroggyNight: require("./images/randomGraphics/Froggy Night.png"),
  GhostFaceBats: require("./images/randomGraphics/Ghost Face Bats.png"),
  Godzilla: require("./images/randomGraphics/Godzilla.png"),
  GoodIdea: require("./images/randomGraphics/Good Idea.png"),
  GramophoneDonut: require("./images/randomGraphics/Gramophone Donut.png"),
  GreenMonster: require("./images/randomGraphics/Green Monster.png"),
  Grenade: require("./images/randomGraphics/Grenade.png"),
  HandOfRevolution: require("./images/randomGraphics/Hand Of Revolution.png"),
  HandOfZombies: require("./images/randomGraphics/Hand Of Zombies.png"),
  HeadphoneDonut: require("./images/randomGraphics/Headphone Donut.png"),
  Hipster: require("./images/randomGraphics/HIPSTER.png"),
  HomeHeart: require("./images/randomGraphics/Home Heart.png"),
  Icecream: require("./images/randomGraphics/Ice Cream.png"),
  JasonMoon: require("./images/randomGraphics/Jason Moon.png"),
  Kaiju2: require("./images/randomGraphics/Kaiju 2.png"),
  Kaiju: require("./images/randomGraphics/Kaiju.png"),
  KnowYourRoots: require("./images/randomGraphics/Know Your Roots.png"),
  Liberty: require("./images/randomGraphics/Liberty.png"),
  LifeAndDeath: require("./images/randomGraphics/Life And Death.png"),
  LOL: require("./images/randomGraphics/LOL.png"),
  Milkyway: require("./images/randomGraphics/Milky Way.png"),
  NatureOfCrime: require("./images/randomGraphics/Nature of Crime.png"),
  Nerd: require("./images/randomGraphics/NERD.png"),
  Peace: require("./images/randomGraphics/Peace.png"),
  PizzaMoon: require("./images/randomGraphics/Pizza Moon.png"),
  PizzaScratch: require("./images/randomGraphics/Pizza Scratch.png"),
  PizzaUFO: require("./images/randomGraphics/Pizza UFO.png"),
  Pizza: require("./images/randomGraphics/Pizza.png"),
  Prismzza: require("./images/randomGraphics/Prismzza.png"),
  ReaperScream: require("./images/randomGraphics/Reaper Scream.png"),
  Recycling: require("./images/randomGraphics/Recycling.png"),
  RhymeInPeace: require("./images/randomGraphics/Rhyme In Peace.png"),
  RibcageBird: require("./images/randomGraphics/Ribcage Bird.png"),
  Scooter: require("./images/randomGraphics/Scooter.png"),
  SeaHorse: require("./images/randomGraphics/Sea Horse.png"),
  SherlockHolmes: require("./images/randomGraphics/Sherlock Holmes.png"),
  Skater: require("./images/randomGraphics/Skater.png"),
  SkaterHook: require("./images/randomGraphics/Skaterhook.png"),
  SkullNature: require("./images/randomGraphics/Skull Nature.png"),
  SmileyMoon: require("./images/randomGraphics/Smiley Moon.png"),
  Smiley: require("./images/randomGraphics/Smiley.png"),
  SmokingKills: require("./images/randomGraphics/Smoking Kills.png"),
  SoundCollector: require("./images/randomGraphics/Sound Collector.png"),
  SoundOfRain: require("./images/randomGraphics/Sound Of Rain.png"),
  StandAndBleed: require("./images/randomGraphics/Stand And Bleed.png"),
  TheBridge: require("./images/randomGraphics/The Bridge.png"),
  TheChronicle: require("./images/randomGraphics/The Chronicle.png"),
  TheCrow: require("./images/randomGraphics/The Crow.png"),
  TheMask: require("./images/randomGraphics/The Mask.png"),
  Thunderbolt: require("./images/randomGraphics/Thunderbolt.png"),
  TrainSong: require("./images/randomGraphics/Train Song.png"),
  truthHurts: require("./images/randomGraphics/Truth Hurts.png"),
  UFOInvasion: require("./images/randomGraphics/UFO Invasion.png"),
  WarPeace: require("./images/randomGraphics/War Peace.png"),
  WeaponFlag: require("./images/randomGraphics/Weapon Flag.png"),
  WildBison: require("./images/randomGraphics/Wild Bison.png"),
  WildLife: require("./images/randomGraphics/Wild Life.png"),
  YinYangCats: require("./images/randomGraphics/YinYang Cats.png"),
  ZebraBones: require("./images/randomGraphics/Zebra Bones.png"),
  
  //BlackHistoryGraphics
  
  BHM365Days: require("./images/BlackHistoryGraphics/BLACK HISTORY MONT 365 DAYS.png"),
  BHMMalcolmX: require("./images/BlackHistoryGraphics/BLACK HISTORY MONTH MALCOLM X.png"),
  BHMMap: require("./images/BlackHistoryGraphics/BLACK HISTORY MONTH MAP.png"),
  BHMMLK: require("./images/BlackHistoryGraphics/BLACK HISTORY MONTH MLK.png"),
  BHMPowerHand: require("./images/BlackHistoryGraphics/BLACK HISTORY MONTH POWER HAND.png"),
  BHM: require("./images/BlackHistoryGraphics/BLACK HISTORY MONTH.png"),
  BH: require("./images/BlackHistoryGraphics/BLACK HISTORY.png"),
  BLMHand: require("./images/BlackHistoryGraphics/BLACK LIVES MATTER HAND.png"),
  MartinLutherJunior: require("./images/BlackHistoryGraphics/BLACK LIVES MATTER Martin Luther Junior.png"),
  BLMMLK: require("./images/BlackHistoryGraphics/BLACK LIVES MATTER MLK.png"),
  BlackLivesMatter: require("./images/BlackHistoryGraphics/BLACKLIVESMATTER.png"),
  DreamBH: require("./images/BlackHistoryGraphics/DREAM.png"),
  EnoughIsEnough: require("./images/BlackHistoryGraphics/ENOUGH IS ENOUGH.png"),
  FightForChange: require("./images/BlackHistoryGraphics/FIGHT FOR CHANGE.png"),
  FrederickDouglass: require("./images/BlackHistoryGraphics/FREDERICK DOUGLASS.png"),
  FreedomBH: require("./images/BlackHistoryGraphics/FREEDOM.png"),
  JohnLewis: require("./images/BlackHistoryGraphics/JOHN LEWIS.png"),
  EveryMonthBH: require("./images/BlackHistoryGraphics/MAKE EVERY MONTH BLACK HISTORY MONTH.png"),
  MalcolmXBH: require("./images/BlackHistoryGraphics/MALCOLM X BLACK HISTORY.png"),
  MLKBH: require("./images/BlackHistoryGraphics/MARTIN LUTHER KING BLACK HISTORY.png"),
  Riot: require("./images/BlackHistoryGraphics/RIOT.png"),
  WeCanDoIt: require("./images/BlackHistoryGraphics/WE CAN DO IT.png"),
  
  //CartoonGraphics
  
  Cat1: require("./images/CartoonGraphics/Cat 1.png"),
  Cat2: require("./images/CartoonGraphics/Cat 2.png"),
  Cat3: require("./images/CartoonGraphics/Cat 3.png"),
  Cat4: require("./images/CartoonGraphics/Cat 4.png"),
  Cat5: require("./images/CartoonGraphics/Cat 5.png"),
  Cat6: require("./images/CartoonGraphics/Cat 6.png"),
  Cat7: require("./images/CartoonGraphics/Cat 7.png"),
  Cat8: require("./images/CartoonGraphics/Cat 8.png"),
  Cat9: require("./images/CartoonGraphics/Cat 9.png"),
  Cat10: require("./images/CartoonGraphics/Cat 10.png"),
  Cat11: require("./images/CartoonGraphics/Cat 11.png"),
  Cat12: require("./images/CartoonGraphics/Cat 12.png"),
  Cat13: require("./images/CartoonGraphics/Cat 13.png"),
  Cat14: require("./images/CartoonGraphics/Cat 14.png"),
  Cat15: require("./images/CartoonGraphics/Cat 15.png"),
  Cat16: require("./images/CartoonGraphics/Cat 16.png"),
  Cat17: require("./images/CartoonGraphics/Cat 17.png"),
  Cat18: require("./images/CartoonGraphics/Cat 18.png"),
  Cat19: require("./images/CartoonGraphics/Cat 19.png"),
  Cat20: require("./images/CartoonGraphics/Cat 20.png"),
  Cat21: require("./images/CartoonGraphics/Cat 21.png"),
  Cat22: require("./images/CartoonGraphics/Cat 22.png"),
  Cat23: require("./images/CartoonGraphics/Cat 23.png"),
  Cat24: require("./images/CartoonGraphics/Cat 24.png"),
  Cat25: require("./images/CartoonGraphics/Cat 25.png"),
  Dog1: require("./images/CartoonGraphics/Dog 1.png"),
  Dog2: require("./images/CartoonGraphics/Dog 2.png"),
  Dog3: require("./images/CartoonGraphics/Dog 3.png"),
  Dog4: require("./images/CartoonGraphics/Dog 4.png"),
  Dog5: require("./images/CartoonGraphics/Dog 5.png"),
  Dog6: require("./images/CartoonGraphics/Dog 6.png"),
  Dog7: require("./images/CartoonGraphics/Dog 7.png"),
  Dog8: require("./images/CartoonGraphics/Dog 8.png"),
  Dog9: require("./images/CartoonGraphics/Dog 9.png"),
  Dog10: require("./images/CartoonGraphics/Dog 10.png"),
  Dog11: require("./images/CartoonGraphics/Dog 11.png"),
  Dog12: require("./images/CartoonGraphics/Dog 12.png"),
  Dog13: require("./images/CartoonGraphics/Dog 13.png"),
  Dog14: require("./images/CartoonGraphics/Dog 14.png"),
  Dog15: require("./images/CartoonGraphics/Dog 15.png"),
  Dog16: require("./images/CartoonGraphics/Dog 16.png"),
  Dog17: require("./images/CartoonGraphics/Dog 17.png"),
  Dog18: require("./images/CartoonGraphics/Dog 18.png"),
  Dog19: require("./images/CartoonGraphics/Dog 19.png"),
  Dog20: require("./images/CartoonGraphics/Dog 20.png"),
  Dog21: require("./images/CartoonGraphics/Dog 21.png"),
  Dog22: require("./images/CartoonGraphics/Dog 22.png"),
  Dog23: require("./images/CartoonGraphics/Dog 23.png"),
  Dog24: require("./images/CartoonGraphics/Dog 24.png"),
  Dog25: require("./images/CartoonGraphics/Dog 25.png"),
  Dragon1: require("./images/CartoonGraphics/Dragon 1.png"),
  Dragon2: require("./images/CartoonGraphics/Dragon 2.png"),
  Dragon3: require("./images/CartoonGraphics/Dragon 3.png"),
  Dragon4: require("./images/CartoonGraphics/Dragon 4.png"),
  Dragon5: require("./images/CartoonGraphics/Dragon 5.png"),
  Dragon6: require("./images/CartoonGraphics/Dragon 6.png"),
  Dragon7: require("./images/CartoonGraphics/Dragon 7.png"),
  Dragon8: require("./images/CartoonGraphics/Dragon 8.png"),
  Dragon9: require("./images/CartoonGraphics/Dragon 9.png"),
  Dragon10: require("./images/CartoonGraphics/Dragon 10.png"),
  Dragon11: require("./images/CartoonGraphics/Dragon 11.png"),
  Dragon12: require("./images/CartoonGraphics/Dragon 12.png"),
  Dragon13: require("./images/CartoonGraphics/Dragon 13.png"),
  Dragon14: require("./images/CartoonGraphics/Dragon 14.png"),
  Dragon15: require("./images/CartoonGraphics/Dragon 15.png"),
  Dragon16: require("./images/CartoonGraphics/Dragon 16.png"),
  Dragon17: require("./images/CartoonGraphics/Dragon 17.png"),
  Dragon18: require("./images/CartoonGraphics/Dragon 18.png"),
  Dragon19: require("./images/CartoonGraphics/Dragon 19.png"),
  Dragon20: require("./images/CartoonGraphics/Dragon 20.png"),
  Dragon21: require("./images/CartoonGraphics/Dragon 21.png"),
  Dragon22: require("./images/CartoonGraphics/Dragon 22.png"),
  Dragon23: require("./images/CartoonGraphics/Dragon 23.png"),
  Dragon24: require("./images/CartoonGraphics/Dragon 24.png"),
  Dragon25: require("./images/CartoonGraphics/Dragon 25.png"),
  Monster: require("./images/CartoonGraphics/Monster.png"),
  Monster1: require("./images/CartoonGraphics/Monster1.png"),
  Monster2: require("./images/CartoonGraphics/Monster2.png"),
  Monster3: require("./images/CartoonGraphics/Monster3.png"),
  Monster4: require("./images/CartoonGraphics/Monster4.png"),
  Monster5: require("./images/CartoonGraphics/Monster5.png"),
  Monster6: require("./images/CartoonGraphics/Monster6.png"),
  Monster7: require("./images/CartoonGraphics/Monster7.png"),
  Monster8: require("./images/CartoonGraphics/Monster8.png"),
  Monster9: require("./images/CartoonGraphics/Monster9.png"),
  Monster10: require("./images/CartoonGraphics/Monster10.png"),
  Monster11: require("./images/CartoonGraphics/Monster11.png"),
  Monster12: require("./images/CartoonGraphics/Monster12.png"),
  Monster13: require("./images/CartoonGraphics/Monster13.png"),
  Monster14: require("./images/CartoonGraphics/Monster14.png"),
  Monster15: require("./images/CartoonGraphics/Monster15.png"),
  Monster16: require("./images/CartoonGraphics/Monster16.png"),
  Monster17: require("./images/CartoonGraphics/Monster17.png"),
  Monster18: require("./images/CartoonGraphics/Monster18.png"),
  Monster19: require("./images/CartoonGraphics/Monster19.png"),
  Monster20: require("./images/CartoonGraphics/Monster20.png"),
  Monster21: require("./images/CartoonGraphics/Monster21.png"),
  Monster22: require("./images/CartoonGraphics/Monster22.png"),
  Monster23: require("./images/CartoonGraphics/Monster23.png"),
  Monster24: require("./images/CartoonGraphics/Monster24.png"),
  Monster25: require("./images/CartoonGraphics/Monster25.png"),
  Monster26: require("./images/CartoonGraphics/Monster26.png"),
  Monster27: require("./images/CartoonGraphics/Monster27.png"),
  Monster28: require("./images/CartoonGraphics/Monster28.png"),
  Monster29: require("./images/CartoonGraphics/Monster29.png"),
  Monster30: require("./images/CartoonGraphics/Monster30.png"),
  Monster31: require("./images/CartoonGraphics/Monster31.png"),
  Monster32: require("./images/CartoonGraphics/Monster32.png"),
  Monster33: require("./images/CartoonGraphics/Monster33.png"),
  Monster34: require("./images/CartoonGraphics/Monster34.png"),
  Monster35: require("./images/CartoonGraphics/Monster35.png"),
  Monster36: require("./images/CartoonGraphics/Monster36.png"),
  Monster37: require("./images/CartoonGraphics/Monster37.png"),
  Monster38: require("./images/CartoonGraphics/Monster38.png"),
  Monster39: require("./images/CartoonGraphics/Monster39.png"),
  Monster40: require("./images/CartoonGraphics/Monster40.png"),
  Monster41: require("./images/CartoonGraphics/Monster41.png"),
  Monster42: require("./images/CartoonGraphics/Monster42.png"),
  Monster43: require("./images/CartoonGraphics/Monster43.png"),
  Monster44: require("./images/CartoonGraphics/Monster44.png"),
  Monster45: require("./images/CartoonGraphics/Monster45.png"),
  Monster46: require("./images/CartoonGraphics/Monster46.png"),
  Monster47: require("./images/CartoonGraphics/Monster47.png"),
  Monster48: require("./images/CartoonGraphics/Monster48.png"),
  Monster49: require("./images/CartoonGraphics/Monster49.png"),
  Monster50: require("./images/CartoonGraphics/Monster50.png"),
  Snake1: require("./images/CartoonGraphics/Snake 1.png"),
  Snake2: require("./images/CartoonGraphics/Snake 2.png"),
  Snake3: require("./images/CartoonGraphics/Snake 3.png"),
  Snake4: require("./images/CartoonGraphics/Snake 4.png"),
  Snake5: require("./images/CartoonGraphics/Snake 5.png"),
  Snake6: require("./images/CartoonGraphics/Snake 6.png"),
  Snake7: require("./images/CartoonGraphics/Snake 7.png"),
  Snake8: require("./images/CartoonGraphics/Snake 8.png"),
  Snake9: require("./images/CartoonGraphics/Snake 9.png"),
  Snake10: require("./images/CartoonGraphics/Snake 10.png"),
  Snake11: require("./images/CartoonGraphics/Snake 11.png"),
  Snake12: require("./images/CartoonGraphics/Snake 12.png"),
  Snake13: require("./images/CartoonGraphics/Snake 13.png"),
  Snake14: require("./images/CartoonGraphics/Snake 14.png"),
  Snake15: require("./images/CartoonGraphics/Snake 15.png"),
  Snake16: require("./images/CartoonGraphics/Snake 16.png"),
  Snake17: require("./images/CartoonGraphics/Snake 17.png"),
  Snake18: require("./images/CartoonGraphics/Snake 18.png"),
  Snake19: require("./images/CartoonGraphics/Snake 19.png"),
  Snake20: require("./images/CartoonGraphics/Snake 20.png"),
  Snake21: require("./images/CartoonGraphics/Snake 21.png"),
  Snake22: require("./images/CartoonGraphics/Snake 22.png"),
  Snake23: require("./images/CartoonGraphics/Snake 23.png"),
  Snake24: require("./images/CartoonGraphics/Snake 24.png"),
  Snake25: require("./images/CartoonGraphics/Snake 25.png"),

  // Super Hero Graphics
  
  ANTIVENOMPOP: require("./images/SuperHeroGraphics/ANTI VENOM POP.png"),
  ANTMANENDGAME: require("./images/SuperHeroGraphics/ANTMAN ENDGAME.png"),
  ARYASTARK: require("./images/SuperHeroGraphics/ARYA STARK.png"),
  BACKTOTHEFUTURE: require("./images/SuperHeroGraphics/BACK TO THE FUTURE.png"),
  Battleforeternia: require("./images/SuperHeroGraphics/Battle for eternia.png"),
  BATMANYROBIN: require("./images/SuperHeroGraphics/BATMAN Y ROBIN.png"),
  BezitaVader: require("./images/SuperHeroGraphics/Bezita Vader.png"),
  blackpanter01: require("./images/SuperHeroGraphics/black panter 01.png"),
  BlackTrooper: require("./images/SuperHeroGraphics/Black Trooper.png"),
  BLACKWIDOWENDGAME: require("./images/SuperHeroGraphics/BLACK WIDOW ENDGAME.png"),
  BLACKW: require("./images/SuperHeroGraphics/BLACKW.png"),
  BRITNEY: require("./images/SuperHeroGraphics/BRITNEY.png"),
  CAPITANAMERICA2: require("./images/SuperHeroGraphics/CAPITAN AMERICA 2.png"),
  CAPITANAMERICA3: require("./images/SuperHeroGraphics/CAPITAN AMERICA 3.png"),
  CAPITANAMARVEL: require("./images/SuperHeroGraphics/CAPITANA MARVEL.png"),
  CAPTAINAMERICA1STAVENGER: require("./images/SuperHeroGraphics/CAPTAIN AMERICA 1ST AVENGER.png"),
  CAPTAINENDGAMEV2: require("./images/SuperHeroGraphics/CAPTAIN ENDGAME V2.png"),
  CAPTAINENDGAME: require("./images/SuperHeroGraphics/CAPTAIN ENDGAME.png"),
  CAPTAIN1: require("./images/SuperHeroGraphics/CAPTAIN1.png"),
  CasadepapelDalírun: require("./images/SuperHeroGraphics/Casa de papel Dalí run.png"),
  CasadepapelgrupoCartoon: require("./images/SuperHeroGraphics/Casa de papel grupo Cartoon.png"),
  casadepapel: require("./images/SuperHeroGraphics/casa de papel.png"),
  CHEWBACCA: require("./images/SuperHeroGraphics/CHEWBACCA.png"),
  chubaca: require("./images/SuperHeroGraphics/chubaca.png"),
  DAENERYS1: require("./images/SuperHeroGraphics/DAENERYS 1.png"),
  DAERAVILFUNKOVECTOR: require("./images/SuperHeroGraphics/DAERAVIL FUNKO VECTOR.png"),
  deadtina: require("./images/SuperHeroGraphics/dead tina.png"),
  deadpool01: require("./images/SuperHeroGraphics/deadpool 01.png"),
  DeadpoolMercenary: require("./images/SuperHeroGraphics/Deadpool Mercenary.png"),
  DeadpoolTacos: require("./images/SuperHeroGraphics/Deadpool Tacos.png"),
  DEADPOOL: require("./images/SuperHeroGraphics/DEADPOOL.png"),
  Droids: require("./images/SuperHeroGraphics/Droids.png"),
  Dumbo2: require("./images/SuperHeroGraphics/Dumbo 2.png"),
  FLINTSTONES: require("./images/SuperHeroGraphics/FLINTSTONES.png"),
  FLYINGDRAGON: require("./images/SuperHeroGraphics/FLYINGDRAGON.png"),
  FORTNITE: require("./images/SuperHeroGraphics/FORTNITE.png"),
  FreddyvsJason: require("./images/SuperHeroGraphics/Freddy vs Jason.png"),
  Freddy: require("./images/SuperHeroGraphics/Freddy.png"),
  FUNKOIT: require("./images/SuperHeroGraphics/FUNKO IT.png"),
  funkovegeta: require("./images/SuperHeroGraphics/funko vegeta.png"),
  GHOSTBUSTERS4: require("./images/SuperHeroGraphics/GHOSTBUSTERS 4.png"),
  GHOSTBUSTERS: require("./images/SuperHeroGraphics/GHOSTBUSTERS.png"),
  GROOT2: require("./images/SuperHeroGraphics/GROOT 2.png"),
  GROOT: require("./images/SuperHeroGraphics/GROOT.png"),
  HarleyQueen: require("./images/SuperHeroGraphics/HarleyQueen.png"),
  HarleyQueenB: require("./images/SuperHeroGraphics/HarleyQueenB.png"),
  HARRYPOTTER2: require("./images/SuperHeroGraphics/HARRY POTTER 2.png"),
  HARRYPOTTER1: require("./images/SuperHeroGraphics/HARRY POTTER1.png"),
  HEISENBERG: require("./images/SuperHeroGraphics/HEISENBERG.png"),
  HERMIONE: require("./images/SuperHeroGraphics/HERMIONE.png"),
  ENDGAMEV2: require("./images/SuperHeroGraphics/HULK ENDGAME V2.png"),
  ENDGAME: require("./images/SuperHeroGraphics/HULK ENDGAME.png"),
  HULK: require("./images/SuperHeroGraphics/HULK.png"),
  IRONSPIDER: require("./images/SuperHeroGraphics/IRON SPIDER.png"),
  IRONMANENDGAME: require("./images/SuperHeroGraphics/IRONMAN ENDGAME.png"),
  It: require("./images/SuperHeroGraphics/It.png"),
  JIMIHENDRIX: require("./images/SuperHeroGraphics/JIMI HENDRIX.png"),
  JOKER: require("./images/SuperHeroGraphics/JOKER.png"),
  JURASICPOP: require("./images/SuperHeroGraphics/JURASIC POP.png"),
  JURASIC2: require("./images/SuperHeroGraphics/JURASSIC2.png"),
  kissfunko: require("./images/SuperHeroGraphics/kiss funko.png"),
  LOKISARMY: require("./images/SuperHeroGraphics/LOKIS ARMY.png"),
  MARTYSKATEBOARD: require("./images/SuperHeroGraphics/MARTY SKATEBOARD.png"),
  MARTY: require("./images/SuperHeroGraphics/MARTY.png"),
  MEGAMANFUNKO: require("./images/SuperHeroGraphics/MEGAMAN FUNKO.png"),
  NIGHTKING2: require("./images/SuperHeroGraphics/NIGHT KING 2.png"),
  NIGHTKING3: require("./images/SuperHeroGraphics/NIGHT KING 3.png"),
  NIGHTKING: require("./images/SuperHeroGraphics/NIGHT KING.png"),
  PREDATOR: require("./images/SuperHeroGraphics/PREDATOR.png"),
  REBELLIONEMPIRE: require("./images/SuperHeroGraphics/REBELLION EMPIRE.png"),
  ROCKSTEADY: require("./images/SuperHeroGraphics/ROCKSTEADY.png"),
  RONINENDGAME: require("./images/SuperHeroGraphics/RONIN ENDGAME.png"),
  ScartTerry: require("./images/SuperHeroGraphics/Scart Terry.png"),
  SIRENITA: require("./images/SuperHeroGraphics/SIRENITA.png"),
  SKELETOR2: require("./images/SuperHeroGraphics/SKELETOR 2.png"),
  SKELETORCONQUERGRAYSKULL: require("./images/SuperHeroGraphics/SKELETOR CONQUER GRAYSKULL.png"),
  SONIC: require("./images/SuperHeroGraphics/SONIC.png"),
  SPIDERMAN2: require("./images/SuperHeroGraphics/SPIDERMAN 2.png"),
  SPIDERMAN: require("./images/SuperHeroGraphics/SPIDERMAN.png"),
  STANLEECOMPL: require("./images/SuperHeroGraphics/STAN LEE COMPL.png"),
  STITCH: require("./images/SuperHeroGraphics/STITCH.png"),
  STORMTROOPER: require("./images/SuperHeroGraphics/STORM TROOPER.png"),
  SUPERMAN: require("./images/SuperHeroGraphics/SUPERMAN.png"),
  TARGARYEN: require("./images/SuperHeroGraphics/TARGARYEN.png"),
  THANOSENDGAMEV2: require("./images/SuperHeroGraphics/THANOS ENDGAME V2.png"),
  THANOSENDGAME: require("./images/SuperHeroGraphics/THANOS ENDGAME.png"),
  THANOS: require("./images/SuperHeroGraphics/THANOS.png"),
  TheJoker: require("./images/SuperHeroGraphics/The Joker.png"),
  THOR4: require("./images/SuperHeroGraphics/THOR 4.png"),
  THORENDGAME: require("./images/SuperHeroGraphics/THOR ENDGAME.png"),
  thor: require("./images/SuperHeroGraphics/thor.png"),
  TMNT2: require("./images/SuperHeroGraphics/TMNT 2.png"),
  Turtles: require("./images/SuperHeroGraphics/Turtles.png"),
  VADERKENOBI: require("./images/SuperHeroGraphics/VADER KENOBI.png"),
  VENOM2: require("./images/SuperHeroGraphics/VENOM 2.png"),
  VENOM1: require("./images/SuperHeroGraphics/VENOM1.png"),
  WONDERWOMANRETRO: require("./images/SuperHeroGraphics/WONDER WOMAN RETRO.png"),
  wonderwomanfunko: require("./images/SuperHeroGraphics/wonder woman funko.png"),
};

export default IMG;


