import IMG from "./photoIMPORTS";
import { nanoid } from "nanoid";

const Photos = [
  {
    id: nanoid(),
    src: IMG.AstronautIceCream,
    alt: "astronaut in space eating ice cream in color",
    name: "Astronaut Ice Cream",
    fee: 3,
  },
  {
    id: nanoid(),
    src: IMG.BarberSkater,
    alt: "barbershop pole with scrissors and skateboard in color",
    name: "Barber Skater",
    fee: 3,
  },
  {
    id: nanoid(),
    src: IMG.BasketBallBombers,
    alt: "a bomb wearing shoes and hat and spinning a basketball in black and white",
    name: "BasketBall Bombers",
    fee: 3,
  },
  {
    id: nanoid(),
    src: IMG.Bomber,
    alt: "man with spray paint can and gas mask in black and white",
    name: "Bomber",
    fee: 3,
  },
  {
    id: nanoid(),
    src: IMG.BoomboxRobot,
    alt: "a transformers-like robot in front of yellow moon in color",
    name: "Boombox Robot",
    fee: 3,
  },
  {
    id: nanoid(),
    src: IMG.BoxingChampion,
    alt: "a character wearing oversized headgear and boxing gloves in color",
    name: "Boxing Champion",
    fee: 3,
  },
  {
    id: nanoid(),
    src: IMG.BrickGamers,
    alt: "a handheld gaming console with backwards hat in color",
    name: "Brick Gamers",
    fee: 3,
  },
  {
    id: nanoid(),
    src: IMG.BrooklynBaseball,
    alt: "a baseball character with bat ready to swing at a pitch in black and white",
    name: "Brooklyn Baseball",
    fee: 3,
  },
  {
    id: nanoid(),
    src: IMG.BurgerBastard,
    alt: "a hamburger character holding a spiked bat amd soda in color",
    name: "Burger Bastard",
    fee: 3,
  },
  {
    id: nanoid(),
    src: IMG.BurgerScooter,
    alt: "a hamburger character riding a motorized scooter in color",
    name: "Burger Scooter",
    fee: 3,
  },
  {
    id: nanoid(),
    src: IMG.CaferacerHelmet,
    alt: "character in large helmet riding a motorbike in color",
    name: "Cafe Racer Helmet",
    fee: 3,
  },
  {
    id: nanoid(),
    src: IMG.CashRules,
    alt: "a character made of money holding two guns in color",
    name: "Cash Rules",
    fee: 3,
  },
  {
    id: nanoid(),
    src: IMG.ChainsawKiller,
    alt: "man in hockey mask holding a chainsaw in monotone",
    name: "Chainsaw Killer",
    fee: 3,
  },
  {
    id: nanoid(),
    src: IMG.ChocolateSquad,
    alt: "candy characters holding a boombox in color",
    name: "Chocolate Squad",
    fee: 3,
  },
  {
    id: nanoid(),
    src: IMG.CigaretteKiller,
    alt: "a pack of cigarettes holding a revolver in color",
    name: "Cigarette Killer",
    fee: 3,
  },
  {
    id: nanoid(),
    src: IMG.ClassicCameraman,
    alt: "an old-style film camera giving the peace sign in black and white",
    name: "Classic Cameraman",
    fee: 3,
  },
  {
    id: nanoid(),
    src: IMG.Diver,
    alt: "a character in an oversized old-style diving helmet holding a sword in color",
    name: "Diver",
    fee: 3,
  },
  {
    id: nanoid(),
    src: IMG.DonutSkater,
    alt: "a donut with sunglasses riding a skateboard in color",
    name: "Donut Skater",
    fee: 3,
  },
  {
    id: nanoid(),
    src: IMG.DoubleStickMan,
    alt: "a pair of nunchucks with hands and feet in color",
    name: "Double StickMan",
    fee: 3,
  },
  {
    id: nanoid(),
    src: IMG.Fighter,
    alt: "man in NY Yankees hat ready to fight in black and white",
    name: "Fighter",
    fee: 3,
  },
  {
    id: nanoid(),
    src: IMG.FootballKing,
    alt: "football character wearing crown and holding trophy in color",
    name: "Football King",
    fee: 3,
  },
  {
    id: nanoid(),
    src: IMG.FootballPlayer,
    alt: "footballl helmet running with ball in color",
    name: "Football Player",
    fee: 3,
  },
  {
    id: nanoid(),
    src: IMG.FrankRace,
    alt: "frankenstein monster driving hotrod in color",
    name: "Frank Race",
    fee: 3,
  },
  {
    id: nanoid(),
    src: IMG.GameKid,
    alt: "gameboy console holding boombox in color",
    name: "Game Kid",
    fee: 3,
  },
  {
    id: nanoid(),
    src: IMG.GameMachine,
    alt: "old gaming machine wearing hat and glasses and holding ice cream in color",
    name: "Game Machine",
    fee: 3,
  },
  {
    id: nanoid(),
    src: IMG.GameOn1,
    alt: "handheld gaming connsole holding bat in color",
    name: "Game On 1",
    fee: 3,
  },
  {
    id: nanoid(),
    src: IMG.GameOn2,
    alt: "handheld gaming connsole holding bat in color",
    name: "Game On 2",
    fee: 3,
  },
  {
    id: nanoid(),
    src: IMG.GamersKiller,
    alt: "handheld gaming console holding bloody knife in color",
    name: "Gamers Killer",
    fee: 3,
  },
  {
    id: nanoid(),
    src: IMG.GiftFromOuterSpace,
    alt: "astronaut in space holding balloons in color",
    name: "Gift From Outer Space",
    fee: 3,
  },
  {
    id: nanoid(),
    src: IMG.Golfer,
    alt: "golfball character swinging club in black and white",
    name: "Golfer",
    fee: 3,
  },
  {
    id: nanoid(),
    src: IMG.GramophoneHead,
    alt: "oldstyle vintage record player wearing monocle and tophat in black and white",
    name: "Gramophone Head",
    fee: 3,
  },
  {
    id: nanoid(),
    src: IMG.GrenadeBrain,
    alt: "a brain with components to look like a grenade in black and white",
    name: "Grenade Brain",
    fee: 3,
  },
  {
    id: nanoid(),
    src: IMG.GrenadeHeart,
    alt: "a heart with components to look like a grenade in monochrome",
    name: "Grenade Heart",
    fee: 3,
  },
  {
    id: nanoid(),
    src: IMG.GrenadeRibcage,
    alt: "a ribcage with components to look like a grenade in monochrome",
    name: "Grenade Ribcage",
    fee: 3,
  },
  {
    id: nanoid(),
    src: IMG.Grenade,
    alt: "a grenade character wearing glasses in monochrome",
    name: "Grenade",
    fee: 3,
  },
  {
    id: nanoid(),
    src: IMG.HeartToKill,
    alt: "a heart character holding two guns in color",
    name: "Heart To Kill",
    fee: 3,
  },
  {
    id: nanoid(),
    src: IMG.Hello,
    alt: "a telephone booth making a phone call in color",
    name: "Hello",
    fee: 3,
  },
  {
    id: nanoid(),
    src: IMG.ILikeDonut,
    alt: "a character with a donut head eating a donut in color",
    name: "I Like Donut",
    fee: 3,
  },
  {
    id: nanoid(),
    src: IMG.ILoveBurger,
    alt: "a character with a hamburger head eating a burger in color",
    name: "I Love Burger",
    fee: 3,
  },
  {
    id: nanoid(),
    src: IMG.IceCreamNinja,
    alt: "a sundae ice cream cone with swords in color",
    name: "Ice Cream Ninja",
    fee: 3,
  },
  {
    id: nanoid(),
    src: IMG.IceCreamTruck,
    alt: "an ice cream truck driven by a man with a mask holding a cone in color",
    name: "Ice Cream Truck",
    fee: 3,
  },
  {
    id: nanoid(),
    src: IMG.KillerMinibike,
    alt: "a character in a hockey mask riding a bike and holding a knife in color",
    name: "Killer Minibike",
    fee: 3,
  },
  {
    id: nanoid(),
    src: IMG.KillerSkater,
    alt: "a masked character riding a skateboard and holding a bloody knife in color",
    name: "Killer Skater",
    fee: 3,
  },
  {
    id: nanoid(),
    src: IMG.LetsPaint,
    alt: "a can of paint holding a painbrush in monochrome",
    name: "Let's Paint",
    fee: 3,
  },
  {
    id: nanoid(),
    src: IMG.LetsPlay,
    alt: "a nintendo controller holding a gun and a soda in color",
    name: "Let's Play",
    fee: 3,
  },
  {
    id: nanoid(),
    src: IMG.LetsPlay2,
    alt: "an Xbox controller holding a gun and a soda in color",
    name: "Let's Play 2",
    fee: 3,
  },
  {
    id: nanoid(),
    src: IMG.LightBoy,
    alt: "a cracked lightbuld wearing a hat in black and white",
    name: "Light Boy",
    fee: 3,
  },
  {
    id: nanoid(),
    src: IMG.MicrophoneKing,
    alt: "an elvis character holding a micrphone in black and white",
    name: "Microphone King",
    fee: 3,
  },
  {
    id: nanoid(),
    src: IMG.MoneyTakers,
    alt: "a bag of money holding a gun in black and white",
    name: "Money Takers",
    fee: 3,
  },
  {
    id: nanoid(),
    src: IMG.Money,
    alt: "a stack of money holding an umbrella and a drink in color",
    name: "Money",
    fee: 3,
  },
  {
    id: nanoid(),
    src: IMG.MrCoffee,
    alt: "a coffee character wearing glasses and riding a skateboard in black and white",
    name: "Mr Coffee",
    fee: 3,
  },
  {
    id: nanoid(),
    src: IMG.MummyRace,
    alt: "a wrapped mummy riding a hot rod in color",
    name: "Mummy Race",
    fee: 3,
  },
  {
    id: nanoid(),
    src: IMG.Peace,
    alt: "a peace sign riding a skatebord and wearing a hat in color",
    name: "Peace",
    fee: 3,
  },
  {
    id: nanoid(),
    src: IMG.Pilot,
    alt: "a pilot flying a fighter jet and giving thumbs up in black and white",
    name: "Pilot",
    fee: 3,
  },
  {
    id: nanoid(),
    src: IMG.PizzaBeard,
    alt: "a hipster character holding and axe and a drink in color",
    name: "Pizza Beard",
    fee: 3,
  },
  {
    id: nanoid(),
    src: IMG.PizzaGangster,
    alt: "a slice of pizza holding two guns and wearing a bandana in color",
    name: "Pizza Gangster",
    fee: 3,
  },
  {
    id: nanoid(),
    src: IMG.PizzaSkater,
    alt: "a slice of pizza wearing a hat and riding a skateboard in color",
    name: "Pizza Skater",
    fee: 3,
  },
  {
    id: nanoid(),
    src: IMG.PlayerHead1,
    alt: "a man with a controller for a head holding a pipe wrench in color",
    name: "Player Head 1",
    fee: 3,
  },
  {
    id: nanoid(),
    src: IMG.PlayerHead2,
    alt: "an animal with a controller for a head giving thumbs up in color",
    name: "Player Head 2",
    fee: 3,
  },
  {
    id: nanoid(),
    src: IMG.PlayerSkater,
    alt: "a man  with a controller for a head holding a wrench and soda riding a skateboard in color",
    name: "Player Skater",
    fee: 3,
  },
  {
    id: nanoid(),
    src: IMG.Polaroid,
    alt: "a polaroid camera holding a slurpee and riding a skateboard in color",
    name: "Polaroid",
    fee: 3,
  },
  {
    id: nanoid(),
    src: IMG.Racer,
    alt: "a race car character in color",
    name: "Racer",
    fee: 3,
  },
  {
    id: nanoid(),
    src: IMG.RamenStyle,
    alt: "a bowl of ramen holding a skateboard in color",
    name: "Ramen Style",
    fee: 3,
  },
  {
    id: nanoid(),
    src: IMG.RobotBoombox,
    alt: "a robot dressed like a b-boy and holding a boombox in color",
    name: "Robot Boombox",
    fee: 3,
  },
  {
    id: nanoid(),
    src: IMG.RubixKiller,
    alt: "a rubix cube holding two guns in color",
    name: "Rubix Killer",
    fee: 3,
  },
  {
    id: nanoid(),
    src: IMG.Sailor,
    alt: "a pirate ship holding a sword in black and white",
    name: "Sailor",
    fee: 3,
  },
  {
    id: nanoid(),
    src: IMG.SamuraiRider,
    alt: "a man in knight armor riding a BMX bike in black and white",
    name: "Samurai Rider",
    fee: 3,
  },
  {
    id: nanoid(),
    src: IMG.Samurai,
    alt: "a man in samurai gear holding a sword in black and white",
    name: "Samurai",
    fee: 3,
  },
  {
    id: nanoid(),
    src: IMG.Savage,
    alt: "a man wearing a gas mask and hat and holding a gun in color",
    name: "Savage",
    fee: 3,
  },
  {
    id: nanoid(),
    src: IMG.ScooterSkater,
    alt: "a scooter that is riding a skateboard in color",
    name: "Scooter Skater",
    fee: 3,
  },
  {
    id: nanoid(),
    src: IMG.Shooter,
    alt: "a camera holding a revolver in black and white",
    name: "Shooter",
    fee: 3,
  },
  {
    id: nanoid(),
    src: IMG.SkateBastard,
    alt: "a skateboard holding a boombox and a drink in color",
    name: "Skate Bastard",
    fee: 3,
  },
  {
    id: nanoid(),
    src: IMG.SkaterBomb,
    alt: "a bomb character riding a skateboard holding a soda in black and white",
    name: "Skater Bomb",
    fee: 3,
  },
  {
    id: nanoid(),
    src: IMG.Skatespace,
    alt: "an astronaut in space riding a skateboard in black and white",
    name: "Skatespace",
    fee: 3,
  },
  {
    id: nanoid(),
    src: IMG.Soldier,
    alt: "an army helmet holding an M16 rifle in color",
    name: "Soldier",
    fee: 3,
  },
  {
    id: nanoid(),
    src: IMG.SpaceBike,
    alt: "an astronaut in space riding a bike in color",
    name: "Space Bike",
    fee: 3,
  },
  {
    id: nanoid(),
    src: IMG.SpaceJump,
    alt: "an astronaut in space reaching for saturn in monocrome",
    name: "Space Jump",
    fee: 3,
  },
  {
    id: nanoid(),
    src: IMG.SpaceRacer,
    alt: "an astronaut driving a hot rod in monochrome",
    name: "Space Racer",
    fee: 3,
  },
  {
    id: nanoid(),
    src: IMG.SpaceSlider,
    alt: "an astronaut in space holding balloons in color",
    name: "Space Slider",
    fee: 3,
  },
  {
    id: nanoid(),
    src: IMG.StayFresh,
    alt: "a watermelon slice holding a drink in color",
    name: "Stay Fresh",
    fee: 3,
  },
  {
    id: nanoid(),
    src: IMG.SteampunkHeart,
    alt: "a heart made of gears in color",
    name: "Steampunk Heart",
    fee: 3,
  },
  {
    id: nanoid(),
    src: IMG.SteampunkOwl,
    alt: "an owl in a tophat made of gears in color",
    name: "Steampunk Owl",
    fee: 3,
  },
  {
    id: nanoid(),
    src: IMG.SteampunkRibcage,
    alt: "a ribcage made of metal and gears in monochrome",
    name: "Steampunk Ribcage",
    fee: 3,
  },
  {
    id: nanoid(),
    src: IMG.SteampunkTRex,
    alt: "a T-rex wearing a tophat and made of gears and metal in monochrome",
    name: "Steampunk T-Rex",
    fee: 3,
  },
  {
    id: nanoid(),
    src: IMG.StreetBasketball,
    alt: "a basketball character holding a boombox in color",
    name: "Street Basketball",
    fee: 3,
  },
  {
    id: nanoid(),
    src: IMG.StreetBeetle,
    alt: "a VW beetle wearing a NY hat in color",
    name: "Street Beetle",
    fee: 3,
  },
  {
    id: nanoid(),
    src: IMG.StreetBomber,
    alt: "a spraypaint can wearing hat and riding skateboard with boombox in color",
    name: "Street Bomber",
    fee: 3,
  },
  {
    id: nanoid(),
    src: IMG.StreetGamers,
    alt: "a gameboy console riding a skateboard in color",
    name: "Street Gamers",
    fee: 3,
  },
  {
    id: nanoid(),
    src: IMG.StreetKing,
    alt: "a royal crown holding a boom box in color",
    name: "Street King",
    fee: 3,
  },
  {
    id: nanoid(),
    src: IMG.StreetSoccer,
    alt: "a soccer ball wearing a hat and kicking a soccer ball in color",
    name: "Street Soccer",
    fee: 3,
  },
  {
    id: nanoid(),
    src: IMG.Surprise,
    alt: "a jack in the box character wearing mask and top hat holding knife in color",
    name: "Surprise",
    fee: 3,
  },
  {
    id: nanoid(),
    src: IMG.Taco,
    alt: "a taco character holding baseball bat in color",
    name: "Taco",
    fee: 3,
  },
  {
    id: nanoid(),
    src: IMG.ToasterMonster,
    alt: "a toaster holding a drink in color",
    name: "Toaster Monster",
    fee: 3,
  },
  {
    id: nanoid(),
    src: IMG.TrainKiller,
    alt: "a train car holding a revolver in color",
    name: "Train Killer",
    fee: 3,
  },
  {
    id: nanoid(),
    src: IMG.Vandalism,
    alt: "a can of spray paint with muliple arms in monochrome",
    name: "Vandalism",
    fee: 3,
  },
  {
    id: nanoid(),
    src: IMG.Viking,
    alt: "a viking character holding axe in black and white",
    name: "Viking",
    fee: 3,
  },
  {
    id: nanoid(),
    src: IMG.VintageRobot,
    alt: "an old style robot graphic in color",
    name: "Vintage Robot",
    fee: 3,
  },
  {
    id: nanoid(),
    src: IMG.WarTank,
    alt: "a tank wearing a helmut and pointing ahead in color",
    name: "War Tank",
    fee: 3,
  },
  {
    id: nanoid(),
    src: IMG.YourTimeWillCome,
    alt: "a clock wearing a grim reaper cloak and holding a sickle in color",
    name: "Your Time Will Come",
    fee: 3,
  },
  {
    id: nanoid(),
    src: IMG.ZombieCassette,
    alt: "a cassette tape wearing a hat that says brain in color",
    name: "Zombie Cassette",
    fee: 3,
  },
];
export default Photos;

// {
//   id: nanoid(),
//   src: IMG.stufffffff,
//   alt: "eraseThis",
//   name: "eraseThis",
//   fee: 3,
// },
